issues:
  exclude-rules:
    # Exclude issues bypassing staticcheck.conf
    - linters:
        - staticcheck
      text: "SA1019:"

    - linters:
        - unparam
      text: "always receives"

  max-per-linter: 0
  max-same-issues: 0

linters:
  disable-all: true
  enable:
    - deadcode
    - gosimple
    - ineffassign
    - staticcheck
    - vet

linters-settings:
  errcheck:
    ignore: github.com/hashicorp/terraform-plugin-sdk/helper/schema:ForceNew|Set,fmt:.*,io:Close

run:
  timeout: 10m
go: '1.18'