// Code generated by go-swagger; DO NOT EDIT.

package ip_collection

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/chmurakrajowa/terraform-provider-ochk/ochk/api/v3/models"
)

// NewPutIpcsParams creates a new PutIpcsParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewPutIpcsParams() *PutIpcsParams {
	return &PutIpcsParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewPutIpcsParamsWithTimeout creates a new PutIpcsParams object
// with the ability to set a timeout on a request.
func NewPutIpcsParamsWithTimeout(timeout time.Duration) *PutIpcsParams {
	return &PutIpcsParams{
		timeout: timeout,
	}
}

// NewPutIpcsParamsWithContext creates a new PutIpcsParams object
// with the ability to set a context for a request.
func NewPutIpcsParamsWithContext(ctx context.Context) *PutIpcsParams {
	return &PutIpcsParams{
		Context: ctx,
	}
}

// NewPutIpcsParamsWithHTTPClient creates a new PutIpcsParams object
// with the ability to set a custom HTTPClient for a request.
func NewPutIpcsParamsWithHTTPClient(client *http.Client) *PutIpcsParams {
	return &PutIpcsParams{
		HTTPClient: client,
	}
}

/*
PutIpcsParams contains all the parameters to send to the API endpoint

	for the put ipcs operation.

	Typically these are written to a http.Request.
*/
type PutIpcsParams struct {

	// Body.
	Body *models.IPCollection

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the put ipcs params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PutIpcsParams) WithDefaults() *PutIpcsParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the put ipcs params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PutIpcsParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the put ipcs params
func (o *PutIpcsParams) WithTimeout(timeout time.Duration) *PutIpcsParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the put ipcs params
func (o *PutIpcsParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the put ipcs params
func (o *PutIpcsParams) WithContext(ctx context.Context) *PutIpcsParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the put ipcs params
func (o *PutIpcsParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the put ipcs params
func (o *PutIpcsParams) WithHTTPClient(client *http.Client) *PutIpcsParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the put ipcs params
func (o *PutIpcsParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the put ipcs params
func (o *PutIpcsParams) WithBody(body *models.IPCollection) *PutIpcsParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the put ipcs params
func (o *PutIpcsParams) SetBody(body *models.IPCollection) {
	o.Body = body
}

// WriteToRequest writes these params to a swagger request
func (o *PutIpcsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
