variable "test-data-prefix" {}
variable "host" {}
variable "tenant" {}
variable "username" {}
variable "password" {}
variable "debug_log_file" {}
variable "test_user" {}
variable "subtenant_network_name" {}
variable "subtenant_for_vm_name" {}
