// Code generated by go-swagger; DO NOT EDIT.

package custom_services

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/chmurakrajowa/terraform-provider-ochk/ochk/api/v3/models"
)

// GetNetworkCustomServicesServiceIDReader is a Reader for the GetNetworkCustomServicesServiceID structure.
type GetNetworkCustomServicesServiceIDReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetNetworkCustomServicesServiceIDReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetNetworkCustomServicesServiceIDOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewGetNetworkCustomServicesServiceIDBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 401:
		result := NewGetNetworkCustomServicesServiceIDUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 403:
		result := NewGetNetworkCustomServicesServiceIDForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewGetNetworkCustomServicesServiceIDNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[GET /network/custom-services/{serviceId}] GetNetworkCustomServicesServiceID", response, response.Code())
	}
}

// NewGetNetworkCustomServicesServiceIDOK creates a GetNetworkCustomServicesServiceIDOK with default headers values
func NewGetNetworkCustomServicesServiceIDOK() *GetNetworkCustomServicesServiceIDOK {
	return &GetNetworkCustomServicesServiceIDOK{}
}

/*
GetNetworkCustomServicesServiceIDOK describes a response with status code 200, with default header values.

OK
*/
type GetNetworkCustomServicesServiceIDOK struct {
	Payload *models.GetCustomServiceResponse
}

// IsSuccess returns true when this get network custom services service Id o k response has a 2xx status code
func (o *GetNetworkCustomServicesServiceIDOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this get network custom services service Id o k response has a 3xx status code
func (o *GetNetworkCustomServicesServiceIDOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get network custom services service Id o k response has a 4xx status code
func (o *GetNetworkCustomServicesServiceIDOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this get network custom services service Id o k response has a 5xx status code
func (o *GetNetworkCustomServicesServiceIDOK) IsServerError() bool {
	return false
}

// IsCode returns true when this get network custom services service Id o k response a status code equal to that given
func (o *GetNetworkCustomServicesServiceIDOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the get network custom services service Id o k response
func (o *GetNetworkCustomServicesServiceIDOK) Code() int {
	return 200
}

func (o *GetNetworkCustomServicesServiceIDOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /network/custom-services/{serviceId}][%d] getNetworkCustomServicesServiceIdOK %s", 200, payload)
}

func (o *GetNetworkCustomServicesServiceIDOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /network/custom-services/{serviceId}][%d] getNetworkCustomServicesServiceIdOK %s", 200, payload)
}

func (o *GetNetworkCustomServicesServiceIDOK) GetPayload() *models.GetCustomServiceResponse {
	return o.Payload
}

func (o *GetNetworkCustomServicesServiceIDOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.GetCustomServiceResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetNetworkCustomServicesServiceIDBadRequest creates a GetNetworkCustomServicesServiceIDBadRequest with default headers values
func NewGetNetworkCustomServicesServiceIDBadRequest() *GetNetworkCustomServicesServiceIDBadRequest {
	return &GetNetworkCustomServicesServiceIDBadRequest{}
}

/*
GetNetworkCustomServicesServiceIDBadRequest describes a response with status code 400, with default header values.

Bad Request
*/
type GetNetworkCustomServicesServiceIDBadRequest struct {
	Payload *models.ProblemDetails
}

// IsSuccess returns true when this get network custom services service Id bad request response has a 2xx status code
func (o *GetNetworkCustomServicesServiceIDBadRequest) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get network custom services service Id bad request response has a 3xx status code
func (o *GetNetworkCustomServicesServiceIDBadRequest) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get network custom services service Id bad request response has a 4xx status code
func (o *GetNetworkCustomServicesServiceIDBadRequest) IsClientError() bool {
	return true
}

// IsServerError returns true when this get network custom services service Id bad request response has a 5xx status code
func (o *GetNetworkCustomServicesServiceIDBadRequest) IsServerError() bool {
	return false
}

// IsCode returns true when this get network custom services service Id bad request response a status code equal to that given
func (o *GetNetworkCustomServicesServiceIDBadRequest) IsCode(code int) bool {
	return code == 400
}

// Code gets the status code for the get network custom services service Id bad request response
func (o *GetNetworkCustomServicesServiceIDBadRequest) Code() int {
	return 400
}

func (o *GetNetworkCustomServicesServiceIDBadRequest) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /network/custom-services/{serviceId}][%d] getNetworkCustomServicesServiceIdBadRequest %s", 400, payload)
}

func (o *GetNetworkCustomServicesServiceIDBadRequest) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /network/custom-services/{serviceId}][%d] getNetworkCustomServicesServiceIdBadRequest %s", 400, payload)
}

func (o *GetNetworkCustomServicesServiceIDBadRequest) GetPayload() *models.ProblemDetails {
	return o.Payload
}

func (o *GetNetworkCustomServicesServiceIDBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ProblemDetails)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetNetworkCustomServicesServiceIDUnauthorized creates a GetNetworkCustomServicesServiceIDUnauthorized with default headers values
func NewGetNetworkCustomServicesServiceIDUnauthorized() *GetNetworkCustomServicesServiceIDUnauthorized {
	return &GetNetworkCustomServicesServiceIDUnauthorized{}
}

/*
GetNetworkCustomServicesServiceIDUnauthorized describes a response with status code 401, with default header values.

Unauthorized
*/
type GetNetworkCustomServicesServiceIDUnauthorized struct {
	Payload *models.ProblemDetails
}

// IsSuccess returns true when this get network custom services service Id unauthorized response has a 2xx status code
func (o *GetNetworkCustomServicesServiceIDUnauthorized) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get network custom services service Id unauthorized response has a 3xx status code
func (o *GetNetworkCustomServicesServiceIDUnauthorized) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get network custom services service Id unauthorized response has a 4xx status code
func (o *GetNetworkCustomServicesServiceIDUnauthorized) IsClientError() bool {
	return true
}

// IsServerError returns true when this get network custom services service Id unauthorized response has a 5xx status code
func (o *GetNetworkCustomServicesServiceIDUnauthorized) IsServerError() bool {
	return false
}

// IsCode returns true when this get network custom services service Id unauthorized response a status code equal to that given
func (o *GetNetworkCustomServicesServiceIDUnauthorized) IsCode(code int) bool {
	return code == 401
}

// Code gets the status code for the get network custom services service Id unauthorized response
func (o *GetNetworkCustomServicesServiceIDUnauthorized) Code() int {
	return 401
}

func (o *GetNetworkCustomServicesServiceIDUnauthorized) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /network/custom-services/{serviceId}][%d] getNetworkCustomServicesServiceIdUnauthorized %s", 401, payload)
}

func (o *GetNetworkCustomServicesServiceIDUnauthorized) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /network/custom-services/{serviceId}][%d] getNetworkCustomServicesServiceIdUnauthorized %s", 401, payload)
}

func (o *GetNetworkCustomServicesServiceIDUnauthorized) GetPayload() *models.ProblemDetails {
	return o.Payload
}

func (o *GetNetworkCustomServicesServiceIDUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ProblemDetails)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetNetworkCustomServicesServiceIDForbidden creates a GetNetworkCustomServicesServiceIDForbidden with default headers values
func NewGetNetworkCustomServicesServiceIDForbidden() *GetNetworkCustomServicesServiceIDForbidden {
	return &GetNetworkCustomServicesServiceIDForbidden{}
}

/*
GetNetworkCustomServicesServiceIDForbidden describes a response with status code 403, with default header values.

Forbidden
*/
type GetNetworkCustomServicesServiceIDForbidden struct {
	Payload *models.ProblemDetails
}

// IsSuccess returns true when this get network custom services service Id forbidden response has a 2xx status code
func (o *GetNetworkCustomServicesServiceIDForbidden) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get network custom services service Id forbidden response has a 3xx status code
func (o *GetNetworkCustomServicesServiceIDForbidden) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get network custom services service Id forbidden response has a 4xx status code
func (o *GetNetworkCustomServicesServiceIDForbidden) IsClientError() bool {
	return true
}

// IsServerError returns true when this get network custom services service Id forbidden response has a 5xx status code
func (o *GetNetworkCustomServicesServiceIDForbidden) IsServerError() bool {
	return false
}

// IsCode returns true when this get network custom services service Id forbidden response a status code equal to that given
func (o *GetNetworkCustomServicesServiceIDForbidden) IsCode(code int) bool {
	return code == 403
}

// Code gets the status code for the get network custom services service Id forbidden response
func (o *GetNetworkCustomServicesServiceIDForbidden) Code() int {
	return 403
}

func (o *GetNetworkCustomServicesServiceIDForbidden) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /network/custom-services/{serviceId}][%d] getNetworkCustomServicesServiceIdForbidden %s", 403, payload)
}

func (o *GetNetworkCustomServicesServiceIDForbidden) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /network/custom-services/{serviceId}][%d] getNetworkCustomServicesServiceIdForbidden %s", 403, payload)
}

func (o *GetNetworkCustomServicesServiceIDForbidden) GetPayload() *models.ProblemDetails {
	return o.Payload
}

func (o *GetNetworkCustomServicesServiceIDForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ProblemDetails)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetNetworkCustomServicesServiceIDNotFound creates a GetNetworkCustomServicesServiceIDNotFound with default headers values
func NewGetNetworkCustomServicesServiceIDNotFound() *GetNetworkCustomServicesServiceIDNotFound {
	return &GetNetworkCustomServicesServiceIDNotFound{}
}

/*
GetNetworkCustomServicesServiceIDNotFound describes a response with status code 404, with default header values.

Not Found
*/
type GetNetworkCustomServicesServiceIDNotFound struct {
	Payload *models.ProblemDetails
}

// IsSuccess returns true when this get network custom services service Id not found response has a 2xx status code
func (o *GetNetworkCustomServicesServiceIDNotFound) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get network custom services service Id not found response has a 3xx status code
func (o *GetNetworkCustomServicesServiceIDNotFound) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get network custom services service Id not found response has a 4xx status code
func (o *GetNetworkCustomServicesServiceIDNotFound) IsClientError() bool {
	return true
}

// IsServerError returns true when this get network custom services service Id not found response has a 5xx status code
func (o *GetNetworkCustomServicesServiceIDNotFound) IsServerError() bool {
	return false
}

// IsCode returns true when this get network custom services service Id not found response a status code equal to that given
func (o *GetNetworkCustomServicesServiceIDNotFound) IsCode(code int) bool {
	return code == 404
}

// Code gets the status code for the get network custom services service Id not found response
func (o *GetNetworkCustomServicesServiceIDNotFound) Code() int {
	return 404
}

func (o *GetNetworkCustomServicesServiceIDNotFound) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /network/custom-services/{serviceId}][%d] getNetworkCustomServicesServiceIdNotFound %s", 404, payload)
}

func (o *GetNetworkCustomServicesServiceIDNotFound) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /network/custom-services/{serviceId}][%d] getNetworkCustomServicesServiceIdNotFound %s", 404, payload)
}

func (o *GetNetworkCustomServicesServiceIDNotFound) GetPayload() *models.ProblemDetails {
	return o.Payload
}

func (o *GetNetworkCustomServicesServiceIDNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ProblemDetails)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
