// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// DhcpConfigPath dhcp config path
//
// swagger:model DhcpConfigPath
type DhcpConfigPath struct {

	// dhcp config path Id
	DhcpConfigPathID int32 `json:"dhcpConfigPathId,omitempty"`

	// dhcp config path name
	DhcpConfigPathName string `json:"dhcpConfigPathName,omitempty"`
}

// Validate validates this dhcp config path
func (m *DhcpConfigPath) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this dhcp config path based on context it is used
func (m *DhcpConfigPath) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *DhcpConfigPath) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *DhcpConfigPath) UnmarshalBinary(b []byte) error {
	var res DhcpConfigPath
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
