// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// GetHealthCheckResponse get health check response
//
// swagger:model GetHealthCheckResponse
type GetHealthCheckResponse struct {

	// health check instance
	HealthCheckInstance *HealthCheckInstance `json:"healthCheckInstance,omitempty"`

	// messages
	Messages string `json:"messages,omitempty"`

	// success
	Success bool `json:"success,omitempty"`

	// timestamp
	// Format: date-time
	Timestamp strfmt.DateTime `json:"timestamp,omitempty"`
}

// Validate validates this get health check response
func (m *GetHealthCheckResponse) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateHealthCheckInstance(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateTimestamp(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *GetHealthCheckResponse) validateHealthCheckInstance(formats strfmt.Registry) error {
	if swag.IsZero(m.HealthCheckInstance) { // not required
		return nil
	}

	if m.HealthCheckInstance != nil {
		if err := m.HealthCheckInstance.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("healthCheckInstance")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("healthCheckInstance")
			}
			return err
		}
	}

	return nil
}

func (m *GetHealthCheckResponse) validateTimestamp(formats strfmt.Registry) error {
	if swag.IsZero(m.Timestamp) { // not required
		return nil
	}

	if err := validate.FormatOf("timestamp", "body", "date-time", m.Timestamp.String(), formats); err != nil {
		return err
	}

	return nil
}

// ContextValidate validate this get health check response based on the context it is used
func (m *GetHealthCheckResponse) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateHealthCheckInstance(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *GetHealthCheckResponse) contextValidateHealthCheckInstance(ctx context.Context, formats strfmt.Registry) error {

	if m.HealthCheckInstance != nil {

		if swag.IsZero(m.HealthCheckInstance) { // not required
			return nil
		}

		if err := m.HealthCheckInstance.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("healthCheckInstance")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("healthCheckInstance")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *GetHealthCheckResponse) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *GetHealthCheckResponse) UnmarshalBinary(b []byte) error {
	var res GetHealthCheckResponse
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
