// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"strconv"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// ListBillingAlarmDefinitionsResponse list billing alarm definitions response
//
// swagger:model ListBillingAlarmDefinitionsResponse
type ListBillingAlarmDefinitionsResponse struct {

	// billing alarm definition collection
	BillingAlarmDefinitionCollection []*BillingAlarmDefinition `json:"billingAlarmDefinitionCollection"`

	// messages
	Messages string `json:"messages,omitempty"`

	// success
	Success bool `json:"success,omitempty"`

	// timestamp
	// Format: date-time
	Timestamp strfmt.DateTime `json:"timestamp,omitempty"`
}

// Validate validates this list billing alarm definitions response
func (m *ListBillingAlarmDefinitionsResponse) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateBillingAlarmDefinitionCollection(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateTimestamp(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *ListBillingAlarmDefinitionsResponse) validateBillingAlarmDefinitionCollection(formats strfmt.Registry) error {
	if swag.IsZero(m.BillingAlarmDefinitionCollection) { // not required
		return nil
	}

	for i := 0; i < len(m.BillingAlarmDefinitionCollection); i++ {
		if swag.IsZero(m.BillingAlarmDefinitionCollection[i]) { // not required
			continue
		}

		if m.BillingAlarmDefinitionCollection[i] != nil {
			if err := m.BillingAlarmDefinitionCollection[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("billingAlarmDefinitionCollection" + "." + strconv.Itoa(i))
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("billingAlarmDefinitionCollection" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

func (m *ListBillingAlarmDefinitionsResponse) validateTimestamp(formats strfmt.Registry) error {
	if swag.IsZero(m.Timestamp) { // not required
		return nil
	}

	if err := validate.FormatOf("timestamp", "body", "date-time", m.Timestamp.String(), formats); err != nil {
		return err
	}

	return nil
}

// ContextValidate validate this list billing alarm definitions response based on the context it is used
func (m *ListBillingAlarmDefinitionsResponse) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateBillingAlarmDefinitionCollection(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *ListBillingAlarmDefinitionsResponse) contextValidateBillingAlarmDefinitionCollection(ctx context.Context, formats strfmt.Registry) error {

	for i := 0; i < len(m.BillingAlarmDefinitionCollection); i++ {

		if m.BillingAlarmDefinitionCollection[i] != nil {

			if swag.IsZero(m.BillingAlarmDefinitionCollection[i]) { // not required
				return nil
			}

			if err := m.BillingAlarmDefinitionCollection[i].ContextValidate(ctx, formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("billingAlarmDefinitionCollection" + "." + strconv.Itoa(i))
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("billingAlarmDefinitionCollection" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// MarshalBinary interface implementation
func (m *ListBillingAlarmDefinitionsResponse) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ListBillingAlarmDefinitionsResponse) UnmarshalBinary(b []byte) error {
	var res ListBillingAlarmDefinitionsResponse
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
