// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// Total total
//
// swagger:model Total
type Total struct {

	// last index
	LastIndex int64 `json:"lastIndex,omitempty"`

	// relation
	Relation string `json:"relation,omitempty"`

	// value
	Value int32 `json:"value,omitempty"`
}

// Validate validates this total
func (m *Total) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this total based on context it is used
func (m *Total) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *Total) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *Total) UnmarshalBinary(b []byte) error {
	var res Total
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
