// Code generated by go-swagger; DO NOT EDIT.

package virtual_machine

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetVcsVirtualMachinesParams creates a new GetVcsVirtualMachinesParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetVcsVirtualMachinesParams() *GetVcsVirtualMachinesParams {
	return &GetVcsVirtualMachinesParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetVcsVirtualMachinesParamsWithTimeout creates a new GetVcsVirtualMachinesParams object
// with the ability to set a timeout on a request.
func NewGetVcsVirtualMachinesParamsWithTimeout(timeout time.Duration) *GetVcsVirtualMachinesParams {
	return &GetVcsVirtualMachinesParams{
		timeout: timeout,
	}
}

// NewGetVcsVirtualMachinesParamsWithContext creates a new GetVcsVirtualMachinesParams object
// with the ability to set a context for a request.
func NewGetVcsVirtualMachinesParamsWithContext(ctx context.Context) *GetVcsVirtualMachinesParams {
	return &GetVcsVirtualMachinesParams{
		Context: ctx,
	}
}

// NewGetVcsVirtualMachinesParamsWithHTTPClient creates a new GetVcsVirtualMachinesParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetVcsVirtualMachinesParamsWithHTTPClient(client *http.Client) *GetVcsVirtualMachinesParams {
	return &GetVcsVirtualMachinesParams{
		HTTPClient: client,
	}
}

/*
GetVcsVirtualMachinesParams contains all the parameters to send to the API endpoint

	for the get vcs virtual machines operation.

	Typically these are written to a http.Request.
*/
type GetVcsVirtualMachinesParams struct {

	// DisplayName.
	DisplayName *string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get vcs virtual machines params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetVcsVirtualMachinesParams) WithDefaults() *GetVcsVirtualMachinesParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get vcs virtual machines params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetVcsVirtualMachinesParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get vcs virtual machines params
func (o *GetVcsVirtualMachinesParams) WithTimeout(timeout time.Duration) *GetVcsVirtualMachinesParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get vcs virtual machines params
func (o *GetVcsVirtualMachinesParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get vcs virtual machines params
func (o *GetVcsVirtualMachinesParams) WithContext(ctx context.Context) *GetVcsVirtualMachinesParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get vcs virtual machines params
func (o *GetVcsVirtualMachinesParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get vcs virtual machines params
func (o *GetVcsVirtualMachinesParams) WithHTTPClient(client *http.Client) *GetVcsVirtualMachinesParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get vcs virtual machines params
func (o *GetVcsVirtualMachinesParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithDisplayName adds the displayName to the get vcs virtual machines params
func (o *GetVcsVirtualMachinesParams) WithDisplayName(displayName *string) *GetVcsVirtualMachinesParams {
	o.SetDisplayName(displayName)
	return o
}

// SetDisplayName adds the displayName to the get vcs virtual machines params
func (o *GetVcsVirtualMachinesParams) SetDisplayName(displayName *string) {
	o.DisplayName = displayName
}

// WriteToRequest writes these params to a swagger request
func (o *GetVcsVirtualMachinesParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.DisplayName != nil {

		// query param displayName
		var qrDisplayName string

		if o.DisplayName != nil {
			qrDisplayName = *o.DisplayName
		}
		qDisplayName := qrDisplayName
		if qDisplayName != "" {

			if err := r.SetQueryParam("displayName", qDisplayName); err != nil {
				return err
			}
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
