/*
Platforma OChK - Proxy API

Platforma OChK - Proxy API

API version: v1
Contact: pomoc@ochk.pl
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"bytes"
	"context"
	"io"
	"net/http"
	"net/url"
	"strings"
)

// OvnLbAPIService OvnLbAPI service
type OvnLbAPIService service

type ApiProjectsProjectIdNlbLoadBalancersOvnGetRequest struct {
	ctx        context.Context
	ApiService *OvnLbAPIService
	projectId  string
	name       *string
}

func (r ApiProjectsProjectIdNlbLoadBalancersOvnGetRequest) Name(name string) ApiProjectsProjectIdNlbLoadBalancersOvnGetRequest {
	r.name = &name
	return r
}

func (r ApiProjectsProjectIdNlbLoadBalancersOvnGetRequest) Execute() (*OvnLoadBalancerListApiResponse, *http.Response, error) {
	return r.ApiService.ProjectsProjectIdNlbLoadBalancersOvnGetExecute(r)
}

/*
ProjectsProjectIdNlbLoadBalancersOvnGet List ovn network load balancers

List ovn network load balancers

	@param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
	@param projectId
	@return ApiProjectsProjectIdNlbLoadBalancersOvnGetRequest
*/
func (a *OvnLbAPIService) ProjectsProjectIdNlbLoadBalancersOvnGet(ctx context.Context, projectId string) ApiProjectsProjectIdNlbLoadBalancersOvnGetRequest {
	return ApiProjectsProjectIdNlbLoadBalancersOvnGetRequest{
		ApiService: a,
		ctx:        ctx,
		projectId:  projectId,
	}
}

// Execute executes the request
//
//	@return OvnLoadBalancerListApiResponse
func (a *OvnLbAPIService) ProjectsProjectIdNlbLoadBalancersOvnGetExecute(r ApiProjectsProjectIdNlbLoadBalancersOvnGetRequest) (*OvnLoadBalancerListApiResponse, *http.Response, error) {
	var (
		localVarHTTPMethod  = http.MethodGet
		localVarPostBody    interface{}
		formFiles           []formFile
		localVarReturnValue *OvnLoadBalancerListApiResponse
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "OvnLbAPIService.ProjectsProjectIdNlbLoadBalancersOvnGet")
	if err != nil {
		return localVarReturnValue, nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/projects/{projectId}/nlb/load-balancers/ovn"
	localVarPath = strings.Replace(localVarPath, "{"+"projectId"+"}", url.PathEscape(parameterValueToString(r.projectId, "projectId")), -1)

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}

	if r.name != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "name", r.name, "")
	}
	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/json"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		if localVarHTTPResponse.StatusCode == 401 {
			var v ProblemDetails
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
			newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
			newErr.model = v
			return localVarReturnValue, localVarHTTPResponse, newErr
		}
		if localVarHTTPResponse.StatusCode == 403 {
			var v ProblemDetails
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
			newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
			newErr.model = v
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	err = a.client.decode(&localVarReturnValue, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
	if err != nil {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: err.Error(),
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	return localVarReturnValue, localVarHTTPResponse, nil
}

type ApiProjectsProjectIdNlbLoadBalancersOvnOvnLoadBalancerIdDeleteRequest struct {
	ctx               context.Context
	ApiService        *OvnLbAPIService
	projectId         string
	ovnLoadBalancerId string
	force             *bool
}

func (r ApiProjectsProjectIdNlbLoadBalancersOvnOvnLoadBalancerIdDeleteRequest) Force(force bool) ApiProjectsProjectIdNlbLoadBalancersOvnOvnLoadBalancerIdDeleteRequest {
	r.force = &force
	return r
}

func (r ApiProjectsProjectIdNlbLoadBalancersOvnOvnLoadBalancerIdDeleteRequest) Execute() (*StringApiResponse, *http.Response, error) {
	return r.ApiService.ProjectsProjectIdNlbLoadBalancersOvnOvnLoadBalancerIdDeleteExecute(r)
}

/*
ProjectsProjectIdNlbLoadBalancersOvnOvnLoadBalancerIdDelete Delete load balancer

Delete load balancer

	@param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
	@param projectId
	@param ovnLoadBalancerId
	@return ApiProjectsProjectIdNlbLoadBalancersOvnOvnLoadBalancerIdDeleteRequest
*/
func (a *OvnLbAPIService) ProjectsProjectIdNlbLoadBalancersOvnOvnLoadBalancerIdDelete(ctx context.Context, projectId string, ovnLoadBalancerId string) ApiProjectsProjectIdNlbLoadBalancersOvnOvnLoadBalancerIdDeleteRequest {
	return ApiProjectsProjectIdNlbLoadBalancersOvnOvnLoadBalancerIdDeleteRequest{
		ApiService:        a,
		ctx:               ctx,
		projectId:         projectId,
		ovnLoadBalancerId: ovnLoadBalancerId,
	}
}

// Execute executes the request
//
//	@return StringApiResponse
func (a *OvnLbAPIService) ProjectsProjectIdNlbLoadBalancersOvnOvnLoadBalancerIdDeleteExecute(r ApiProjectsProjectIdNlbLoadBalancersOvnOvnLoadBalancerIdDeleteRequest) (*StringApiResponse, *http.Response, error) {
	var (
		localVarHTTPMethod  = http.MethodDelete
		localVarPostBody    interface{}
		formFiles           []formFile
		localVarReturnValue *StringApiResponse
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "OvnLbAPIService.ProjectsProjectIdNlbLoadBalancersOvnOvnLoadBalancerIdDelete")
	if err != nil {
		return localVarReturnValue, nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/projects/{projectId}/nlb/load-balancers/ovn/{ovnLoadBalancerId}"
	localVarPath = strings.Replace(localVarPath, "{"+"projectId"+"}", url.PathEscape(parameterValueToString(r.projectId, "projectId")), -1)
	localVarPath = strings.Replace(localVarPath, "{"+"ovnLoadBalancerId"+"}", url.PathEscape(parameterValueToString(r.ovnLoadBalancerId, "ovnLoadBalancerId")), -1)

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}

	if r.force != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "force", r.force, "")
	} else {
		var defaultValue bool = false
		r.force = &defaultValue
	}
	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/json"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		if localVarHTTPResponse.StatusCode == 401 {
			var v ProblemDetails
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
			newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
			newErr.model = v
			return localVarReturnValue, localVarHTTPResponse, newErr
		}
		if localVarHTTPResponse.StatusCode == 403 {
			var v ProblemDetails
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
			newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
			newErr.model = v
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	err = a.client.decode(&localVarReturnValue, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
	if err != nil {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: err.Error(),
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	return localVarReturnValue, localVarHTTPResponse, nil
}

type ApiProjectsProjectIdNlbLoadBalancersOvnOvnLoadBalancerIdGetRequest struct {
	ctx               context.Context
	ApiService        *OvnLbAPIService
	projectId         string
	ovnLoadBalancerId string
}

func (r ApiProjectsProjectIdNlbLoadBalancersOvnOvnLoadBalancerIdGetRequest) Execute() (*OvnLoadBalancerApiResponse, *http.Response, error) {
	return r.ApiService.ProjectsProjectIdNlbLoadBalancersOvnOvnLoadBalancerIdGetExecute(r)
}

/*
ProjectsProjectIdNlbLoadBalancersOvnOvnLoadBalancerIdGet Get ovn network load balancer

Get ovn network load balancer

	@param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
	@param projectId
	@param ovnLoadBalancerId
	@return ApiProjectsProjectIdNlbLoadBalancersOvnOvnLoadBalancerIdGetRequest
*/
func (a *OvnLbAPIService) ProjectsProjectIdNlbLoadBalancersOvnOvnLoadBalancerIdGet(ctx context.Context, projectId string, ovnLoadBalancerId string) ApiProjectsProjectIdNlbLoadBalancersOvnOvnLoadBalancerIdGetRequest {
	return ApiProjectsProjectIdNlbLoadBalancersOvnOvnLoadBalancerIdGetRequest{
		ApiService:        a,
		ctx:               ctx,
		projectId:         projectId,
		ovnLoadBalancerId: ovnLoadBalancerId,
	}
}

// Execute executes the request
//
//	@return OvnLoadBalancerApiResponse
func (a *OvnLbAPIService) ProjectsProjectIdNlbLoadBalancersOvnOvnLoadBalancerIdGetExecute(r ApiProjectsProjectIdNlbLoadBalancersOvnOvnLoadBalancerIdGetRequest) (*OvnLoadBalancerApiResponse, *http.Response, error) {
	var (
		localVarHTTPMethod  = http.MethodGet
		localVarPostBody    interface{}
		formFiles           []formFile
		localVarReturnValue *OvnLoadBalancerApiResponse
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "OvnLbAPIService.ProjectsProjectIdNlbLoadBalancersOvnOvnLoadBalancerIdGet")
	if err != nil {
		return localVarReturnValue, nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/projects/{projectId}/nlb/load-balancers/ovn/{ovnLoadBalancerId}"
	localVarPath = strings.Replace(localVarPath, "{"+"projectId"+"}", url.PathEscape(parameterValueToString(r.projectId, "projectId")), -1)
	localVarPath = strings.Replace(localVarPath, "{"+"ovnLoadBalancerId"+"}", url.PathEscape(parameterValueToString(r.ovnLoadBalancerId, "ovnLoadBalancerId")), -1)

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}

	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/json"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		if localVarHTTPResponse.StatusCode == 401 {
			var v ProblemDetails
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
			newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
			newErr.model = v
			return localVarReturnValue, localVarHTTPResponse, newErr
		}
		if localVarHTTPResponse.StatusCode == 403 {
			var v ProblemDetails
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
			newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
			newErr.model = v
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	err = a.client.decode(&localVarReturnValue, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
	if err != nil {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: err.Error(),
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	return localVarReturnValue, localVarHTTPResponse, nil
}

type ApiProjectsProjectIdNlbLoadBalancersOvnOvnLoadBalancerIdPutRequest struct {
	ctx               context.Context
	ApiService        *OvnLbAPIService
	projectId         string
	ovnLoadBalancerId string
	ovnLoadBalancer   *OvnLoadBalancer
}

func (r ApiProjectsProjectIdNlbLoadBalancersOvnOvnLoadBalancerIdPutRequest) OvnLoadBalancer(ovnLoadBalancer OvnLoadBalancer) ApiProjectsProjectIdNlbLoadBalancersOvnOvnLoadBalancerIdPutRequest {
	r.ovnLoadBalancer = &ovnLoadBalancer
	return r
}

func (r ApiProjectsProjectIdNlbLoadBalancersOvnOvnLoadBalancerIdPutRequest) Execute() (*OvnLoadBalancerApiResponse, *http.Response, error) {
	return r.ApiService.ProjectsProjectIdNlbLoadBalancersOvnOvnLoadBalancerIdPutExecute(r)
}

/*
ProjectsProjectIdNlbLoadBalancersOvnOvnLoadBalancerIdPut Update load balancer

Update load balancer

	@param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
	@param projectId
	@param ovnLoadBalancerId
	@return ApiProjectsProjectIdNlbLoadBalancersOvnOvnLoadBalancerIdPutRequest
*/
func (a *OvnLbAPIService) ProjectsProjectIdNlbLoadBalancersOvnOvnLoadBalancerIdPut(ctx context.Context, projectId string, ovnLoadBalancerId string) ApiProjectsProjectIdNlbLoadBalancersOvnOvnLoadBalancerIdPutRequest {
	return ApiProjectsProjectIdNlbLoadBalancersOvnOvnLoadBalancerIdPutRequest{
		ApiService:        a,
		ctx:               ctx,
		projectId:         projectId,
		ovnLoadBalancerId: ovnLoadBalancerId,
	}
}

// Execute executes the request
//
//	@return OvnLoadBalancerApiResponse
func (a *OvnLbAPIService) ProjectsProjectIdNlbLoadBalancersOvnOvnLoadBalancerIdPutExecute(r ApiProjectsProjectIdNlbLoadBalancersOvnOvnLoadBalancerIdPutRequest) (*OvnLoadBalancerApiResponse, *http.Response, error) {
	var (
		localVarHTTPMethod  = http.MethodPut
		localVarPostBody    interface{}
		formFiles           []formFile
		localVarReturnValue *OvnLoadBalancerApiResponse
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "OvnLbAPIService.ProjectsProjectIdNlbLoadBalancersOvnOvnLoadBalancerIdPut")
	if err != nil {
		return localVarReturnValue, nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/projects/{projectId}/nlb/load-balancers/ovn/{ovnLoadBalancerId}"
	localVarPath = strings.Replace(localVarPath, "{"+"projectId"+"}", url.PathEscape(parameterValueToString(r.projectId, "projectId")), -1)
	localVarPath = strings.Replace(localVarPath, "{"+"ovnLoadBalancerId"+"}", url.PathEscape(parameterValueToString(r.ovnLoadBalancerId, "ovnLoadBalancerId")), -1)

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}

	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{"application/json", "text/json", "application/*+json"}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/json"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	// body params
	localVarPostBody = r.ovnLoadBalancer
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		if localVarHTTPResponse.StatusCode == 401 {
			var v ProblemDetails
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
			newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
			newErr.model = v
			return localVarReturnValue, localVarHTTPResponse, newErr
		}
		if localVarHTTPResponse.StatusCode == 403 {
			var v ProblemDetails
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
			newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
			newErr.model = v
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	err = a.client.decode(&localVarReturnValue, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
	if err != nil {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: err.Error(),
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	return localVarReturnValue, localVarHTTPResponse, nil
}

type ApiProjectsProjectIdNlbLoadBalancersOvnPutRequest struct {
	ctx             context.Context
	ApiService      *OvnLbAPIService
	projectId       string
	ovnLoadBalancer *OvnLoadBalancer
}

func (r ApiProjectsProjectIdNlbLoadBalancersOvnPutRequest) OvnLoadBalancer(ovnLoadBalancer OvnLoadBalancer) ApiProjectsProjectIdNlbLoadBalancersOvnPutRequest {
	r.ovnLoadBalancer = &ovnLoadBalancer
	return r
}

func (r ApiProjectsProjectIdNlbLoadBalancersOvnPutRequest) Execute() (*OvnLoadBalancerApiResponse, *http.Response, error) {
	return r.ApiService.ProjectsProjectIdNlbLoadBalancersOvnPutExecute(r)
}

/*
ProjectsProjectIdNlbLoadBalancersOvnPut Create network load balancer

Create network load balancer

	@param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
	@param projectId
	@return ApiProjectsProjectIdNlbLoadBalancersOvnPutRequest
*/
func (a *OvnLbAPIService) ProjectsProjectIdNlbLoadBalancersOvnPut(ctx context.Context, projectId string) ApiProjectsProjectIdNlbLoadBalancersOvnPutRequest {
	return ApiProjectsProjectIdNlbLoadBalancersOvnPutRequest{
		ApiService: a,
		ctx:        ctx,
		projectId:  projectId,
	}
}

// Execute executes the request
//
//	@return OvnLoadBalancerApiResponse
func (a *OvnLbAPIService) ProjectsProjectIdNlbLoadBalancersOvnPutExecute(r ApiProjectsProjectIdNlbLoadBalancersOvnPutRequest) (*OvnLoadBalancerApiResponse, *http.Response, error) {
	var (
		localVarHTTPMethod  = http.MethodPut
		localVarPostBody    interface{}
		formFiles           []formFile
		localVarReturnValue *OvnLoadBalancerApiResponse
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "OvnLbAPIService.ProjectsProjectIdNlbLoadBalancersOvnPut")
	if err != nil {
		return localVarReturnValue, nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/projects/{projectId}/nlb/load-balancers/ovn"
	localVarPath = strings.Replace(localVarPath, "{"+"projectId"+"}", url.PathEscape(parameterValueToString(r.projectId, "projectId")), -1)

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}

	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{"application/json", "text/json", "application/*+json"}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/json"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	// body params
	localVarPostBody = r.ovnLoadBalancer
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		if localVarHTTPResponse.StatusCode == 401 {
			var v ProblemDetails
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
			newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
			newErr.model = v
			return localVarReturnValue, localVarHTTPResponse, newErr
		}
		if localVarHTTPResponse.StatusCode == 403 {
			var v ProblemDetails
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
			newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
			newErr.model = v
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	err = a.client.decode(&localVarReturnValue, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
	if err != nil {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: err.Error(),
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	return localVarReturnValue, localVarHTTPResponse, nil
}
