/*
Platforma OChK - Proxy API

Platforma OChK - Proxy API

API version: v1
Contact: pomoc@ochk.pl
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"bytes"
	"context"
	"io"
	"net/http"
	"net/url"
	"strings"
)

// LogAPIService LogAPI service
type LogAPIService service

type ApiLogCategoriesLogCategoryIdGeneratePostRequest struct {
	ctx           context.Context
	ApiService    *LogAPIService
	logCategoryId int32
	dataSize      *int32
	lastIndex     *int64
	queryFilter   *QueryFilter
}

func (r ApiLogCategoriesLogCategoryIdGeneratePostRequest) DataSize(dataSize int32) ApiLogCategoriesLogCategoryIdGeneratePostRequest {
	r.dataSize = &dataSize
	return r
}

func (r ApiLogCategoriesLogCategoryIdGeneratePostRequest) LastIndex(lastIndex int64) ApiLogCategoriesLogCategoryIdGeneratePostRequest {
	r.lastIndex = &lastIndex
	return r
}

func (r ApiLogCategoriesLogCategoryIdGeneratePostRequest) QueryFilter(queryFilter QueryFilter) ApiLogCategoriesLogCategoryIdGeneratePostRequest {
	r.queryFilter = &queryFilter
	return r
}

func (r ApiLogCategoriesLogCategoryIdGeneratePostRequest) Execute() (*GetLogsResponse, *http.Response, error) {
	return r.ApiService.LogCategoriesLogCategoryIdGeneratePostExecute(r)
}

/*
LogCategoriesLogCategoryIdGeneratePost Get logs

Get logs

	@param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
	@param logCategoryId
	@return ApiLogCategoriesLogCategoryIdGeneratePostRequest
*/
func (a *LogAPIService) LogCategoriesLogCategoryIdGeneratePost(ctx context.Context, logCategoryId int32) ApiLogCategoriesLogCategoryIdGeneratePostRequest {
	return ApiLogCategoriesLogCategoryIdGeneratePostRequest{
		ApiService:    a,
		ctx:           ctx,
		logCategoryId: logCategoryId,
	}
}

// Execute executes the request
//
//	@return GetLogsResponse
func (a *LogAPIService) LogCategoriesLogCategoryIdGeneratePostExecute(r ApiLogCategoriesLogCategoryIdGeneratePostRequest) (*GetLogsResponse, *http.Response, error) {
	var (
		localVarHTTPMethod  = http.MethodPost
		localVarPostBody    interface{}
		formFiles           []formFile
		localVarReturnValue *GetLogsResponse
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "LogAPIService.LogCategoriesLogCategoryIdGeneratePost")
	if err != nil {
		return localVarReturnValue, nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/log/categories/{logCategoryId}/generate"
	localVarPath = strings.Replace(localVarPath, "{"+"logCategoryId"+"}", url.PathEscape(parameterValueToString(r.logCategoryId, "logCategoryId")), -1)

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}

	if r.dataSize != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "dataSize", r.dataSize, "")
	}
	if r.lastIndex != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "lastIndex", r.lastIndex, "")
	}
	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{"application/json", "text/json", "application/*+json"}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/json"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	// body params
	localVarPostBody = r.queryFilter
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		if localVarHTTPResponse.StatusCode == 400 {
			var v ProblemDetails
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
			newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
			newErr.model = v
			return localVarReturnValue, localVarHTTPResponse, newErr
		}
		if localVarHTTPResponse.StatusCode == 401 {
			var v ProblemDetails
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
			newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
			newErr.model = v
			return localVarReturnValue, localVarHTTPResponse, newErr
		}
		if localVarHTTPResponse.StatusCode == 403 {
			var v ProblemDetails
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
			newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
			newErr.model = v
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	err = a.client.decode(&localVarReturnValue, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
	if err != nil {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: err.Error(),
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	return localVarReturnValue, localVarHTTPResponse, nil
}

type ApiLogCategoriesLogCategoryIdGeneratebydslPostRequest struct {
	ctx           context.Context
	ApiService    *LogAPIService
	logCategoryId int32
	dataSize      *int32
	body          *string
}

func (r ApiLogCategoriesLogCategoryIdGeneratebydslPostRequest) DataSize(dataSize int32) ApiLogCategoriesLogCategoryIdGeneratebydslPostRequest {
	r.dataSize = &dataSize
	return r
}

func (r ApiLogCategoriesLogCategoryIdGeneratebydslPostRequest) Body(body string) ApiLogCategoriesLogCategoryIdGeneratebydslPostRequest {
	r.body = &body
	return r
}

func (r ApiLogCategoriesLogCategoryIdGeneratebydslPostRequest) Execute() (*GetLogsResponse, *http.Response, error) {
	return r.ApiService.LogCategoriesLogCategoryIdGeneratebydslPostExecute(r)
}

/*
LogCategoriesLogCategoryIdGeneratebydslPost Get logs by DSL query

Get logs by DSL query

	@param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
	@param logCategoryId
	@return ApiLogCategoriesLogCategoryIdGeneratebydslPostRequest
*/
func (a *LogAPIService) LogCategoriesLogCategoryIdGeneratebydslPost(ctx context.Context, logCategoryId int32) ApiLogCategoriesLogCategoryIdGeneratebydslPostRequest {
	return ApiLogCategoriesLogCategoryIdGeneratebydslPostRequest{
		ApiService:    a,
		ctx:           ctx,
		logCategoryId: logCategoryId,
	}
}

// Execute executes the request
//
//	@return GetLogsResponse
func (a *LogAPIService) LogCategoriesLogCategoryIdGeneratebydslPostExecute(r ApiLogCategoriesLogCategoryIdGeneratebydslPostRequest) (*GetLogsResponse, *http.Response, error) {
	var (
		localVarHTTPMethod  = http.MethodPost
		localVarPostBody    interface{}
		formFiles           []formFile
		localVarReturnValue *GetLogsResponse
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "LogAPIService.LogCategoriesLogCategoryIdGeneratebydslPost")
	if err != nil {
		return localVarReturnValue, nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/log/categories/{logCategoryId}/generatebydsl"
	localVarPath = strings.Replace(localVarPath, "{"+"logCategoryId"+"}", url.PathEscape(parameterValueToString(r.logCategoryId, "logCategoryId")), -1)

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}

	if r.dataSize != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "dataSize", r.dataSize, "")
	}
	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{"application/json", "text/json", "application/*+json"}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/json"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	// body params
	localVarPostBody = r.body
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		if localVarHTTPResponse.StatusCode == 400 {
			var v ProblemDetails
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
			newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
			newErr.model = v
			return localVarReturnValue, localVarHTTPResponse, newErr
		}
		if localVarHTTPResponse.StatusCode == 401 {
			var v ProblemDetails
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
			newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
			newErr.model = v
			return localVarReturnValue, localVarHTTPResponse, newErr
		}
		if localVarHTTPResponse.StatusCode == 403 {
			var v ProblemDetails
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
			newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
			newErr.model = v
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	err = a.client.decode(&localVarReturnValue, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
	if err != nil {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: err.Error(),
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	return localVarReturnValue, localVarHTTPResponse, nil
}
