/*
Platforma OChK - Proxy API

Platforma OChK - Proxy API

API version: v1
Contact: pomoc@ochk.pl
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the WorkersStatus type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &WorkersStatus{}

// WorkersStatus struct for WorkersStatus
type WorkersStatus struct {
	AvailableReplicas NullableInt32 `json:"availableReplicas,omitempty"`
	DesiredReplicas   NullableInt32 `json:"desiredReplicas,omitempty"`
	ReadyReplicas     NullableInt32 `json:"readyReplicas,omitempty"`
	Replicas          NullableInt32 `json:"replicas,omitempty"`
	UpToDateReplicas  NullableInt32 `json:"upToDateReplicas,omitempty"`
	StatusOk          NullableBool  `json:"statusOk,omitempty"`
}

// NewWorkersStatus instantiates a new WorkersStatus object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewWorkersStatus() *WorkersStatus {
	this := WorkersStatus{}
	return &this
}

// NewWorkersStatusWithDefaults instantiates a new WorkersStatus object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewWorkersStatusWithDefaults() *WorkersStatus {
	this := WorkersStatus{}
	return &this
}

// GetAvailableReplicas returns the AvailableReplicas field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *WorkersStatus) GetAvailableReplicas() int32 {
	if o == nil || IsNil(o.AvailableReplicas.Get()) {
		var ret int32
		return ret
	}
	return *o.AvailableReplicas.Get()
}

// GetAvailableReplicasOk returns a tuple with the AvailableReplicas field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *WorkersStatus) GetAvailableReplicasOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return o.AvailableReplicas.Get(), o.AvailableReplicas.IsSet()
}

// HasAvailableReplicas returns a boolean if a field has been set.
func (o *WorkersStatus) HasAvailableReplicas() bool {
	if o != nil && o.AvailableReplicas.IsSet() {
		return true
	}

	return false
}

// SetAvailableReplicas gets a reference to the given NullableInt32 and assigns it to the AvailableReplicas field.
func (o *WorkersStatus) SetAvailableReplicas(v int32) {
	o.AvailableReplicas.Set(&v)
}

// SetAvailableReplicasNil sets the value for AvailableReplicas to be an explicit nil
func (o *WorkersStatus) SetAvailableReplicasNil() {
	o.AvailableReplicas.Set(nil)
}

// UnsetAvailableReplicas ensures that no value is present for AvailableReplicas, not even an explicit nil
func (o *WorkersStatus) UnsetAvailableReplicas() {
	o.AvailableReplicas.Unset()
}

// GetDesiredReplicas returns the DesiredReplicas field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *WorkersStatus) GetDesiredReplicas() int32 {
	if o == nil || IsNil(o.DesiredReplicas.Get()) {
		var ret int32
		return ret
	}
	return *o.DesiredReplicas.Get()
}

// GetDesiredReplicasOk returns a tuple with the DesiredReplicas field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *WorkersStatus) GetDesiredReplicasOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return o.DesiredReplicas.Get(), o.DesiredReplicas.IsSet()
}

// HasDesiredReplicas returns a boolean if a field has been set.
func (o *WorkersStatus) HasDesiredReplicas() bool {
	if o != nil && o.DesiredReplicas.IsSet() {
		return true
	}

	return false
}

// SetDesiredReplicas gets a reference to the given NullableInt32 and assigns it to the DesiredReplicas field.
func (o *WorkersStatus) SetDesiredReplicas(v int32) {
	o.DesiredReplicas.Set(&v)
}

// SetDesiredReplicasNil sets the value for DesiredReplicas to be an explicit nil
func (o *WorkersStatus) SetDesiredReplicasNil() {
	o.DesiredReplicas.Set(nil)
}

// UnsetDesiredReplicas ensures that no value is present for DesiredReplicas, not even an explicit nil
func (o *WorkersStatus) UnsetDesiredReplicas() {
	o.DesiredReplicas.Unset()
}

// GetReadyReplicas returns the ReadyReplicas field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *WorkersStatus) GetReadyReplicas() int32 {
	if o == nil || IsNil(o.ReadyReplicas.Get()) {
		var ret int32
		return ret
	}
	return *o.ReadyReplicas.Get()
}

// GetReadyReplicasOk returns a tuple with the ReadyReplicas field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *WorkersStatus) GetReadyReplicasOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return o.ReadyReplicas.Get(), o.ReadyReplicas.IsSet()
}

// HasReadyReplicas returns a boolean if a field has been set.
func (o *WorkersStatus) HasReadyReplicas() bool {
	if o != nil && o.ReadyReplicas.IsSet() {
		return true
	}

	return false
}

// SetReadyReplicas gets a reference to the given NullableInt32 and assigns it to the ReadyReplicas field.
func (o *WorkersStatus) SetReadyReplicas(v int32) {
	o.ReadyReplicas.Set(&v)
}

// SetReadyReplicasNil sets the value for ReadyReplicas to be an explicit nil
func (o *WorkersStatus) SetReadyReplicasNil() {
	o.ReadyReplicas.Set(nil)
}

// UnsetReadyReplicas ensures that no value is present for ReadyReplicas, not even an explicit nil
func (o *WorkersStatus) UnsetReadyReplicas() {
	o.ReadyReplicas.Unset()
}

// GetReplicas returns the Replicas field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *WorkersStatus) GetReplicas() int32 {
	if o == nil || IsNil(o.Replicas.Get()) {
		var ret int32
		return ret
	}
	return *o.Replicas.Get()
}

// GetReplicasOk returns a tuple with the Replicas field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *WorkersStatus) GetReplicasOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return o.Replicas.Get(), o.Replicas.IsSet()
}

// HasReplicas returns a boolean if a field has been set.
func (o *WorkersStatus) HasReplicas() bool {
	if o != nil && o.Replicas.IsSet() {
		return true
	}

	return false
}

// SetReplicas gets a reference to the given NullableInt32 and assigns it to the Replicas field.
func (o *WorkersStatus) SetReplicas(v int32) {
	o.Replicas.Set(&v)
}

// SetReplicasNil sets the value for Replicas to be an explicit nil
func (o *WorkersStatus) SetReplicasNil() {
	o.Replicas.Set(nil)
}

// UnsetReplicas ensures that no value is present for Replicas, not even an explicit nil
func (o *WorkersStatus) UnsetReplicas() {
	o.Replicas.Unset()
}

// GetUpToDateReplicas returns the UpToDateReplicas field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *WorkersStatus) GetUpToDateReplicas() int32 {
	if o == nil || IsNil(o.UpToDateReplicas.Get()) {
		var ret int32
		return ret
	}
	return *o.UpToDateReplicas.Get()
}

// GetUpToDateReplicasOk returns a tuple with the UpToDateReplicas field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *WorkersStatus) GetUpToDateReplicasOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return o.UpToDateReplicas.Get(), o.UpToDateReplicas.IsSet()
}

// HasUpToDateReplicas returns a boolean if a field has been set.
func (o *WorkersStatus) HasUpToDateReplicas() bool {
	if o != nil && o.UpToDateReplicas.IsSet() {
		return true
	}

	return false
}

// SetUpToDateReplicas gets a reference to the given NullableInt32 and assigns it to the UpToDateReplicas field.
func (o *WorkersStatus) SetUpToDateReplicas(v int32) {
	o.UpToDateReplicas.Set(&v)
}

// SetUpToDateReplicasNil sets the value for UpToDateReplicas to be an explicit nil
func (o *WorkersStatus) SetUpToDateReplicasNil() {
	o.UpToDateReplicas.Set(nil)
}

// UnsetUpToDateReplicas ensures that no value is present for UpToDateReplicas, not even an explicit nil
func (o *WorkersStatus) UnsetUpToDateReplicas() {
	o.UpToDateReplicas.Unset()
}

// GetStatusOk returns the StatusOk field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *WorkersStatus) GetStatusOk() bool {
	if o == nil || IsNil(o.StatusOk.Get()) {
		var ret bool
		return ret
	}
	return *o.StatusOk.Get()
}

// GetStatusOkOk returns a tuple with the StatusOk field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *WorkersStatus) GetStatusOkOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return o.StatusOk.Get(), o.StatusOk.IsSet()
}

// HasStatusOk returns a boolean if a field has been set.
func (o *WorkersStatus) HasStatusOk() bool {
	if o != nil && o.StatusOk.IsSet() {
		return true
	}

	return false
}

// SetStatusOk gets a reference to the given NullableBool and assigns it to the StatusOk field.
func (o *WorkersStatus) SetStatusOk(v bool) {
	o.StatusOk.Set(&v)
}

// SetStatusOkNil sets the value for StatusOk to be an explicit nil
func (o *WorkersStatus) SetStatusOkNil() {
	o.StatusOk.Set(nil)
}

// UnsetStatusOk ensures that no value is present for StatusOk, not even an explicit nil
func (o *WorkersStatus) UnsetStatusOk() {
	o.StatusOk.Unset()
}

func (o WorkersStatus) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if o.AvailableReplicas.IsSet() {
		toSerialize["availableReplicas"] = o.AvailableReplicas.Get()
	}
	if o.DesiredReplicas.IsSet() {
		toSerialize["desiredReplicas"] = o.DesiredReplicas.Get()
	}
	if o.ReadyReplicas.IsSet() {
		toSerialize["readyReplicas"] = o.ReadyReplicas.Get()
	}
	if o.Replicas.IsSet() {
		toSerialize["replicas"] = o.Replicas.Get()
	}
	if o.UpToDateReplicas.IsSet() {
		toSerialize["upToDateReplicas"] = o.UpToDateReplicas.Get()
	}
	if o.StatusOk.IsSet() {
		toSerialize["statusOk"] = o.StatusOk.Get()
	}
	return toSerialize, nil
}

type NullableWorkersStatus struct {
	value *WorkersStatus
	isSet bool
}

func (v NullableWorkersStatus) Get() *WorkersStatus {
	return v.value
}

func (v *NullableWorkersStatus) Set(val *WorkersStatus) {
	v.value = val
	v.isSet = true
}

func (v NullableWorkersStatus) IsSet() bool {
	return v.isSet
}

func (v *NullableWorkersStatus) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableWorkersStatus(val *WorkersStatus) *NullableWorkersStatus {
	return &NullableWorkersStatus{value: val, isSet: true}
}

func (v NullableWorkersStatus) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableWorkersStatus) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
