/*
Platforma OChK - Proxy API

Platforma OChK - Proxy API

API version: v1
Contact: pomoc@ochk.pl
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"time"
)

// checks if the CreateClusterResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CreateClusterResponse{}

// CreateClusterResponse struct for CreateClusterResponse
type CreateClusterResponse struct {
	ErrorCode       NullableInt32    `json:"errorCode,omitempty"`
	Messages        NullableString   `json:"messages,omitempty"`
	Success         *bool            `json:"success,omitempty"`
	Timestamp       *time.Time       `json:"timestamp,omitempty"`
	ClusterInstance *ClusterInstance `json:"clusterInstance,omitempty"`
	RequestInstance *RequestInstance `json:"requestInstance,omitempty"`
}

// NewCreateClusterResponse instantiates a new CreateClusterResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateClusterResponse() *CreateClusterResponse {
	this := CreateClusterResponse{}
	return &this
}

// NewCreateClusterResponseWithDefaults instantiates a new CreateClusterResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateClusterResponseWithDefaults() *CreateClusterResponse {
	this := CreateClusterResponse{}
	return &this
}

// GetErrorCode returns the ErrorCode field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *CreateClusterResponse) GetErrorCode() int32 {
	if o == nil || IsNil(o.ErrorCode.Get()) {
		var ret int32
		return ret
	}
	return *o.ErrorCode.Get()
}

// GetErrorCodeOk returns a tuple with the ErrorCode field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *CreateClusterResponse) GetErrorCodeOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return o.ErrorCode.Get(), o.ErrorCode.IsSet()
}

// HasErrorCode returns a boolean if a field has been set.
func (o *CreateClusterResponse) HasErrorCode() bool {
	if o != nil && o.ErrorCode.IsSet() {
		return true
	}

	return false
}

// SetErrorCode gets a reference to the given NullableInt32 and assigns it to the ErrorCode field.
func (o *CreateClusterResponse) SetErrorCode(v int32) {
	o.ErrorCode.Set(&v)
}

// SetErrorCodeNil sets the value for ErrorCode to be an explicit nil
func (o *CreateClusterResponse) SetErrorCodeNil() {
	o.ErrorCode.Set(nil)
}

// UnsetErrorCode ensures that no value is present for ErrorCode, not even an explicit nil
func (o *CreateClusterResponse) UnsetErrorCode() {
	o.ErrorCode.Unset()
}

// GetMessages returns the Messages field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *CreateClusterResponse) GetMessages() string {
	if o == nil || IsNil(o.Messages.Get()) {
		var ret string
		return ret
	}
	return *o.Messages.Get()
}

// GetMessagesOk returns a tuple with the Messages field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *CreateClusterResponse) GetMessagesOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Messages.Get(), o.Messages.IsSet()
}

// HasMessages returns a boolean if a field has been set.
func (o *CreateClusterResponse) HasMessages() bool {
	if o != nil && o.Messages.IsSet() {
		return true
	}

	return false
}

// SetMessages gets a reference to the given NullableString and assigns it to the Messages field.
func (o *CreateClusterResponse) SetMessages(v string) {
	o.Messages.Set(&v)
}

// SetMessagesNil sets the value for Messages to be an explicit nil
func (o *CreateClusterResponse) SetMessagesNil() {
	o.Messages.Set(nil)
}

// UnsetMessages ensures that no value is present for Messages, not even an explicit nil
func (o *CreateClusterResponse) UnsetMessages() {
	o.Messages.Unset()
}

// GetSuccess returns the Success field value if set, zero value otherwise.
func (o *CreateClusterResponse) GetSuccess() bool {
	if o == nil || IsNil(o.Success) {
		var ret bool
		return ret
	}
	return *o.Success
}

// GetSuccessOk returns a tuple with the Success field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateClusterResponse) GetSuccessOk() (*bool, bool) {
	if o == nil || IsNil(o.Success) {
		return nil, false
	}
	return o.Success, true
}

// HasSuccess returns a boolean if a field has been set.
func (o *CreateClusterResponse) HasSuccess() bool {
	if o != nil && !IsNil(o.Success) {
		return true
	}

	return false
}

// SetSuccess gets a reference to the given bool and assigns it to the Success field.
func (o *CreateClusterResponse) SetSuccess(v bool) {
	o.Success = &v
}

// GetTimestamp returns the Timestamp field value if set, zero value otherwise.
func (o *CreateClusterResponse) GetTimestamp() time.Time {
	if o == nil || IsNil(o.Timestamp) {
		var ret time.Time
		return ret
	}
	return *o.Timestamp
}

// GetTimestampOk returns a tuple with the Timestamp field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateClusterResponse) GetTimestampOk() (*time.Time, bool) {
	if o == nil || IsNil(o.Timestamp) {
		return nil, false
	}
	return o.Timestamp, true
}

// HasTimestamp returns a boolean if a field has been set.
func (o *CreateClusterResponse) HasTimestamp() bool {
	if o != nil && !IsNil(o.Timestamp) {
		return true
	}

	return false
}

// SetTimestamp gets a reference to the given time.Time and assigns it to the Timestamp field.
func (o *CreateClusterResponse) SetTimestamp(v time.Time) {
	o.Timestamp = &v
}

// GetClusterInstance returns the ClusterInstance field value if set, zero value otherwise.
func (o *CreateClusterResponse) GetClusterInstance() ClusterInstance {
	if o == nil || IsNil(o.ClusterInstance) {
		var ret ClusterInstance
		return ret
	}
	return *o.ClusterInstance
}

// GetClusterInstanceOk returns a tuple with the ClusterInstance field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateClusterResponse) GetClusterInstanceOk() (*ClusterInstance, bool) {
	if o == nil || IsNil(o.ClusterInstance) {
		return nil, false
	}
	return o.ClusterInstance, true
}

// HasClusterInstance returns a boolean if a field has been set.
func (o *CreateClusterResponse) HasClusterInstance() bool {
	if o != nil && !IsNil(o.ClusterInstance) {
		return true
	}

	return false
}

// SetClusterInstance gets a reference to the given ClusterInstance and assigns it to the ClusterInstance field.
func (o *CreateClusterResponse) SetClusterInstance(v ClusterInstance) {
	o.ClusterInstance = &v
}

// GetRequestInstance returns the RequestInstance field value if set, zero value otherwise.
func (o *CreateClusterResponse) GetRequestInstance() RequestInstance {
	if o == nil || IsNil(o.RequestInstance) {
		var ret RequestInstance
		return ret
	}
	return *o.RequestInstance
}

// GetRequestInstanceOk returns a tuple with the RequestInstance field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateClusterResponse) GetRequestInstanceOk() (*RequestInstance, bool) {
	if o == nil || IsNil(o.RequestInstance) {
		return nil, false
	}
	return o.RequestInstance, true
}

// HasRequestInstance returns a boolean if a field has been set.
func (o *CreateClusterResponse) HasRequestInstance() bool {
	if o != nil && !IsNil(o.RequestInstance) {
		return true
	}

	return false
}

// SetRequestInstance gets a reference to the given RequestInstance and assigns it to the RequestInstance field.
func (o *CreateClusterResponse) SetRequestInstance(v RequestInstance) {
	o.RequestInstance = &v
}

func (o CreateClusterResponse) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CreateClusterResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if o.ErrorCode.IsSet() {
		toSerialize["errorCode"] = o.ErrorCode.Get()
	}
	if o.Messages.IsSet() {
		toSerialize["messages"] = o.Messages.Get()
	}
	if !IsNil(o.Success) {
		toSerialize["success"] = o.Success
	}
	if !IsNil(o.Timestamp) {
		toSerialize["timestamp"] = o.Timestamp
	}
	if !IsNil(o.ClusterInstance) {
		toSerialize["clusterInstance"] = o.ClusterInstance
	}
	if !IsNil(o.RequestInstance) {
		toSerialize["requestInstance"] = o.RequestInstance
	}
	return toSerialize, nil
}

type NullableCreateClusterResponse struct {
	value *CreateClusterResponse
	isSet bool
}

func (v NullableCreateClusterResponse) Get() *CreateClusterResponse {
	return v.value
}

func (v *NullableCreateClusterResponse) Set(val *CreateClusterResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateClusterResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateClusterResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateClusterResponse(val *CreateClusterResponse) *NullableCreateClusterResponse {
	return &NullableCreateClusterResponse{value: val, isSet: true}
}

func (v NullableCreateClusterResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateClusterResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
