/*
Platforma OChK - Proxy API

Platforma OChK - Proxy API

API version: v1
Contact: pomoc@ochk.pl
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"time"
)

// checks if the GetGfwRuleResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetGfwRuleResponse{}

// GetGfwRuleResponse struct for GetGfwRuleResponse
type GetGfwRuleResponse struct {
	ErrorCode    NullableInt32  `json:"errorCode,omitempty"`
	Messages     NullableString `json:"messages,omitempty"`
	Success      *bool          `json:"success,omitempty"`
	Timestamp    *time.Time     `json:"timestamp,omitempty"`
	RuleInstance *GfwRule       `json:"ruleInstance,omitempty"`
}

// NewGetGfwRuleResponse instantiates a new GetGfwRuleResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetGfwRuleResponse() *GetGfwRuleResponse {
	this := GetGfwRuleResponse{}
	return &this
}

// NewGetGfwRuleResponseWithDefaults instantiates a new GetGfwRuleResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetGfwRuleResponseWithDefaults() *GetGfwRuleResponse {
	this := GetGfwRuleResponse{}
	return &this
}

// GetErrorCode returns the ErrorCode field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *GetGfwRuleResponse) GetErrorCode() int32 {
	if o == nil || IsNil(o.ErrorCode.Get()) {
		var ret int32
		return ret
	}
	return *o.ErrorCode.Get()
}

// GetErrorCodeOk returns a tuple with the ErrorCode field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *GetGfwRuleResponse) GetErrorCodeOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return o.ErrorCode.Get(), o.ErrorCode.IsSet()
}

// HasErrorCode returns a boolean if a field has been set.
func (o *GetGfwRuleResponse) HasErrorCode() bool {
	if o != nil && o.ErrorCode.IsSet() {
		return true
	}

	return false
}

// SetErrorCode gets a reference to the given NullableInt32 and assigns it to the ErrorCode field.
func (o *GetGfwRuleResponse) SetErrorCode(v int32) {
	o.ErrorCode.Set(&v)
}

// SetErrorCodeNil sets the value for ErrorCode to be an explicit nil
func (o *GetGfwRuleResponse) SetErrorCodeNil() {
	o.ErrorCode.Set(nil)
}

// UnsetErrorCode ensures that no value is present for ErrorCode, not even an explicit nil
func (o *GetGfwRuleResponse) UnsetErrorCode() {
	o.ErrorCode.Unset()
}

// GetMessages returns the Messages field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *GetGfwRuleResponse) GetMessages() string {
	if o == nil || IsNil(o.Messages.Get()) {
		var ret string
		return ret
	}
	return *o.Messages.Get()
}

// GetMessagesOk returns a tuple with the Messages field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *GetGfwRuleResponse) GetMessagesOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Messages.Get(), o.Messages.IsSet()
}

// HasMessages returns a boolean if a field has been set.
func (o *GetGfwRuleResponse) HasMessages() bool {
	if o != nil && o.Messages.IsSet() {
		return true
	}

	return false
}

// SetMessages gets a reference to the given NullableString and assigns it to the Messages field.
func (o *GetGfwRuleResponse) SetMessages(v string) {
	o.Messages.Set(&v)
}

// SetMessagesNil sets the value for Messages to be an explicit nil
func (o *GetGfwRuleResponse) SetMessagesNil() {
	o.Messages.Set(nil)
}

// UnsetMessages ensures that no value is present for Messages, not even an explicit nil
func (o *GetGfwRuleResponse) UnsetMessages() {
	o.Messages.Unset()
}

// GetSuccess returns the Success field value if set, zero value otherwise.
func (o *GetGfwRuleResponse) GetSuccess() bool {
	if o == nil || IsNil(o.Success) {
		var ret bool
		return ret
	}
	return *o.Success
}

// GetSuccessOk returns a tuple with the Success field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetGfwRuleResponse) GetSuccessOk() (*bool, bool) {
	if o == nil || IsNil(o.Success) {
		return nil, false
	}
	return o.Success, true
}

// HasSuccess returns a boolean if a field has been set.
func (o *GetGfwRuleResponse) HasSuccess() bool {
	if o != nil && !IsNil(o.Success) {
		return true
	}

	return false
}

// SetSuccess gets a reference to the given bool and assigns it to the Success field.
func (o *GetGfwRuleResponse) SetSuccess(v bool) {
	o.Success = &v
}

// GetTimestamp returns the Timestamp field value if set, zero value otherwise.
func (o *GetGfwRuleResponse) GetTimestamp() time.Time {
	if o == nil || IsNil(o.Timestamp) {
		var ret time.Time
		return ret
	}
	return *o.Timestamp
}

// GetTimestampOk returns a tuple with the Timestamp field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetGfwRuleResponse) GetTimestampOk() (*time.Time, bool) {
	if o == nil || IsNil(o.Timestamp) {
		return nil, false
	}
	return o.Timestamp, true
}

// HasTimestamp returns a boolean if a field has been set.
func (o *GetGfwRuleResponse) HasTimestamp() bool {
	if o != nil && !IsNil(o.Timestamp) {
		return true
	}

	return false
}

// SetTimestamp gets a reference to the given time.Time and assigns it to the Timestamp field.
func (o *GetGfwRuleResponse) SetTimestamp(v time.Time) {
	o.Timestamp = &v
}

// GetRuleInstance returns the RuleInstance field value if set, zero value otherwise.
func (o *GetGfwRuleResponse) GetRuleInstance() GfwRule {
	if o == nil || IsNil(o.RuleInstance) {
		var ret GfwRule
		return ret
	}
	return *o.RuleInstance
}

// GetRuleInstanceOk returns a tuple with the RuleInstance field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetGfwRuleResponse) GetRuleInstanceOk() (*GfwRule, bool) {
	if o == nil || IsNil(o.RuleInstance) {
		return nil, false
	}
	return o.RuleInstance, true
}

// HasRuleInstance returns a boolean if a field has been set.
func (o *GetGfwRuleResponse) HasRuleInstance() bool {
	if o != nil && !IsNil(o.RuleInstance) {
		return true
	}

	return false
}

// SetRuleInstance gets a reference to the given GfwRule and assigns it to the RuleInstance field.
func (o *GetGfwRuleResponse) SetRuleInstance(v GfwRule) {
	o.RuleInstance = &v
}

func (o GetGfwRuleResponse) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetGfwRuleResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if o.ErrorCode.IsSet() {
		toSerialize["errorCode"] = o.ErrorCode.Get()
	}
	if o.Messages.IsSet() {
		toSerialize["messages"] = o.Messages.Get()
	}
	if !IsNil(o.Success) {
		toSerialize["success"] = o.Success
	}
	if !IsNil(o.Timestamp) {
		toSerialize["timestamp"] = o.Timestamp
	}
	if !IsNil(o.RuleInstance) {
		toSerialize["ruleInstance"] = o.RuleInstance
	}
	return toSerialize, nil
}

type NullableGetGfwRuleResponse struct {
	value *GetGfwRuleResponse
	isSet bool
}

func (v NullableGetGfwRuleResponse) Get() *GetGfwRuleResponse {
	return v.value
}

func (v *NullableGetGfwRuleResponse) Set(val *GetGfwRuleResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableGetGfwRuleResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableGetGfwRuleResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetGfwRuleResponse(val *GetGfwRuleResponse) *NullableGetGfwRuleResponse {
	return &NullableGetGfwRuleResponse{value: val, isSet: true}
}

func (v NullableGetGfwRuleResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetGfwRuleResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
