/*
Platforma OChK - Proxy API

Platforma OChK - Proxy API

API version: v1
Contact: pomoc@ochk.pl
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the UserInstance type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UserInstance{}

// UserInstance struct for UserInstance
type UserInstance struct {
	UserId           NullableString  `json:"userId,omitempty"`
	ScimUserId       NullableString  `json:"scimUserId,omitempty"`
	DisplayName      NullableString  `json:"displayName,omitempty"`
	FirstName        NullableString  `json:"firstName,omitempty"`
	LastName         NullableString  `json:"lastName,omitempty"`
	Email            NullableString  `json:"email,omitempty"`
	Enabled          *bool           `json:"enabled,omitempty"`
	Locked           *bool           `json:"locked,omitempty"`
	ResetPassword    *bool           `json:"resetPassword,omitempty"`
	Roles            NullableString  `json:"roles,omitempty"`
	Groups           []GroupInstance `json:"groups,omitempty"`
	RolesEffective   NullableString  `json:"rolesEffective,omitempty"`
	Image            NullableString  `json:"image,omitempty"`
	ApiAccess        *bool           `json:"apiAccess,omitempty"`
	CreationDate     NullableString  `json:"creationDate,omitempty"`
	ModificationDate NullableString  `json:"modificationDate,omitempty"`
	TfaEnabled       *bool           `json:"tfaEnabled,omitempty"`
	Platforms        NullableString  `json:"platforms,omitempty"`
	IsApiKey         *bool           `json:"isApiKey,omitempty"`
	ExternalId       NullableString  `json:"externalId,omitempty"`
}

// NewUserInstance instantiates a new UserInstance object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUserInstance() *UserInstance {
	this := UserInstance{}
	return &this
}

// NewUserInstanceWithDefaults instantiates a new UserInstance object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUserInstanceWithDefaults() *UserInstance {
	this := UserInstance{}
	return &this
}

// GetUserId returns the UserId field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *UserInstance) GetUserId() string {
	if o == nil || IsNil(o.UserId.Get()) {
		var ret string
		return ret
	}
	return *o.UserId.Get()
}

// GetUserIdOk returns a tuple with the UserId field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *UserInstance) GetUserIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.UserId.Get(), o.UserId.IsSet()
}

// HasUserId returns a boolean if a field has been set.
func (o *UserInstance) HasUserId() bool {
	if o != nil && o.UserId.IsSet() {
		return true
	}

	return false
}

// SetUserId gets a reference to the given NullableString and assigns it to the UserId field.
func (o *UserInstance) SetUserId(v string) {
	o.UserId.Set(&v)
}

// SetUserIdNil sets the value for UserId to be an explicit nil
func (o *UserInstance) SetUserIdNil() {
	o.UserId.Set(nil)
}

// UnsetUserId ensures that no value is present for UserId, not even an explicit nil
func (o *UserInstance) UnsetUserId() {
	o.UserId.Unset()
}

// GetScimUserId returns the ScimUserId field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *UserInstance) GetScimUserId() string {
	if o == nil || IsNil(o.ScimUserId.Get()) {
		var ret string
		return ret
	}
	return *o.ScimUserId.Get()
}

// GetScimUserIdOk returns a tuple with the ScimUserId field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *UserInstance) GetScimUserIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.ScimUserId.Get(), o.ScimUserId.IsSet()
}

// HasScimUserId returns a boolean if a field has been set.
func (o *UserInstance) HasScimUserId() bool {
	if o != nil && o.ScimUserId.IsSet() {
		return true
	}

	return false
}

// SetScimUserId gets a reference to the given NullableString and assigns it to the ScimUserId field.
func (o *UserInstance) SetScimUserId(v string) {
	o.ScimUserId.Set(&v)
}

// SetScimUserIdNil sets the value for ScimUserId to be an explicit nil
func (o *UserInstance) SetScimUserIdNil() {
	o.ScimUserId.Set(nil)
}

// UnsetScimUserId ensures that no value is present for ScimUserId, not even an explicit nil
func (o *UserInstance) UnsetScimUserId() {
	o.ScimUserId.Unset()
}

// GetDisplayName returns the DisplayName field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *UserInstance) GetDisplayName() string {
	if o == nil || IsNil(o.DisplayName.Get()) {
		var ret string
		return ret
	}
	return *o.DisplayName.Get()
}

// GetDisplayNameOk returns a tuple with the DisplayName field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *UserInstance) GetDisplayNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.DisplayName.Get(), o.DisplayName.IsSet()
}

// HasDisplayName returns a boolean if a field has been set.
func (o *UserInstance) HasDisplayName() bool {
	if o != nil && o.DisplayName.IsSet() {
		return true
	}

	return false
}

// SetDisplayName gets a reference to the given NullableString and assigns it to the DisplayName field.
func (o *UserInstance) SetDisplayName(v string) {
	o.DisplayName.Set(&v)
}

// SetDisplayNameNil sets the value for DisplayName to be an explicit nil
func (o *UserInstance) SetDisplayNameNil() {
	o.DisplayName.Set(nil)
}

// UnsetDisplayName ensures that no value is present for DisplayName, not even an explicit nil
func (o *UserInstance) UnsetDisplayName() {
	o.DisplayName.Unset()
}

// GetFirstName returns the FirstName field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *UserInstance) GetFirstName() string {
	if o == nil || IsNil(o.FirstName.Get()) {
		var ret string
		return ret
	}
	return *o.FirstName.Get()
}

// GetFirstNameOk returns a tuple with the FirstName field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *UserInstance) GetFirstNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.FirstName.Get(), o.FirstName.IsSet()
}

// HasFirstName returns a boolean if a field has been set.
func (o *UserInstance) HasFirstName() bool {
	if o != nil && o.FirstName.IsSet() {
		return true
	}

	return false
}

// SetFirstName gets a reference to the given NullableString and assigns it to the FirstName field.
func (o *UserInstance) SetFirstName(v string) {
	o.FirstName.Set(&v)
}

// SetFirstNameNil sets the value for FirstName to be an explicit nil
func (o *UserInstance) SetFirstNameNil() {
	o.FirstName.Set(nil)
}

// UnsetFirstName ensures that no value is present for FirstName, not even an explicit nil
func (o *UserInstance) UnsetFirstName() {
	o.FirstName.Unset()
}

// GetLastName returns the LastName field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *UserInstance) GetLastName() string {
	if o == nil || IsNil(o.LastName.Get()) {
		var ret string
		return ret
	}
	return *o.LastName.Get()
}

// GetLastNameOk returns a tuple with the LastName field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *UserInstance) GetLastNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.LastName.Get(), o.LastName.IsSet()
}

// HasLastName returns a boolean if a field has been set.
func (o *UserInstance) HasLastName() bool {
	if o != nil && o.LastName.IsSet() {
		return true
	}

	return false
}

// SetLastName gets a reference to the given NullableString and assigns it to the LastName field.
func (o *UserInstance) SetLastName(v string) {
	o.LastName.Set(&v)
}

// SetLastNameNil sets the value for LastName to be an explicit nil
func (o *UserInstance) SetLastNameNil() {
	o.LastName.Set(nil)
}

// UnsetLastName ensures that no value is present for LastName, not even an explicit nil
func (o *UserInstance) UnsetLastName() {
	o.LastName.Unset()
}

// GetEmail returns the Email field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *UserInstance) GetEmail() string {
	if o == nil || IsNil(o.Email.Get()) {
		var ret string
		return ret
	}
	return *o.Email.Get()
}

// GetEmailOk returns a tuple with the Email field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *UserInstance) GetEmailOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Email.Get(), o.Email.IsSet()
}

// HasEmail returns a boolean if a field has been set.
func (o *UserInstance) HasEmail() bool {
	if o != nil && o.Email.IsSet() {
		return true
	}

	return false
}

// SetEmail gets a reference to the given NullableString and assigns it to the Email field.
func (o *UserInstance) SetEmail(v string) {
	o.Email.Set(&v)
}

// SetEmailNil sets the value for Email to be an explicit nil
func (o *UserInstance) SetEmailNil() {
	o.Email.Set(nil)
}

// UnsetEmail ensures that no value is present for Email, not even an explicit nil
func (o *UserInstance) UnsetEmail() {
	o.Email.Unset()
}

// GetEnabled returns the Enabled field value if set, zero value otherwise.
func (o *UserInstance) GetEnabled() bool {
	if o == nil || IsNil(o.Enabled) {
		var ret bool
		return ret
	}
	return *o.Enabled
}

// GetEnabledOk returns a tuple with the Enabled field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UserInstance) GetEnabledOk() (*bool, bool) {
	if o == nil || IsNil(o.Enabled) {
		return nil, false
	}
	return o.Enabled, true
}

// HasEnabled returns a boolean if a field has been set.
func (o *UserInstance) HasEnabled() bool {
	if o != nil && !IsNil(o.Enabled) {
		return true
	}

	return false
}

// SetEnabled gets a reference to the given bool and assigns it to the Enabled field.
func (o *UserInstance) SetEnabled(v bool) {
	o.Enabled = &v
}

// GetLocked returns the Locked field value if set, zero value otherwise.
func (o *UserInstance) GetLocked() bool {
	if o == nil || IsNil(o.Locked) {
		var ret bool
		return ret
	}
	return *o.Locked
}

// GetLockedOk returns a tuple with the Locked field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UserInstance) GetLockedOk() (*bool, bool) {
	if o == nil || IsNil(o.Locked) {
		return nil, false
	}
	return o.Locked, true
}

// HasLocked returns a boolean if a field has been set.
func (o *UserInstance) HasLocked() bool {
	if o != nil && !IsNil(o.Locked) {
		return true
	}

	return false
}

// SetLocked gets a reference to the given bool and assigns it to the Locked field.
func (o *UserInstance) SetLocked(v bool) {
	o.Locked = &v
}

// GetResetPassword returns the ResetPassword field value if set, zero value otherwise.
func (o *UserInstance) GetResetPassword() bool {
	if o == nil || IsNil(o.ResetPassword) {
		var ret bool
		return ret
	}
	return *o.ResetPassword
}

// GetResetPasswordOk returns a tuple with the ResetPassword field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UserInstance) GetResetPasswordOk() (*bool, bool) {
	if o == nil || IsNil(o.ResetPassword) {
		return nil, false
	}
	return o.ResetPassword, true
}

// HasResetPassword returns a boolean if a field has been set.
func (o *UserInstance) HasResetPassword() bool {
	if o != nil && !IsNil(o.ResetPassword) {
		return true
	}

	return false
}

// SetResetPassword gets a reference to the given bool and assigns it to the ResetPassword field.
func (o *UserInstance) SetResetPassword(v bool) {
	o.ResetPassword = &v
}

// GetRoles returns the Roles field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *UserInstance) GetRoles() string {
	if o == nil || IsNil(o.Roles.Get()) {
		var ret string
		return ret
	}
	return *o.Roles.Get()
}

// GetRolesOk returns a tuple with the Roles field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *UserInstance) GetRolesOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Roles.Get(), o.Roles.IsSet()
}

// HasRoles returns a boolean if a field has been set.
func (o *UserInstance) HasRoles() bool {
	if o != nil && o.Roles.IsSet() {
		return true
	}

	return false
}

// SetRoles gets a reference to the given NullableString and assigns it to the Roles field.
func (o *UserInstance) SetRoles(v string) {
	o.Roles.Set(&v)
}

// SetRolesNil sets the value for Roles to be an explicit nil
func (o *UserInstance) SetRolesNil() {
	o.Roles.Set(nil)
}

// UnsetRoles ensures that no value is present for Roles, not even an explicit nil
func (o *UserInstance) UnsetRoles() {
	o.Roles.Unset()
}

// GetGroups returns the Groups field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *UserInstance) GetGroups() []GroupInstance {
	if o == nil {
		var ret []GroupInstance
		return ret
	}
	return o.Groups
}

// GetGroupsOk returns a tuple with the Groups field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *UserInstance) GetGroupsOk() ([]GroupInstance, bool) {
	if o == nil || IsNil(o.Groups) {
		return nil, false
	}
	return o.Groups, true
}

// HasGroups returns a boolean if a field has been set.
func (o *UserInstance) HasGroups() bool {
	if o != nil && !IsNil(o.Groups) {
		return true
	}

	return false
}

// SetGroups gets a reference to the given []GroupInstance and assigns it to the Groups field.
func (o *UserInstance) SetGroups(v []GroupInstance) {
	o.Groups = v
}

// GetRolesEffective returns the RolesEffective field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *UserInstance) GetRolesEffective() string {
	if o == nil || IsNil(o.RolesEffective.Get()) {
		var ret string
		return ret
	}
	return *o.RolesEffective.Get()
}

// GetRolesEffectiveOk returns a tuple with the RolesEffective field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *UserInstance) GetRolesEffectiveOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.RolesEffective.Get(), o.RolesEffective.IsSet()
}

// HasRolesEffective returns a boolean if a field has been set.
func (o *UserInstance) HasRolesEffective() bool {
	if o != nil && o.RolesEffective.IsSet() {
		return true
	}

	return false
}

// SetRolesEffective gets a reference to the given NullableString and assigns it to the RolesEffective field.
func (o *UserInstance) SetRolesEffective(v string) {
	o.RolesEffective.Set(&v)
}

// SetRolesEffectiveNil sets the value for RolesEffective to be an explicit nil
func (o *UserInstance) SetRolesEffectiveNil() {
	o.RolesEffective.Set(nil)
}

// UnsetRolesEffective ensures that no value is present for RolesEffective, not even an explicit nil
func (o *UserInstance) UnsetRolesEffective() {
	o.RolesEffective.Unset()
}

// GetImage returns the Image field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *UserInstance) GetImage() string {
	if o == nil || IsNil(o.Image.Get()) {
		var ret string
		return ret
	}
	return *o.Image.Get()
}

// GetImageOk returns a tuple with the Image field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *UserInstance) GetImageOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Image.Get(), o.Image.IsSet()
}

// HasImage returns a boolean if a field has been set.
func (o *UserInstance) HasImage() bool {
	if o != nil && o.Image.IsSet() {
		return true
	}

	return false
}

// SetImage gets a reference to the given NullableString and assigns it to the Image field.
func (o *UserInstance) SetImage(v string) {
	o.Image.Set(&v)
}

// SetImageNil sets the value for Image to be an explicit nil
func (o *UserInstance) SetImageNil() {
	o.Image.Set(nil)
}

// UnsetImage ensures that no value is present for Image, not even an explicit nil
func (o *UserInstance) UnsetImage() {
	o.Image.Unset()
}

// GetApiAccess returns the ApiAccess field value if set, zero value otherwise.
func (o *UserInstance) GetApiAccess() bool {
	if o == nil || IsNil(o.ApiAccess) {
		var ret bool
		return ret
	}
	return *o.ApiAccess
}

// GetApiAccessOk returns a tuple with the ApiAccess field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UserInstance) GetApiAccessOk() (*bool, bool) {
	if o == nil || IsNil(o.ApiAccess) {
		return nil, false
	}
	return o.ApiAccess, true
}

// HasApiAccess returns a boolean if a field has been set.
func (o *UserInstance) HasApiAccess() bool {
	if o != nil && !IsNil(o.ApiAccess) {
		return true
	}

	return false
}

// SetApiAccess gets a reference to the given bool and assigns it to the ApiAccess field.
func (o *UserInstance) SetApiAccess(v bool) {
	o.ApiAccess = &v
}

// GetCreationDate returns the CreationDate field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *UserInstance) GetCreationDate() string {
	if o == nil || IsNil(o.CreationDate.Get()) {
		var ret string
		return ret
	}
	return *o.CreationDate.Get()
}

// GetCreationDateOk returns a tuple with the CreationDate field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *UserInstance) GetCreationDateOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.CreationDate.Get(), o.CreationDate.IsSet()
}

// HasCreationDate returns a boolean if a field has been set.
func (o *UserInstance) HasCreationDate() bool {
	if o != nil && o.CreationDate.IsSet() {
		return true
	}

	return false
}

// SetCreationDate gets a reference to the given NullableString and assigns it to the CreationDate field.
func (o *UserInstance) SetCreationDate(v string) {
	o.CreationDate.Set(&v)
}

// SetCreationDateNil sets the value for CreationDate to be an explicit nil
func (o *UserInstance) SetCreationDateNil() {
	o.CreationDate.Set(nil)
}

// UnsetCreationDate ensures that no value is present for CreationDate, not even an explicit nil
func (o *UserInstance) UnsetCreationDate() {
	o.CreationDate.Unset()
}

// GetModificationDate returns the ModificationDate field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *UserInstance) GetModificationDate() string {
	if o == nil || IsNil(o.ModificationDate.Get()) {
		var ret string
		return ret
	}
	return *o.ModificationDate.Get()
}

// GetModificationDateOk returns a tuple with the ModificationDate field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *UserInstance) GetModificationDateOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.ModificationDate.Get(), o.ModificationDate.IsSet()
}

// HasModificationDate returns a boolean if a field has been set.
func (o *UserInstance) HasModificationDate() bool {
	if o != nil && o.ModificationDate.IsSet() {
		return true
	}

	return false
}

// SetModificationDate gets a reference to the given NullableString and assigns it to the ModificationDate field.
func (o *UserInstance) SetModificationDate(v string) {
	o.ModificationDate.Set(&v)
}

// SetModificationDateNil sets the value for ModificationDate to be an explicit nil
func (o *UserInstance) SetModificationDateNil() {
	o.ModificationDate.Set(nil)
}

// UnsetModificationDate ensures that no value is present for ModificationDate, not even an explicit nil
func (o *UserInstance) UnsetModificationDate() {
	o.ModificationDate.Unset()
}

// GetTfaEnabled returns the TfaEnabled field value if set, zero value otherwise.
func (o *UserInstance) GetTfaEnabled() bool {
	if o == nil || IsNil(o.TfaEnabled) {
		var ret bool
		return ret
	}
	return *o.TfaEnabled
}

// GetTfaEnabledOk returns a tuple with the TfaEnabled field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UserInstance) GetTfaEnabledOk() (*bool, bool) {
	if o == nil || IsNil(o.TfaEnabled) {
		return nil, false
	}
	return o.TfaEnabled, true
}

// HasTfaEnabled returns a boolean if a field has been set.
func (o *UserInstance) HasTfaEnabled() bool {
	if o != nil && !IsNil(o.TfaEnabled) {
		return true
	}

	return false
}

// SetTfaEnabled gets a reference to the given bool and assigns it to the TfaEnabled field.
func (o *UserInstance) SetTfaEnabled(v bool) {
	o.TfaEnabled = &v
}

// GetPlatforms returns the Platforms field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *UserInstance) GetPlatforms() string {
	if o == nil || IsNil(o.Platforms.Get()) {
		var ret string
		return ret
	}
	return *o.Platforms.Get()
}

// GetPlatformsOk returns a tuple with the Platforms field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *UserInstance) GetPlatformsOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Platforms.Get(), o.Platforms.IsSet()
}

// HasPlatforms returns a boolean if a field has been set.
func (o *UserInstance) HasPlatforms() bool {
	if o != nil && o.Platforms.IsSet() {
		return true
	}

	return false
}

// SetPlatforms gets a reference to the given NullableString and assigns it to the Platforms field.
func (o *UserInstance) SetPlatforms(v string) {
	o.Platforms.Set(&v)
}

// SetPlatformsNil sets the value for Platforms to be an explicit nil
func (o *UserInstance) SetPlatformsNil() {
	o.Platforms.Set(nil)
}

// UnsetPlatforms ensures that no value is present for Platforms, not even an explicit nil
func (o *UserInstance) UnsetPlatforms() {
	o.Platforms.Unset()
}

// GetIsApiKey returns the IsApiKey field value if set, zero value otherwise.
func (o *UserInstance) GetIsApiKey() bool {
	if o == nil || IsNil(o.IsApiKey) {
		var ret bool
		return ret
	}
	return *o.IsApiKey
}

// GetIsApiKeyOk returns a tuple with the IsApiKey field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UserInstance) GetIsApiKeyOk() (*bool, bool) {
	if o == nil || IsNil(o.IsApiKey) {
		return nil, false
	}
	return o.IsApiKey, true
}

// HasIsApiKey returns a boolean if a field has been set.
func (o *UserInstance) HasIsApiKey() bool {
	if o != nil && !IsNil(o.IsApiKey) {
		return true
	}

	return false
}

// SetIsApiKey gets a reference to the given bool and assigns it to the IsApiKey field.
func (o *UserInstance) SetIsApiKey(v bool) {
	o.IsApiKey = &v
}

// GetExternalId returns the ExternalId field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *UserInstance) GetExternalId() string {
	if o == nil || IsNil(o.ExternalId.Get()) {
		var ret string
		return ret
	}
	return *o.ExternalId.Get()
}

// GetExternalIdOk returns a tuple with the ExternalId field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *UserInstance) GetExternalIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.ExternalId.Get(), o.ExternalId.IsSet()
}

// HasExternalId returns a boolean if a field has been set.
func (o *UserInstance) HasExternalId() bool {
	if o != nil && o.ExternalId.IsSet() {
		return true
	}

	return false
}

// SetExternalId gets a reference to the given NullableString and assigns it to the ExternalId field.
func (o *UserInstance) SetExternalId(v string) {
	o.ExternalId.Set(&v)
}

// SetExternalIdNil sets the value for ExternalId to be an explicit nil
func (o *UserInstance) SetExternalIdNil() {
	o.ExternalId.Set(nil)
}

// UnsetExternalId ensures that no value is present for ExternalId, not even an explicit nil
func (o *UserInstance) UnsetExternalId() {
	o.ExternalId.Unset()
}

func (o UserInstance) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if o.UserId.IsSet() {
		toSerialize["userId"] = o.UserId.Get()
	}
	if o.ScimUserId.IsSet() {
		toSerialize["scimUserId"] = o.ScimUserId.Get()
	}
	if o.DisplayName.IsSet() {
		toSerialize["displayName"] = o.DisplayName.Get()
	}
	if o.FirstName.IsSet() {
		toSerialize["firstName"] = o.FirstName.Get()
	}
	if o.LastName.IsSet() {
		toSerialize["lastName"] = o.LastName.Get()
	}
	if o.Email.IsSet() {
		toSerialize["email"] = o.Email.Get()
	}
	if !IsNil(o.Enabled) {
		toSerialize["enabled"] = o.Enabled
	}
	if !IsNil(o.Locked) {
		toSerialize["locked"] = o.Locked
	}
	if !IsNil(o.ResetPassword) {
		toSerialize["resetPassword"] = o.ResetPassword
	}
	if o.Roles.IsSet() {
		toSerialize["roles"] = o.Roles.Get()
	}
	if o.Groups != nil {
		toSerialize["groups"] = o.Groups
	}
	if o.RolesEffective.IsSet() {
		toSerialize["rolesEffective"] = o.RolesEffective.Get()
	}
	if o.Image.IsSet() {
		toSerialize["image"] = o.Image.Get()
	}
	if !IsNil(o.ApiAccess) {
		toSerialize["apiAccess"] = o.ApiAccess
	}
	if o.CreationDate.IsSet() {
		toSerialize["creationDate"] = o.CreationDate.Get()
	}
	if o.ModificationDate.IsSet() {
		toSerialize["modificationDate"] = o.ModificationDate.Get()
	}
	if !IsNil(o.TfaEnabled) {
		toSerialize["tfaEnabled"] = o.TfaEnabled
	}
	if o.Platforms.IsSet() {
		toSerialize["platforms"] = o.Platforms.Get()
	}
	if !IsNil(o.IsApiKey) {
		toSerialize["isApiKey"] = o.IsApiKey
	}
	if o.ExternalId.IsSet() {
		toSerialize["externalId"] = o.ExternalId.Get()
	}
	return toSerialize, nil
}

type NullableUserInstance struct {
	value *UserInstance
	isSet bool
}

func (v NullableUserInstance) Get() *UserInstance {
	return v.value
}

func (v *NullableUserInstance) Set(val *UserInstance) {
	v.value = val
	v.isSet = true
}

func (v NullableUserInstance) IsSet() bool {
	return v.isSet
}

func (v *NullableUserInstance) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUserInstance(val *UserInstance) *NullableUserInstance {
	return &NullableUserInstance{value: val, isSet: true}
}

func (v NullableUserInstance) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUserInstance) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
