/*
Platforma OChK - Proxy API

Platforma OChK - Proxy API

API version: v1
Contact: pomoc@ochk.pl
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"time"
)

// checks if the ProjectInstance type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ProjectInstance{}

// ProjectInstance struct for ProjectInstance
type ProjectInstance struct {
	ProjectId             NullableString `json:"projectId,omitempty"`
	Id                    NullableString `json:"id,omitempty"`
	Description           NullableString `json:"description,omitempty"`
	Name                  NullableString `json:"name,omitempty"`
	LimitEnabled          *bool          `json:"limitEnabled,omitempty"`
	IsDeleted             *bool          `json:"isDeleted,omitempty"`
	CpuReserved           *int64         `json:"cpuReserved,omitempty"`
	MemoryReservedSizeMB  *int64         `json:"memoryReservedSizeMB,omitempty"`
	StorageReservedSizeGB *int64         `json:"storageReservedSizeGB,omitempty"`
	VmCount               *int64         `json:"vmCount,omitempty"`
	CpuAllocated          *int64         `json:"cpuAllocated,omitempty"`
	RamAllocated          *int64         `json:"ramAllocated,omitempty"`
	StorageAllocated      *int64         `json:"storageAllocated,omitempty"`
	CreationDate          NullableTime   `json:"creationDate,omitempty"`
	ModificationDate      NullableTime   `json:"modificationDate,omitempty"`
	Cost                  *float32       `json:"cost,omitempty"`
	EstimatedMonthlyCost  *float32       `json:"estimatedMonthlyCost,omitempty"`
	VrfId                 NullableString `json:"vrfId,omitempty"`
	AccountId             NullableString `json:"accountId,omitempty"`
}

// NewProjectInstance instantiates a new ProjectInstance object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewProjectInstance() *ProjectInstance {
	this := ProjectInstance{}
	return &this
}

// NewProjectInstanceWithDefaults instantiates a new ProjectInstance object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewProjectInstanceWithDefaults() *ProjectInstance {
	this := ProjectInstance{}
	return &this
}

// GetProjectId returns the ProjectId field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ProjectInstance) GetProjectId() string {
	if o == nil || IsNil(o.ProjectId.Get()) {
		var ret string
		return ret
	}
	return *o.ProjectId.Get()
}

// GetProjectIdOk returns a tuple with the ProjectId field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ProjectInstance) GetProjectIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.ProjectId.Get(), o.ProjectId.IsSet()
}

// HasProjectId returns a boolean if a field has been set.
func (o *ProjectInstance) HasProjectId() bool {
	if o != nil && o.ProjectId.IsSet() {
		return true
	}

	return false
}

// SetProjectId gets a reference to the given NullableString and assigns it to the ProjectId field.
func (o *ProjectInstance) SetProjectId(v string) {
	o.ProjectId.Set(&v)
}

// SetProjectIdNil sets the value for ProjectId to be an explicit nil
func (o *ProjectInstance) SetProjectIdNil() {
	o.ProjectId.Set(nil)
}

// UnsetProjectId ensures that no value is present for ProjectId, not even an explicit nil
func (o *ProjectInstance) UnsetProjectId() {
	o.ProjectId.Unset()
}

// GetId returns the Id field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ProjectInstance) GetId() string {
	if o == nil || IsNil(o.Id.Get()) {
		var ret string
		return ret
	}
	return *o.Id.Get()
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ProjectInstance) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Id.Get(), o.Id.IsSet()
}

// HasId returns a boolean if a field has been set.
func (o *ProjectInstance) HasId() bool {
	if o != nil && o.Id.IsSet() {
		return true
	}

	return false
}

// SetId gets a reference to the given NullableString and assigns it to the Id field.
func (o *ProjectInstance) SetId(v string) {
	o.Id.Set(&v)
}

// SetIdNil sets the value for Id to be an explicit nil
func (o *ProjectInstance) SetIdNil() {
	o.Id.Set(nil)
}

// UnsetId ensures that no value is present for Id, not even an explicit nil
func (o *ProjectInstance) UnsetId() {
	o.Id.Unset()
}

// GetDescription returns the Description field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ProjectInstance) GetDescription() string {
	if o == nil || IsNil(o.Description.Get()) {
		var ret string
		return ret
	}
	return *o.Description.Get()
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ProjectInstance) GetDescriptionOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Description.Get(), o.Description.IsSet()
}

// HasDescription returns a boolean if a field has been set.
func (o *ProjectInstance) HasDescription() bool {
	if o != nil && o.Description.IsSet() {
		return true
	}

	return false
}

// SetDescription gets a reference to the given NullableString and assigns it to the Description field.
func (o *ProjectInstance) SetDescription(v string) {
	o.Description.Set(&v)
}

// SetDescriptionNil sets the value for Description to be an explicit nil
func (o *ProjectInstance) SetDescriptionNil() {
	o.Description.Set(nil)
}

// UnsetDescription ensures that no value is present for Description, not even an explicit nil
func (o *ProjectInstance) UnsetDescription() {
	o.Description.Unset()
}

// GetName returns the Name field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ProjectInstance) GetName() string {
	if o == nil || IsNil(o.Name.Get()) {
		var ret string
		return ret
	}
	return *o.Name.Get()
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ProjectInstance) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Name.Get(), o.Name.IsSet()
}

// HasName returns a boolean if a field has been set.
func (o *ProjectInstance) HasName() bool {
	if o != nil && o.Name.IsSet() {
		return true
	}

	return false
}

// SetName gets a reference to the given NullableString and assigns it to the Name field.
func (o *ProjectInstance) SetName(v string) {
	o.Name.Set(&v)
}

// SetNameNil sets the value for Name to be an explicit nil
func (o *ProjectInstance) SetNameNil() {
	o.Name.Set(nil)
}

// UnsetName ensures that no value is present for Name, not even an explicit nil
func (o *ProjectInstance) UnsetName() {
	o.Name.Unset()
}

// GetLimitEnabled returns the LimitEnabled field value if set, zero value otherwise.
func (o *ProjectInstance) GetLimitEnabled() bool {
	if o == nil || IsNil(o.LimitEnabled) {
		var ret bool
		return ret
	}
	return *o.LimitEnabled
}

// GetLimitEnabledOk returns a tuple with the LimitEnabled field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProjectInstance) GetLimitEnabledOk() (*bool, bool) {
	if o == nil || IsNil(o.LimitEnabled) {
		return nil, false
	}
	return o.LimitEnabled, true
}

// HasLimitEnabled returns a boolean if a field has been set.
func (o *ProjectInstance) HasLimitEnabled() bool {
	if o != nil && !IsNil(o.LimitEnabled) {
		return true
	}

	return false
}

// SetLimitEnabled gets a reference to the given bool and assigns it to the LimitEnabled field.
func (o *ProjectInstance) SetLimitEnabled(v bool) {
	o.LimitEnabled = &v
}

// GetIsDeleted returns the IsDeleted field value if set, zero value otherwise.
func (o *ProjectInstance) GetIsDeleted() bool {
	if o == nil || IsNil(o.IsDeleted) {
		var ret bool
		return ret
	}
	return *o.IsDeleted
}

// GetIsDeletedOk returns a tuple with the IsDeleted field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProjectInstance) GetIsDeletedOk() (*bool, bool) {
	if o == nil || IsNil(o.IsDeleted) {
		return nil, false
	}
	return o.IsDeleted, true
}

// HasIsDeleted returns a boolean if a field has been set.
func (o *ProjectInstance) HasIsDeleted() bool {
	if o != nil && !IsNil(o.IsDeleted) {
		return true
	}

	return false
}

// SetIsDeleted gets a reference to the given bool and assigns it to the IsDeleted field.
func (o *ProjectInstance) SetIsDeleted(v bool) {
	o.IsDeleted = &v
}

// GetCpuReserved returns the CpuReserved field value if set, zero value otherwise.
func (o *ProjectInstance) GetCpuReserved() int64 {
	if o == nil || IsNil(o.CpuReserved) {
		var ret int64
		return ret
	}
	return *o.CpuReserved
}

// GetCpuReservedOk returns a tuple with the CpuReserved field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProjectInstance) GetCpuReservedOk() (*int64, bool) {
	if o == nil || IsNil(o.CpuReserved) {
		return nil, false
	}
	return o.CpuReserved, true
}

// HasCpuReserved returns a boolean if a field has been set.
func (o *ProjectInstance) HasCpuReserved() bool {
	if o != nil && !IsNil(o.CpuReserved) {
		return true
	}

	return false
}

// SetCpuReserved gets a reference to the given int64 and assigns it to the CpuReserved field.
func (o *ProjectInstance) SetCpuReserved(v int64) {
	o.CpuReserved = &v
}

// GetMemoryReservedSizeMB returns the MemoryReservedSizeMB field value if set, zero value otherwise.
func (o *ProjectInstance) GetMemoryReservedSizeMB() int64 {
	if o == nil || IsNil(o.MemoryReservedSizeMB) {
		var ret int64
		return ret
	}
	return *o.MemoryReservedSizeMB
}

// GetMemoryReservedSizeMBOk returns a tuple with the MemoryReservedSizeMB field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProjectInstance) GetMemoryReservedSizeMBOk() (*int64, bool) {
	if o == nil || IsNil(o.MemoryReservedSizeMB) {
		return nil, false
	}
	return o.MemoryReservedSizeMB, true
}

// HasMemoryReservedSizeMB returns a boolean if a field has been set.
func (o *ProjectInstance) HasMemoryReservedSizeMB() bool {
	if o != nil && !IsNil(o.MemoryReservedSizeMB) {
		return true
	}

	return false
}

// SetMemoryReservedSizeMB gets a reference to the given int64 and assigns it to the MemoryReservedSizeMB field.
func (o *ProjectInstance) SetMemoryReservedSizeMB(v int64) {
	o.MemoryReservedSizeMB = &v
}

// GetStorageReservedSizeGB returns the StorageReservedSizeGB field value if set, zero value otherwise.
func (o *ProjectInstance) GetStorageReservedSizeGB() int64 {
	if o == nil || IsNil(o.StorageReservedSizeGB) {
		var ret int64
		return ret
	}
	return *o.StorageReservedSizeGB
}

// GetStorageReservedSizeGBOk returns a tuple with the StorageReservedSizeGB field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProjectInstance) GetStorageReservedSizeGBOk() (*int64, bool) {
	if o == nil || IsNil(o.StorageReservedSizeGB) {
		return nil, false
	}
	return o.StorageReservedSizeGB, true
}

// HasStorageReservedSizeGB returns a boolean if a field has been set.
func (o *ProjectInstance) HasStorageReservedSizeGB() bool {
	if o != nil && !IsNil(o.StorageReservedSizeGB) {
		return true
	}

	return false
}

// SetStorageReservedSizeGB gets a reference to the given int64 and assigns it to the StorageReservedSizeGB field.
func (o *ProjectInstance) SetStorageReservedSizeGB(v int64) {
	o.StorageReservedSizeGB = &v
}

// GetVmCount returns the VmCount field value if set, zero value otherwise.
func (o *ProjectInstance) GetVmCount() int64 {
	if o == nil || IsNil(o.VmCount) {
		var ret int64
		return ret
	}
	return *o.VmCount
}

// GetVmCountOk returns a tuple with the VmCount field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProjectInstance) GetVmCountOk() (*int64, bool) {
	if o == nil || IsNil(o.VmCount) {
		return nil, false
	}
	return o.VmCount, true
}

// HasVmCount returns a boolean if a field has been set.
func (o *ProjectInstance) HasVmCount() bool {
	if o != nil && !IsNil(o.VmCount) {
		return true
	}

	return false
}

// SetVmCount gets a reference to the given int64 and assigns it to the VmCount field.
func (o *ProjectInstance) SetVmCount(v int64) {
	o.VmCount = &v
}

// GetCpuAllocated returns the CpuAllocated field value if set, zero value otherwise.
func (o *ProjectInstance) GetCpuAllocated() int64 {
	if o == nil || IsNil(o.CpuAllocated) {
		var ret int64
		return ret
	}
	return *o.CpuAllocated
}

// GetCpuAllocatedOk returns a tuple with the CpuAllocated field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProjectInstance) GetCpuAllocatedOk() (*int64, bool) {
	if o == nil || IsNil(o.CpuAllocated) {
		return nil, false
	}
	return o.CpuAllocated, true
}

// HasCpuAllocated returns a boolean if a field has been set.
func (o *ProjectInstance) HasCpuAllocated() bool {
	if o != nil && !IsNil(o.CpuAllocated) {
		return true
	}

	return false
}

// SetCpuAllocated gets a reference to the given int64 and assigns it to the CpuAllocated field.
func (o *ProjectInstance) SetCpuAllocated(v int64) {
	o.CpuAllocated = &v
}

// GetRamAllocated returns the RamAllocated field value if set, zero value otherwise.
func (o *ProjectInstance) GetRamAllocated() int64 {
	if o == nil || IsNil(o.RamAllocated) {
		var ret int64
		return ret
	}
	return *o.RamAllocated
}

// GetRamAllocatedOk returns a tuple with the RamAllocated field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProjectInstance) GetRamAllocatedOk() (*int64, bool) {
	if o == nil || IsNil(o.RamAllocated) {
		return nil, false
	}
	return o.RamAllocated, true
}

// HasRamAllocated returns a boolean if a field has been set.
func (o *ProjectInstance) HasRamAllocated() bool {
	if o != nil && !IsNil(o.RamAllocated) {
		return true
	}

	return false
}

// SetRamAllocated gets a reference to the given int64 and assigns it to the RamAllocated field.
func (o *ProjectInstance) SetRamAllocated(v int64) {
	o.RamAllocated = &v
}

// GetStorageAllocated returns the StorageAllocated field value if set, zero value otherwise.
func (o *ProjectInstance) GetStorageAllocated() int64 {
	if o == nil || IsNil(o.StorageAllocated) {
		var ret int64
		return ret
	}
	return *o.StorageAllocated
}

// GetStorageAllocatedOk returns a tuple with the StorageAllocated field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProjectInstance) GetStorageAllocatedOk() (*int64, bool) {
	if o == nil || IsNil(o.StorageAllocated) {
		return nil, false
	}
	return o.StorageAllocated, true
}

// HasStorageAllocated returns a boolean if a field has been set.
func (o *ProjectInstance) HasStorageAllocated() bool {
	if o != nil && !IsNil(o.StorageAllocated) {
		return true
	}

	return false
}

// SetStorageAllocated gets a reference to the given int64 and assigns it to the StorageAllocated field.
func (o *ProjectInstance) SetStorageAllocated(v int64) {
	o.StorageAllocated = &v
}

// GetCreationDate returns the CreationDate field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ProjectInstance) GetCreationDate() time.Time {
	if o == nil || IsNil(o.CreationDate.Get()) {
		var ret time.Time
		return ret
	}
	return *o.CreationDate.Get()
}

// GetCreationDateOk returns a tuple with the CreationDate field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ProjectInstance) GetCreationDateOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return o.CreationDate.Get(), o.CreationDate.IsSet()
}

// HasCreationDate returns a boolean if a field has been set.
func (o *ProjectInstance) HasCreationDate() bool {
	if o != nil && o.CreationDate.IsSet() {
		return true
	}

	return false
}

// SetCreationDate gets a reference to the given NullableTime and assigns it to the CreationDate field.
func (o *ProjectInstance) SetCreationDate(v time.Time) {
	o.CreationDate.Set(&v)
}

// SetCreationDateNil sets the value for CreationDate to be an explicit nil
func (o *ProjectInstance) SetCreationDateNil() {
	o.CreationDate.Set(nil)
}

// UnsetCreationDate ensures that no value is present for CreationDate, not even an explicit nil
func (o *ProjectInstance) UnsetCreationDate() {
	o.CreationDate.Unset()
}

// GetModificationDate returns the ModificationDate field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ProjectInstance) GetModificationDate() time.Time {
	if o == nil || IsNil(o.ModificationDate.Get()) {
		var ret time.Time
		return ret
	}
	return *o.ModificationDate.Get()
}

// GetModificationDateOk returns a tuple with the ModificationDate field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ProjectInstance) GetModificationDateOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return o.ModificationDate.Get(), o.ModificationDate.IsSet()
}

// HasModificationDate returns a boolean if a field has been set.
func (o *ProjectInstance) HasModificationDate() bool {
	if o != nil && o.ModificationDate.IsSet() {
		return true
	}

	return false
}

// SetModificationDate gets a reference to the given NullableTime and assigns it to the ModificationDate field.
func (o *ProjectInstance) SetModificationDate(v time.Time) {
	o.ModificationDate.Set(&v)
}

// SetModificationDateNil sets the value for ModificationDate to be an explicit nil
func (o *ProjectInstance) SetModificationDateNil() {
	o.ModificationDate.Set(nil)
}

// UnsetModificationDate ensures that no value is present for ModificationDate, not even an explicit nil
func (o *ProjectInstance) UnsetModificationDate() {
	o.ModificationDate.Unset()
}

// GetCost returns the Cost field value if set, zero value otherwise.
func (o *ProjectInstance) GetCost() float32 {
	if o == nil || IsNil(o.Cost) {
		var ret float32
		return ret
	}
	return *o.Cost
}

// GetCostOk returns a tuple with the Cost field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProjectInstance) GetCostOk() (*float32, bool) {
	if o == nil || IsNil(o.Cost) {
		return nil, false
	}
	return o.Cost, true
}

// HasCost returns a boolean if a field has been set.
func (o *ProjectInstance) HasCost() bool {
	if o != nil && !IsNil(o.Cost) {
		return true
	}

	return false
}

// SetCost gets a reference to the given float32 and assigns it to the Cost field.
func (o *ProjectInstance) SetCost(v float32) {
	o.Cost = &v
}

// GetEstimatedMonthlyCost returns the EstimatedMonthlyCost field value if set, zero value otherwise.
func (o *ProjectInstance) GetEstimatedMonthlyCost() float32 {
	if o == nil || IsNil(o.EstimatedMonthlyCost) {
		var ret float32
		return ret
	}
	return *o.EstimatedMonthlyCost
}

// GetEstimatedMonthlyCostOk returns a tuple with the EstimatedMonthlyCost field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProjectInstance) GetEstimatedMonthlyCostOk() (*float32, bool) {
	if o == nil || IsNil(o.EstimatedMonthlyCost) {
		return nil, false
	}
	return o.EstimatedMonthlyCost, true
}

// HasEstimatedMonthlyCost returns a boolean if a field has been set.
func (o *ProjectInstance) HasEstimatedMonthlyCost() bool {
	if o != nil && !IsNil(o.EstimatedMonthlyCost) {
		return true
	}

	return false
}

// SetEstimatedMonthlyCost gets a reference to the given float32 and assigns it to the EstimatedMonthlyCost field.
func (o *ProjectInstance) SetEstimatedMonthlyCost(v float32) {
	o.EstimatedMonthlyCost = &v
}

// GetVrfId returns the VrfId field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ProjectInstance) GetVrfId() string {
	if o == nil || IsNil(o.VrfId.Get()) {
		var ret string
		return ret
	}
	return *o.VrfId.Get()
}

// GetVrfIdOk returns a tuple with the VrfId field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ProjectInstance) GetVrfIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.VrfId.Get(), o.VrfId.IsSet()
}

// HasVrfId returns a boolean if a field has been set.
func (o *ProjectInstance) HasVrfId() bool {
	if o != nil && o.VrfId.IsSet() {
		return true
	}

	return false
}

// SetVrfId gets a reference to the given NullableString and assigns it to the VrfId field.
func (o *ProjectInstance) SetVrfId(v string) {
	o.VrfId.Set(&v)
}

// SetVrfIdNil sets the value for VrfId to be an explicit nil
func (o *ProjectInstance) SetVrfIdNil() {
	o.VrfId.Set(nil)
}

// UnsetVrfId ensures that no value is present for VrfId, not even an explicit nil
func (o *ProjectInstance) UnsetVrfId() {
	o.VrfId.Unset()
}

// GetAccountId returns the AccountId field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ProjectInstance) GetAccountId() string {
	if o == nil || IsNil(o.AccountId.Get()) {
		var ret string
		return ret
	}
	return *o.AccountId.Get()
}

// GetAccountIdOk returns a tuple with the AccountId field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ProjectInstance) GetAccountIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.AccountId.Get(), o.AccountId.IsSet()
}

// HasAccountId returns a boolean if a field has been set.
func (o *ProjectInstance) HasAccountId() bool {
	if o != nil && o.AccountId.IsSet() {
		return true
	}

	return false
}

// SetAccountId gets a reference to the given NullableString and assigns it to the AccountId field.
func (o *ProjectInstance) SetAccountId(v string) {
	o.AccountId.Set(&v)
}

// SetAccountIdNil sets the value for AccountId to be an explicit nil
func (o *ProjectInstance) SetAccountIdNil() {
	o.AccountId.Set(nil)
}

// UnsetAccountId ensures that no value is present for AccountId, not even an explicit nil
func (o *ProjectInstance) UnsetAccountId() {
	o.AccountId.Unset()
}

func (o ProjectInstance) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ProjectInstance) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if o.ProjectId.IsSet() {
		toSerialize["projectId"] = o.ProjectId.Get()
	}
	if o.Id.IsSet() {
		toSerialize["id"] = o.Id.Get()
	}
	if o.Description.IsSet() {
		toSerialize["description"] = o.Description.Get()
	}
	if o.Name.IsSet() {
		toSerialize["name"] = o.Name.Get()
	}
	if !IsNil(o.LimitEnabled) {
		toSerialize["limitEnabled"] = o.LimitEnabled
	}
	if !IsNil(o.IsDeleted) {
		toSerialize["isDeleted"] = o.IsDeleted
	}
	if !IsNil(o.CpuReserved) {
		toSerialize["cpuReserved"] = o.CpuReserved
	}
	if !IsNil(o.MemoryReservedSizeMB) {
		toSerialize["memoryReservedSizeMB"] = o.MemoryReservedSizeMB
	}
	if !IsNil(o.StorageReservedSizeGB) {
		toSerialize["storageReservedSizeGB"] = o.StorageReservedSizeGB
	}
	if !IsNil(o.VmCount) {
		toSerialize["vmCount"] = o.VmCount
	}
	if !IsNil(o.CpuAllocated) {
		toSerialize["cpuAllocated"] = o.CpuAllocated
	}
	if !IsNil(o.RamAllocated) {
		toSerialize["ramAllocated"] = o.RamAllocated
	}
	if !IsNil(o.StorageAllocated) {
		toSerialize["storageAllocated"] = o.StorageAllocated
	}
	if o.CreationDate.IsSet() {
		toSerialize["creationDate"] = o.CreationDate.Get()
	}
	if o.ModificationDate.IsSet() {
		toSerialize["modificationDate"] = o.ModificationDate.Get()
	}
	if !IsNil(o.Cost) {
		toSerialize["cost"] = o.Cost
	}
	if !IsNil(o.EstimatedMonthlyCost) {
		toSerialize["estimatedMonthlyCost"] = o.EstimatedMonthlyCost
	}
	if o.VrfId.IsSet() {
		toSerialize["vrfId"] = o.VrfId.Get()
	}
	if o.AccountId.IsSet() {
		toSerialize["accountId"] = o.AccountId.Get()
	}
	return toSerialize, nil
}

type NullableProjectInstance struct {
	value *ProjectInstance
	isSet bool
}

func (v NullableProjectInstance) Get() *ProjectInstance {
	return v.value
}

func (v *NullableProjectInstance) Set(val *ProjectInstance) {
	v.value = val
	v.isSet = true
}

func (v NullableProjectInstance) IsSet() bool {
	return v.isSet
}

func (v *NullableProjectInstance) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableProjectInstance(val *ProjectInstance) *NullableProjectInstance {
	return &NullableProjectInstance{value: val, isSet: true}
}

func (v NullableProjectInstance) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableProjectInstance) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
