/*
Platforma OChK - Proxy API

Platforma OChK - Proxy API

API version: v1
Contact: pomoc@ochk.pl
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the CreateConfigMapDto type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CreateConfigMapDto{}

// CreateConfigMapDto struct for CreateConfigMapDto
type CreateConfigMapDto struct {
	ClientLbExtId       NullableString `json:"clientLbExtId,omitempty"`
	ClientLbIpPoolExtId NullableString `json:"clientLbIpPoolExtId,omitempty"`
	ClientLbIpPoolName  NullableString `json:"clientLbIpPoolName,omitempty"`
}

// NewCreateConfigMapDto instantiates a new CreateConfigMapDto object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateConfigMapDto() *CreateConfigMapDto {
	this := CreateConfigMapDto{}
	return &this
}

// NewCreateConfigMapDtoWithDefaults instantiates a new CreateConfigMapDto object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateConfigMapDtoWithDefaults() *CreateConfigMapDto {
	this := CreateConfigMapDto{}
	return &this
}

// GetClientLbExtId returns the ClientLbExtId field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *CreateConfigMapDto) GetClientLbExtId() string {
	if o == nil || IsNil(o.ClientLbExtId.Get()) {
		var ret string
		return ret
	}
	return *o.ClientLbExtId.Get()
}

// GetClientLbExtIdOk returns a tuple with the ClientLbExtId field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *CreateConfigMapDto) GetClientLbExtIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.ClientLbExtId.Get(), o.ClientLbExtId.IsSet()
}

// HasClientLbExtId returns a boolean if a field has been set.
func (o *CreateConfigMapDto) HasClientLbExtId() bool {
	if o != nil && o.ClientLbExtId.IsSet() {
		return true
	}

	return false
}

// SetClientLbExtId gets a reference to the given NullableString and assigns it to the ClientLbExtId field.
func (o *CreateConfigMapDto) SetClientLbExtId(v string) {
	o.ClientLbExtId.Set(&v)
}

// SetClientLbExtIdNil sets the value for ClientLbExtId to be an explicit nil
func (o *CreateConfigMapDto) SetClientLbExtIdNil() {
	o.ClientLbExtId.Set(nil)
}

// UnsetClientLbExtId ensures that no value is present for ClientLbExtId, not even an explicit nil
func (o *CreateConfigMapDto) UnsetClientLbExtId() {
	o.ClientLbExtId.Unset()
}

// GetClientLbIpPoolExtId returns the ClientLbIpPoolExtId field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *CreateConfigMapDto) GetClientLbIpPoolExtId() string {
	if o == nil || IsNil(o.ClientLbIpPoolExtId.Get()) {
		var ret string
		return ret
	}
	return *o.ClientLbIpPoolExtId.Get()
}

// GetClientLbIpPoolExtIdOk returns a tuple with the ClientLbIpPoolExtId field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *CreateConfigMapDto) GetClientLbIpPoolExtIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.ClientLbIpPoolExtId.Get(), o.ClientLbIpPoolExtId.IsSet()
}

// HasClientLbIpPoolExtId returns a boolean if a field has been set.
func (o *CreateConfigMapDto) HasClientLbIpPoolExtId() bool {
	if o != nil && o.ClientLbIpPoolExtId.IsSet() {
		return true
	}

	return false
}

// SetClientLbIpPoolExtId gets a reference to the given NullableString and assigns it to the ClientLbIpPoolExtId field.
func (o *CreateConfigMapDto) SetClientLbIpPoolExtId(v string) {
	o.ClientLbIpPoolExtId.Set(&v)
}

// SetClientLbIpPoolExtIdNil sets the value for ClientLbIpPoolExtId to be an explicit nil
func (o *CreateConfigMapDto) SetClientLbIpPoolExtIdNil() {
	o.ClientLbIpPoolExtId.Set(nil)
}

// UnsetClientLbIpPoolExtId ensures that no value is present for ClientLbIpPoolExtId, not even an explicit nil
func (o *CreateConfigMapDto) UnsetClientLbIpPoolExtId() {
	o.ClientLbIpPoolExtId.Unset()
}

// GetClientLbIpPoolName returns the ClientLbIpPoolName field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *CreateConfigMapDto) GetClientLbIpPoolName() string {
	if o == nil || IsNil(o.ClientLbIpPoolName.Get()) {
		var ret string
		return ret
	}
	return *o.ClientLbIpPoolName.Get()
}

// GetClientLbIpPoolNameOk returns a tuple with the ClientLbIpPoolName field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *CreateConfigMapDto) GetClientLbIpPoolNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.ClientLbIpPoolName.Get(), o.ClientLbIpPoolName.IsSet()
}

// HasClientLbIpPoolName returns a boolean if a field has been set.
func (o *CreateConfigMapDto) HasClientLbIpPoolName() bool {
	if o != nil && o.ClientLbIpPoolName.IsSet() {
		return true
	}

	return false
}

// SetClientLbIpPoolName gets a reference to the given NullableString and assigns it to the ClientLbIpPoolName field.
func (o *CreateConfigMapDto) SetClientLbIpPoolName(v string) {
	o.ClientLbIpPoolName.Set(&v)
}

// SetClientLbIpPoolNameNil sets the value for ClientLbIpPoolName to be an explicit nil
func (o *CreateConfigMapDto) SetClientLbIpPoolNameNil() {
	o.ClientLbIpPoolName.Set(nil)
}

// UnsetClientLbIpPoolName ensures that no value is present for ClientLbIpPoolName, not even an explicit nil
func (o *CreateConfigMapDto) UnsetClientLbIpPoolName() {
	o.ClientLbIpPoolName.Unset()
}

func (o CreateConfigMapDto) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CreateConfigMapDto) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if o.ClientLbExtId.IsSet() {
		toSerialize["clientLbExtId"] = o.ClientLbExtId.Get()
	}
	if o.ClientLbIpPoolExtId.IsSet() {
		toSerialize["clientLbIpPoolExtId"] = o.ClientLbIpPoolExtId.Get()
	}
	if o.ClientLbIpPoolName.IsSet() {
		toSerialize["clientLbIpPoolName"] = o.ClientLbIpPoolName.Get()
	}
	return toSerialize, nil
}

type NullableCreateConfigMapDto struct {
	value *CreateConfigMapDto
	isSet bool
}

func (v NullableCreateConfigMapDto) Get() *CreateConfigMapDto {
	return v.value
}

func (v *NullableCreateConfigMapDto) Set(val *CreateConfigMapDto) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateConfigMapDto) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateConfigMapDto) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateConfigMapDto(val *CreateConfigMapDto) *NullableCreateConfigMapDto {
	return &NullableCreateConfigMapDto{value: val, isSet: true}
}

func (v NullableCreateConfigMapDto) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateConfigMapDto) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
