/*
Platforma OChK - Proxy API

Platforma OChK - Proxy API

API version: v1
Contact: pomoc@ochk.pl
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the RouterInstance type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &RouterInstance{}

// RouterInstance struct for RouterInstance
type RouterInstance struct {
	RouterId                  NullableString          `json:"routerId,omitempty"`
	ExternalId                NullableString          `json:"externalId,omitempty"`
	RouterType                *RouterType             `json:"routerType,omitempty"`
	DisplayName               NullableString          `json:"displayName,omitempty"`
	DefaultRuleLogging        NullableBool            `json:"defaultRuleLogging,omitempty"`
	Description               NullableString          `json:"description,omitempty"`
	DisableFirewall           NullableBool            `json:"disableFirewall,omitempty"`
	FailoverMode              *FailoverMode           `json:"failoverMode,omitempty"`
	ForceWithListing          NullableBool            `json:"forceWithListing,omitempty"`
	HaMode                    *HAMode                 `json:"haMode,omitempty"`
	Overridden                NullableBool            `json:"overridden,omitempty"`
	ParentPath                NullableString          `json:"parentPath,omitempty"`
	Path                      NullableString          `json:"path,omitempty"`
	RelativePath              NullableString          `json:"relativePath,omitempty"`
	Protection                *Protection             `json:"protection,omitempty"`
	RdAdminField              NullableString          `json:"rdAdminField,omitempty"`
	ResourceType              *ResourceType           `json:"resourceType,omitempty"`
	Revision                  NullableInt64           `json:"revision,omitempty"`
	DhcpConfigPathList        []DhcpConfigPath        `json:"dhcpConfigPathList,omitempty"`
	InternalTransitSubnetList []InternalTransitSubnet `json:"internalTransitSubnetList,omitempty"`
	Ip6ProfilePathList        []IP6ProfilePath        `json:"ip6ProfilePathList,omitempty"`
	TransitSubnetList         []TransitSubnet         `json:"transitSubnetList,omitempty"`
	RouteAdvertisementType    []string                `json:"routeAdvertisementType,omitempty"`
	SchemaValue               NullableString          `json:"schemaValue,omitempty"`
	CreatedBy                 NullableString          `json:"createdBy,omitempty"`
	CreationDate              NullableString          `json:"creationDate,omitempty"`
	ModifiedBy                NullableString          `json:"modifiedBy,omitempty"`
	ModificationDate          NullableString          `json:"modificationDate,omitempty"`
	EdgeClusterInstance       *EdgeClusterInstance    `json:"edgeClusterInstance,omitempty"`
	Tier0Path                 NullableString          `json:"tier0Path,omitempty"`
	ParentT0Id                NullableString          `json:"parentT0Id,omitempty"`
	ProjectId                 NullableString          `json:"projectId,omitempty"`
	FolderPath                NullableString          `json:"folderPath,omitempty"`
	SnatEnabled               *bool                   `json:"snatEnabled,omitempty"`
	SnatIp                    NullableString          `json:"snatIp,omitempty"`
}

// NewRouterInstance instantiates a new RouterInstance object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewRouterInstance() *RouterInstance {
	this := RouterInstance{}
	return &this
}

// NewRouterInstanceWithDefaults instantiates a new RouterInstance object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewRouterInstanceWithDefaults() *RouterInstance {
	this := RouterInstance{}
	return &this
}

// GetRouterId returns the RouterId field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *RouterInstance) GetRouterId() string {
	if o == nil || IsNil(o.RouterId.Get()) {
		var ret string
		return ret
	}
	return *o.RouterId.Get()
}

// GetRouterIdOk returns a tuple with the RouterId field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *RouterInstance) GetRouterIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.RouterId.Get(), o.RouterId.IsSet()
}

// HasRouterId returns a boolean if a field has been set.
func (o *RouterInstance) HasRouterId() bool {
	if o != nil && o.RouterId.IsSet() {
		return true
	}

	return false
}

// SetRouterId gets a reference to the given NullableString and assigns it to the RouterId field.
func (o *RouterInstance) SetRouterId(v string) {
	o.RouterId.Set(&v)
}

// SetRouterIdNil sets the value for RouterId to be an explicit nil
func (o *RouterInstance) SetRouterIdNil() {
	o.RouterId.Set(nil)
}

// UnsetRouterId ensures that no value is present for RouterId, not even an explicit nil
func (o *RouterInstance) UnsetRouterId() {
	o.RouterId.Unset()
}

// GetExternalId returns the ExternalId field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *RouterInstance) GetExternalId() string {
	if o == nil || IsNil(o.ExternalId.Get()) {
		var ret string
		return ret
	}
	return *o.ExternalId.Get()
}

// GetExternalIdOk returns a tuple with the ExternalId field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *RouterInstance) GetExternalIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.ExternalId.Get(), o.ExternalId.IsSet()
}

// HasExternalId returns a boolean if a field has been set.
func (o *RouterInstance) HasExternalId() bool {
	if o != nil && o.ExternalId.IsSet() {
		return true
	}

	return false
}

// SetExternalId gets a reference to the given NullableString and assigns it to the ExternalId field.
func (o *RouterInstance) SetExternalId(v string) {
	o.ExternalId.Set(&v)
}

// SetExternalIdNil sets the value for ExternalId to be an explicit nil
func (o *RouterInstance) SetExternalIdNil() {
	o.ExternalId.Set(nil)
}

// UnsetExternalId ensures that no value is present for ExternalId, not even an explicit nil
func (o *RouterInstance) UnsetExternalId() {
	o.ExternalId.Unset()
}

// GetRouterType returns the RouterType field value if set, zero value otherwise.
func (o *RouterInstance) GetRouterType() RouterType {
	if o == nil || IsNil(o.RouterType) {
		var ret RouterType
		return ret
	}
	return *o.RouterType
}

// GetRouterTypeOk returns a tuple with the RouterType field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RouterInstance) GetRouterTypeOk() (*RouterType, bool) {
	if o == nil || IsNil(o.RouterType) {
		return nil, false
	}
	return o.RouterType, true
}

// HasRouterType returns a boolean if a field has been set.
func (o *RouterInstance) HasRouterType() bool {
	if o != nil && !IsNil(o.RouterType) {
		return true
	}

	return false
}

// SetRouterType gets a reference to the given RouterType and assigns it to the RouterType field.
func (o *RouterInstance) SetRouterType(v RouterType) {
	o.RouterType = &v
}

// GetDisplayName returns the DisplayName field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *RouterInstance) GetDisplayName() string {
	if o == nil || IsNil(o.DisplayName.Get()) {
		var ret string
		return ret
	}
	return *o.DisplayName.Get()
}

// GetDisplayNameOk returns a tuple with the DisplayName field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *RouterInstance) GetDisplayNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.DisplayName.Get(), o.DisplayName.IsSet()
}

// HasDisplayName returns a boolean if a field has been set.
func (o *RouterInstance) HasDisplayName() bool {
	if o != nil && o.DisplayName.IsSet() {
		return true
	}

	return false
}

// SetDisplayName gets a reference to the given NullableString and assigns it to the DisplayName field.
func (o *RouterInstance) SetDisplayName(v string) {
	o.DisplayName.Set(&v)
}

// SetDisplayNameNil sets the value for DisplayName to be an explicit nil
func (o *RouterInstance) SetDisplayNameNil() {
	o.DisplayName.Set(nil)
}

// UnsetDisplayName ensures that no value is present for DisplayName, not even an explicit nil
func (o *RouterInstance) UnsetDisplayName() {
	o.DisplayName.Unset()
}

// GetDefaultRuleLogging returns the DefaultRuleLogging field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *RouterInstance) GetDefaultRuleLogging() bool {
	if o == nil || IsNil(o.DefaultRuleLogging.Get()) {
		var ret bool
		return ret
	}
	return *o.DefaultRuleLogging.Get()
}

// GetDefaultRuleLoggingOk returns a tuple with the DefaultRuleLogging field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *RouterInstance) GetDefaultRuleLoggingOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return o.DefaultRuleLogging.Get(), o.DefaultRuleLogging.IsSet()
}

// HasDefaultRuleLogging returns a boolean if a field has been set.
func (o *RouterInstance) HasDefaultRuleLogging() bool {
	if o != nil && o.DefaultRuleLogging.IsSet() {
		return true
	}

	return false
}

// SetDefaultRuleLogging gets a reference to the given NullableBool and assigns it to the DefaultRuleLogging field.
func (o *RouterInstance) SetDefaultRuleLogging(v bool) {
	o.DefaultRuleLogging.Set(&v)
}

// SetDefaultRuleLoggingNil sets the value for DefaultRuleLogging to be an explicit nil
func (o *RouterInstance) SetDefaultRuleLoggingNil() {
	o.DefaultRuleLogging.Set(nil)
}

// UnsetDefaultRuleLogging ensures that no value is present for DefaultRuleLogging, not even an explicit nil
func (o *RouterInstance) UnsetDefaultRuleLogging() {
	o.DefaultRuleLogging.Unset()
}

// GetDescription returns the Description field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *RouterInstance) GetDescription() string {
	if o == nil || IsNil(o.Description.Get()) {
		var ret string
		return ret
	}
	return *o.Description.Get()
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *RouterInstance) GetDescriptionOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Description.Get(), o.Description.IsSet()
}

// HasDescription returns a boolean if a field has been set.
func (o *RouterInstance) HasDescription() bool {
	if o != nil && o.Description.IsSet() {
		return true
	}

	return false
}

// SetDescription gets a reference to the given NullableString and assigns it to the Description field.
func (o *RouterInstance) SetDescription(v string) {
	o.Description.Set(&v)
}

// SetDescriptionNil sets the value for Description to be an explicit nil
func (o *RouterInstance) SetDescriptionNil() {
	o.Description.Set(nil)
}

// UnsetDescription ensures that no value is present for Description, not even an explicit nil
func (o *RouterInstance) UnsetDescription() {
	o.Description.Unset()
}

// GetDisableFirewall returns the DisableFirewall field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *RouterInstance) GetDisableFirewall() bool {
	if o == nil || IsNil(o.DisableFirewall.Get()) {
		var ret bool
		return ret
	}
	return *o.DisableFirewall.Get()
}

// GetDisableFirewallOk returns a tuple with the DisableFirewall field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *RouterInstance) GetDisableFirewallOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return o.DisableFirewall.Get(), o.DisableFirewall.IsSet()
}

// HasDisableFirewall returns a boolean if a field has been set.
func (o *RouterInstance) HasDisableFirewall() bool {
	if o != nil && o.DisableFirewall.IsSet() {
		return true
	}

	return false
}

// SetDisableFirewall gets a reference to the given NullableBool and assigns it to the DisableFirewall field.
func (o *RouterInstance) SetDisableFirewall(v bool) {
	o.DisableFirewall.Set(&v)
}

// SetDisableFirewallNil sets the value for DisableFirewall to be an explicit nil
func (o *RouterInstance) SetDisableFirewallNil() {
	o.DisableFirewall.Set(nil)
}

// UnsetDisableFirewall ensures that no value is present for DisableFirewall, not even an explicit nil
func (o *RouterInstance) UnsetDisableFirewall() {
	o.DisableFirewall.Unset()
}

// GetFailoverMode returns the FailoverMode field value if set, zero value otherwise.
func (o *RouterInstance) GetFailoverMode() FailoverMode {
	if o == nil || IsNil(o.FailoverMode) {
		var ret FailoverMode
		return ret
	}
	return *o.FailoverMode
}

// GetFailoverModeOk returns a tuple with the FailoverMode field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RouterInstance) GetFailoverModeOk() (*FailoverMode, bool) {
	if o == nil || IsNil(o.FailoverMode) {
		return nil, false
	}
	return o.FailoverMode, true
}

// HasFailoverMode returns a boolean if a field has been set.
func (o *RouterInstance) HasFailoverMode() bool {
	if o != nil && !IsNil(o.FailoverMode) {
		return true
	}

	return false
}

// SetFailoverMode gets a reference to the given FailoverMode and assigns it to the FailoverMode field.
func (o *RouterInstance) SetFailoverMode(v FailoverMode) {
	o.FailoverMode = &v
}

// GetForceWithListing returns the ForceWithListing field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *RouterInstance) GetForceWithListing() bool {
	if o == nil || IsNil(o.ForceWithListing.Get()) {
		var ret bool
		return ret
	}
	return *o.ForceWithListing.Get()
}

// GetForceWithListingOk returns a tuple with the ForceWithListing field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *RouterInstance) GetForceWithListingOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return o.ForceWithListing.Get(), o.ForceWithListing.IsSet()
}

// HasForceWithListing returns a boolean if a field has been set.
func (o *RouterInstance) HasForceWithListing() bool {
	if o != nil && o.ForceWithListing.IsSet() {
		return true
	}

	return false
}

// SetForceWithListing gets a reference to the given NullableBool and assigns it to the ForceWithListing field.
func (o *RouterInstance) SetForceWithListing(v bool) {
	o.ForceWithListing.Set(&v)
}

// SetForceWithListingNil sets the value for ForceWithListing to be an explicit nil
func (o *RouterInstance) SetForceWithListingNil() {
	o.ForceWithListing.Set(nil)
}

// UnsetForceWithListing ensures that no value is present for ForceWithListing, not even an explicit nil
func (o *RouterInstance) UnsetForceWithListing() {
	o.ForceWithListing.Unset()
}

// GetHaMode returns the HaMode field value if set, zero value otherwise.
func (o *RouterInstance) GetHaMode() HAMode {
	if o == nil || IsNil(o.HaMode) {
		var ret HAMode
		return ret
	}
	return *o.HaMode
}

// GetHaModeOk returns a tuple with the HaMode field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RouterInstance) GetHaModeOk() (*HAMode, bool) {
	if o == nil || IsNil(o.HaMode) {
		return nil, false
	}
	return o.HaMode, true
}

// HasHaMode returns a boolean if a field has been set.
func (o *RouterInstance) HasHaMode() bool {
	if o != nil && !IsNil(o.HaMode) {
		return true
	}

	return false
}

// SetHaMode gets a reference to the given HAMode and assigns it to the HaMode field.
func (o *RouterInstance) SetHaMode(v HAMode) {
	o.HaMode = &v
}

// GetOverridden returns the Overridden field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *RouterInstance) GetOverridden() bool {
	if o == nil || IsNil(o.Overridden.Get()) {
		var ret bool
		return ret
	}
	return *o.Overridden.Get()
}

// GetOverriddenOk returns a tuple with the Overridden field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *RouterInstance) GetOverriddenOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return o.Overridden.Get(), o.Overridden.IsSet()
}

// HasOverridden returns a boolean if a field has been set.
func (o *RouterInstance) HasOverridden() bool {
	if o != nil && o.Overridden.IsSet() {
		return true
	}

	return false
}

// SetOverridden gets a reference to the given NullableBool and assigns it to the Overridden field.
func (o *RouterInstance) SetOverridden(v bool) {
	o.Overridden.Set(&v)
}

// SetOverriddenNil sets the value for Overridden to be an explicit nil
func (o *RouterInstance) SetOverriddenNil() {
	o.Overridden.Set(nil)
}

// UnsetOverridden ensures that no value is present for Overridden, not even an explicit nil
func (o *RouterInstance) UnsetOverridden() {
	o.Overridden.Unset()
}

// GetParentPath returns the ParentPath field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *RouterInstance) GetParentPath() string {
	if o == nil || IsNil(o.ParentPath.Get()) {
		var ret string
		return ret
	}
	return *o.ParentPath.Get()
}

// GetParentPathOk returns a tuple with the ParentPath field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *RouterInstance) GetParentPathOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.ParentPath.Get(), o.ParentPath.IsSet()
}

// HasParentPath returns a boolean if a field has been set.
func (o *RouterInstance) HasParentPath() bool {
	if o != nil && o.ParentPath.IsSet() {
		return true
	}

	return false
}

// SetParentPath gets a reference to the given NullableString and assigns it to the ParentPath field.
func (o *RouterInstance) SetParentPath(v string) {
	o.ParentPath.Set(&v)
}

// SetParentPathNil sets the value for ParentPath to be an explicit nil
func (o *RouterInstance) SetParentPathNil() {
	o.ParentPath.Set(nil)
}

// UnsetParentPath ensures that no value is present for ParentPath, not even an explicit nil
func (o *RouterInstance) UnsetParentPath() {
	o.ParentPath.Unset()
}

// GetPath returns the Path field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *RouterInstance) GetPath() string {
	if o == nil || IsNil(o.Path.Get()) {
		var ret string
		return ret
	}
	return *o.Path.Get()
}

// GetPathOk returns a tuple with the Path field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *RouterInstance) GetPathOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Path.Get(), o.Path.IsSet()
}

// HasPath returns a boolean if a field has been set.
func (o *RouterInstance) HasPath() bool {
	if o != nil && o.Path.IsSet() {
		return true
	}

	return false
}

// SetPath gets a reference to the given NullableString and assigns it to the Path field.
func (o *RouterInstance) SetPath(v string) {
	o.Path.Set(&v)
}

// SetPathNil sets the value for Path to be an explicit nil
func (o *RouterInstance) SetPathNil() {
	o.Path.Set(nil)
}

// UnsetPath ensures that no value is present for Path, not even an explicit nil
func (o *RouterInstance) UnsetPath() {
	o.Path.Unset()
}

// GetRelativePath returns the RelativePath field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *RouterInstance) GetRelativePath() string {
	if o == nil || IsNil(o.RelativePath.Get()) {
		var ret string
		return ret
	}
	return *o.RelativePath.Get()
}

// GetRelativePathOk returns a tuple with the RelativePath field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *RouterInstance) GetRelativePathOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.RelativePath.Get(), o.RelativePath.IsSet()
}

// HasRelativePath returns a boolean if a field has been set.
func (o *RouterInstance) HasRelativePath() bool {
	if o != nil && o.RelativePath.IsSet() {
		return true
	}

	return false
}

// SetRelativePath gets a reference to the given NullableString and assigns it to the RelativePath field.
func (o *RouterInstance) SetRelativePath(v string) {
	o.RelativePath.Set(&v)
}

// SetRelativePathNil sets the value for RelativePath to be an explicit nil
func (o *RouterInstance) SetRelativePathNil() {
	o.RelativePath.Set(nil)
}

// UnsetRelativePath ensures that no value is present for RelativePath, not even an explicit nil
func (o *RouterInstance) UnsetRelativePath() {
	o.RelativePath.Unset()
}

// GetProtection returns the Protection field value if set, zero value otherwise.
func (o *RouterInstance) GetProtection() Protection {
	if o == nil || IsNil(o.Protection) {
		var ret Protection
		return ret
	}
	return *o.Protection
}

// GetProtectionOk returns a tuple with the Protection field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RouterInstance) GetProtectionOk() (*Protection, bool) {
	if o == nil || IsNil(o.Protection) {
		return nil, false
	}
	return o.Protection, true
}

// HasProtection returns a boolean if a field has been set.
func (o *RouterInstance) HasProtection() bool {
	if o != nil && !IsNil(o.Protection) {
		return true
	}

	return false
}

// SetProtection gets a reference to the given Protection and assigns it to the Protection field.
func (o *RouterInstance) SetProtection(v Protection) {
	o.Protection = &v
}

// GetRdAdminField returns the RdAdminField field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *RouterInstance) GetRdAdminField() string {
	if o == nil || IsNil(o.RdAdminField.Get()) {
		var ret string
		return ret
	}
	return *o.RdAdminField.Get()
}

// GetRdAdminFieldOk returns a tuple with the RdAdminField field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *RouterInstance) GetRdAdminFieldOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.RdAdminField.Get(), o.RdAdminField.IsSet()
}

// HasRdAdminField returns a boolean if a field has been set.
func (o *RouterInstance) HasRdAdminField() bool {
	if o != nil && o.RdAdminField.IsSet() {
		return true
	}

	return false
}

// SetRdAdminField gets a reference to the given NullableString and assigns it to the RdAdminField field.
func (o *RouterInstance) SetRdAdminField(v string) {
	o.RdAdminField.Set(&v)
}

// SetRdAdminFieldNil sets the value for RdAdminField to be an explicit nil
func (o *RouterInstance) SetRdAdminFieldNil() {
	o.RdAdminField.Set(nil)
}

// UnsetRdAdminField ensures that no value is present for RdAdminField, not even an explicit nil
func (o *RouterInstance) UnsetRdAdminField() {
	o.RdAdminField.Unset()
}

// GetResourceType returns the ResourceType field value if set, zero value otherwise.
func (o *RouterInstance) GetResourceType() ResourceType {
	if o == nil || IsNil(o.ResourceType) {
		var ret ResourceType
		return ret
	}
	return *o.ResourceType
}

// GetResourceTypeOk returns a tuple with the ResourceType field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RouterInstance) GetResourceTypeOk() (*ResourceType, bool) {
	if o == nil || IsNil(o.ResourceType) {
		return nil, false
	}
	return o.ResourceType, true
}

// HasResourceType returns a boolean if a field has been set.
func (o *RouterInstance) HasResourceType() bool {
	if o != nil && !IsNil(o.ResourceType) {
		return true
	}

	return false
}

// SetResourceType gets a reference to the given ResourceType and assigns it to the ResourceType field.
func (o *RouterInstance) SetResourceType(v ResourceType) {
	o.ResourceType = &v
}

// GetRevision returns the Revision field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *RouterInstance) GetRevision() int64 {
	if o == nil || IsNil(o.Revision.Get()) {
		var ret int64
		return ret
	}
	return *o.Revision.Get()
}

// GetRevisionOk returns a tuple with the Revision field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *RouterInstance) GetRevisionOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return o.Revision.Get(), o.Revision.IsSet()
}

// HasRevision returns a boolean if a field has been set.
func (o *RouterInstance) HasRevision() bool {
	if o != nil && o.Revision.IsSet() {
		return true
	}

	return false
}

// SetRevision gets a reference to the given NullableInt64 and assigns it to the Revision field.
func (o *RouterInstance) SetRevision(v int64) {
	o.Revision.Set(&v)
}

// SetRevisionNil sets the value for Revision to be an explicit nil
func (o *RouterInstance) SetRevisionNil() {
	o.Revision.Set(nil)
}

// UnsetRevision ensures that no value is present for Revision, not even an explicit nil
func (o *RouterInstance) UnsetRevision() {
	o.Revision.Unset()
}

// GetDhcpConfigPathList returns the DhcpConfigPathList field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *RouterInstance) GetDhcpConfigPathList() []DhcpConfigPath {
	if o == nil {
		var ret []DhcpConfigPath
		return ret
	}
	return o.DhcpConfigPathList
}

// GetDhcpConfigPathListOk returns a tuple with the DhcpConfigPathList field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *RouterInstance) GetDhcpConfigPathListOk() ([]DhcpConfigPath, bool) {
	if o == nil || IsNil(o.DhcpConfigPathList) {
		return nil, false
	}
	return o.DhcpConfigPathList, true
}

// HasDhcpConfigPathList returns a boolean if a field has been set.
func (o *RouterInstance) HasDhcpConfigPathList() bool {
	if o != nil && !IsNil(o.DhcpConfigPathList) {
		return true
	}

	return false
}

// SetDhcpConfigPathList gets a reference to the given []DhcpConfigPath and assigns it to the DhcpConfigPathList field.
func (o *RouterInstance) SetDhcpConfigPathList(v []DhcpConfigPath) {
	o.DhcpConfigPathList = v
}

// GetInternalTransitSubnetList returns the InternalTransitSubnetList field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *RouterInstance) GetInternalTransitSubnetList() []InternalTransitSubnet {
	if o == nil {
		var ret []InternalTransitSubnet
		return ret
	}
	return o.InternalTransitSubnetList
}

// GetInternalTransitSubnetListOk returns a tuple with the InternalTransitSubnetList field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *RouterInstance) GetInternalTransitSubnetListOk() ([]InternalTransitSubnet, bool) {
	if o == nil || IsNil(o.InternalTransitSubnetList) {
		return nil, false
	}
	return o.InternalTransitSubnetList, true
}

// HasInternalTransitSubnetList returns a boolean if a field has been set.
func (o *RouterInstance) HasInternalTransitSubnetList() bool {
	if o != nil && !IsNil(o.InternalTransitSubnetList) {
		return true
	}

	return false
}

// SetInternalTransitSubnetList gets a reference to the given []InternalTransitSubnet and assigns it to the InternalTransitSubnetList field.
func (o *RouterInstance) SetInternalTransitSubnetList(v []InternalTransitSubnet) {
	o.InternalTransitSubnetList = v
}

// GetIp6ProfilePathList returns the Ip6ProfilePathList field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *RouterInstance) GetIp6ProfilePathList() []IP6ProfilePath {
	if o == nil {
		var ret []IP6ProfilePath
		return ret
	}
	return o.Ip6ProfilePathList
}

// GetIp6ProfilePathListOk returns a tuple with the Ip6ProfilePathList field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *RouterInstance) GetIp6ProfilePathListOk() ([]IP6ProfilePath, bool) {
	if o == nil || IsNil(o.Ip6ProfilePathList) {
		return nil, false
	}
	return o.Ip6ProfilePathList, true
}

// HasIp6ProfilePathList returns a boolean if a field has been set.
func (o *RouterInstance) HasIp6ProfilePathList() bool {
	if o != nil && !IsNil(o.Ip6ProfilePathList) {
		return true
	}

	return false
}

// SetIp6ProfilePathList gets a reference to the given []IP6ProfilePath and assigns it to the Ip6ProfilePathList field.
func (o *RouterInstance) SetIp6ProfilePathList(v []IP6ProfilePath) {
	o.Ip6ProfilePathList = v
}

// GetTransitSubnetList returns the TransitSubnetList field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *RouterInstance) GetTransitSubnetList() []TransitSubnet {
	if o == nil {
		var ret []TransitSubnet
		return ret
	}
	return o.TransitSubnetList
}

// GetTransitSubnetListOk returns a tuple with the TransitSubnetList field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *RouterInstance) GetTransitSubnetListOk() ([]TransitSubnet, bool) {
	if o == nil || IsNil(o.TransitSubnetList) {
		return nil, false
	}
	return o.TransitSubnetList, true
}

// HasTransitSubnetList returns a boolean if a field has been set.
func (o *RouterInstance) HasTransitSubnetList() bool {
	if o != nil && !IsNil(o.TransitSubnetList) {
		return true
	}

	return false
}

// SetTransitSubnetList gets a reference to the given []TransitSubnet and assigns it to the TransitSubnetList field.
func (o *RouterInstance) SetTransitSubnetList(v []TransitSubnet) {
	o.TransitSubnetList = v
}

// GetRouteAdvertisementType returns the RouteAdvertisementType field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *RouterInstance) GetRouteAdvertisementType() []string {
	if o == nil {
		var ret []string
		return ret
	}
	return o.RouteAdvertisementType
}

// GetRouteAdvertisementTypeOk returns a tuple with the RouteAdvertisementType field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *RouterInstance) GetRouteAdvertisementTypeOk() ([]string, bool) {
	if o == nil || IsNil(o.RouteAdvertisementType) {
		return nil, false
	}
	return o.RouteAdvertisementType, true
}

// HasRouteAdvertisementType returns a boolean if a field has been set.
func (o *RouterInstance) HasRouteAdvertisementType() bool {
	if o != nil && !IsNil(o.RouteAdvertisementType) {
		return true
	}

	return false
}

// SetRouteAdvertisementType gets a reference to the given []string and assigns it to the RouteAdvertisementType field.
func (o *RouterInstance) SetRouteAdvertisementType(v []string) {
	o.RouteAdvertisementType = v
}

// GetSchemaValue returns the SchemaValue field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *RouterInstance) GetSchemaValue() string {
	if o == nil || IsNil(o.SchemaValue.Get()) {
		var ret string
		return ret
	}
	return *o.SchemaValue.Get()
}

// GetSchemaValueOk returns a tuple with the SchemaValue field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *RouterInstance) GetSchemaValueOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.SchemaValue.Get(), o.SchemaValue.IsSet()
}

// HasSchemaValue returns a boolean if a field has been set.
func (o *RouterInstance) HasSchemaValue() bool {
	if o != nil && o.SchemaValue.IsSet() {
		return true
	}

	return false
}

// SetSchemaValue gets a reference to the given NullableString and assigns it to the SchemaValue field.
func (o *RouterInstance) SetSchemaValue(v string) {
	o.SchemaValue.Set(&v)
}

// SetSchemaValueNil sets the value for SchemaValue to be an explicit nil
func (o *RouterInstance) SetSchemaValueNil() {
	o.SchemaValue.Set(nil)
}

// UnsetSchemaValue ensures that no value is present for SchemaValue, not even an explicit nil
func (o *RouterInstance) UnsetSchemaValue() {
	o.SchemaValue.Unset()
}

// GetCreatedBy returns the CreatedBy field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *RouterInstance) GetCreatedBy() string {
	if o == nil || IsNil(o.CreatedBy.Get()) {
		var ret string
		return ret
	}
	return *o.CreatedBy.Get()
}

// GetCreatedByOk returns a tuple with the CreatedBy field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *RouterInstance) GetCreatedByOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.CreatedBy.Get(), o.CreatedBy.IsSet()
}

// HasCreatedBy returns a boolean if a field has been set.
func (o *RouterInstance) HasCreatedBy() bool {
	if o != nil && o.CreatedBy.IsSet() {
		return true
	}

	return false
}

// SetCreatedBy gets a reference to the given NullableString and assigns it to the CreatedBy field.
func (o *RouterInstance) SetCreatedBy(v string) {
	o.CreatedBy.Set(&v)
}

// SetCreatedByNil sets the value for CreatedBy to be an explicit nil
func (o *RouterInstance) SetCreatedByNil() {
	o.CreatedBy.Set(nil)
}

// UnsetCreatedBy ensures that no value is present for CreatedBy, not even an explicit nil
func (o *RouterInstance) UnsetCreatedBy() {
	o.CreatedBy.Unset()
}

// GetCreationDate returns the CreationDate field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *RouterInstance) GetCreationDate() string {
	if o == nil || IsNil(o.CreationDate.Get()) {
		var ret string
		return ret
	}
	return *o.CreationDate.Get()
}

// GetCreationDateOk returns a tuple with the CreationDate field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *RouterInstance) GetCreationDateOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.CreationDate.Get(), o.CreationDate.IsSet()
}

// HasCreationDate returns a boolean if a field has been set.
func (o *RouterInstance) HasCreationDate() bool {
	if o != nil && o.CreationDate.IsSet() {
		return true
	}

	return false
}

// SetCreationDate gets a reference to the given NullableString and assigns it to the CreationDate field.
func (o *RouterInstance) SetCreationDate(v string) {
	o.CreationDate.Set(&v)
}

// SetCreationDateNil sets the value for CreationDate to be an explicit nil
func (o *RouterInstance) SetCreationDateNil() {
	o.CreationDate.Set(nil)
}

// UnsetCreationDate ensures that no value is present for CreationDate, not even an explicit nil
func (o *RouterInstance) UnsetCreationDate() {
	o.CreationDate.Unset()
}

// GetModifiedBy returns the ModifiedBy field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *RouterInstance) GetModifiedBy() string {
	if o == nil || IsNil(o.ModifiedBy.Get()) {
		var ret string
		return ret
	}
	return *o.ModifiedBy.Get()
}

// GetModifiedByOk returns a tuple with the ModifiedBy field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *RouterInstance) GetModifiedByOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.ModifiedBy.Get(), o.ModifiedBy.IsSet()
}

// HasModifiedBy returns a boolean if a field has been set.
func (o *RouterInstance) HasModifiedBy() bool {
	if o != nil && o.ModifiedBy.IsSet() {
		return true
	}

	return false
}

// SetModifiedBy gets a reference to the given NullableString and assigns it to the ModifiedBy field.
func (o *RouterInstance) SetModifiedBy(v string) {
	o.ModifiedBy.Set(&v)
}

// SetModifiedByNil sets the value for ModifiedBy to be an explicit nil
func (o *RouterInstance) SetModifiedByNil() {
	o.ModifiedBy.Set(nil)
}

// UnsetModifiedBy ensures that no value is present for ModifiedBy, not even an explicit nil
func (o *RouterInstance) UnsetModifiedBy() {
	o.ModifiedBy.Unset()
}

// GetModificationDate returns the ModificationDate field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *RouterInstance) GetModificationDate() string {
	if o == nil || IsNil(o.ModificationDate.Get()) {
		var ret string
		return ret
	}
	return *o.ModificationDate.Get()
}

// GetModificationDateOk returns a tuple with the ModificationDate field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *RouterInstance) GetModificationDateOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.ModificationDate.Get(), o.ModificationDate.IsSet()
}

// HasModificationDate returns a boolean if a field has been set.
func (o *RouterInstance) HasModificationDate() bool {
	if o != nil && o.ModificationDate.IsSet() {
		return true
	}

	return false
}

// SetModificationDate gets a reference to the given NullableString and assigns it to the ModificationDate field.
func (o *RouterInstance) SetModificationDate(v string) {
	o.ModificationDate.Set(&v)
}

// SetModificationDateNil sets the value for ModificationDate to be an explicit nil
func (o *RouterInstance) SetModificationDateNil() {
	o.ModificationDate.Set(nil)
}

// UnsetModificationDate ensures that no value is present for ModificationDate, not even an explicit nil
func (o *RouterInstance) UnsetModificationDate() {
	o.ModificationDate.Unset()
}

// GetEdgeClusterInstance returns the EdgeClusterInstance field value if set, zero value otherwise.
func (o *RouterInstance) GetEdgeClusterInstance() EdgeClusterInstance {
	if o == nil || IsNil(o.EdgeClusterInstance) {
		var ret EdgeClusterInstance
		return ret
	}
	return *o.EdgeClusterInstance
}

// GetEdgeClusterInstanceOk returns a tuple with the EdgeClusterInstance field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RouterInstance) GetEdgeClusterInstanceOk() (*EdgeClusterInstance, bool) {
	if o == nil || IsNil(o.EdgeClusterInstance) {
		return nil, false
	}
	return o.EdgeClusterInstance, true
}

// HasEdgeClusterInstance returns a boolean if a field has been set.
func (o *RouterInstance) HasEdgeClusterInstance() bool {
	if o != nil && !IsNil(o.EdgeClusterInstance) {
		return true
	}

	return false
}

// SetEdgeClusterInstance gets a reference to the given EdgeClusterInstance and assigns it to the EdgeClusterInstance field.
func (o *RouterInstance) SetEdgeClusterInstance(v EdgeClusterInstance) {
	o.EdgeClusterInstance = &v
}

// GetTier0Path returns the Tier0Path field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *RouterInstance) GetTier0Path() string {
	if o == nil || IsNil(o.Tier0Path.Get()) {
		var ret string
		return ret
	}
	return *o.Tier0Path.Get()
}

// GetTier0PathOk returns a tuple with the Tier0Path field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *RouterInstance) GetTier0PathOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Tier0Path.Get(), o.Tier0Path.IsSet()
}

// HasTier0Path returns a boolean if a field has been set.
func (o *RouterInstance) HasTier0Path() bool {
	if o != nil && o.Tier0Path.IsSet() {
		return true
	}

	return false
}

// SetTier0Path gets a reference to the given NullableString and assigns it to the Tier0Path field.
func (o *RouterInstance) SetTier0Path(v string) {
	o.Tier0Path.Set(&v)
}

// SetTier0PathNil sets the value for Tier0Path to be an explicit nil
func (o *RouterInstance) SetTier0PathNil() {
	o.Tier0Path.Set(nil)
}

// UnsetTier0Path ensures that no value is present for Tier0Path, not even an explicit nil
func (o *RouterInstance) UnsetTier0Path() {
	o.Tier0Path.Unset()
}

// GetParentT0Id returns the ParentT0Id field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *RouterInstance) GetParentT0Id() string {
	if o == nil || IsNil(o.ParentT0Id.Get()) {
		var ret string
		return ret
	}
	return *o.ParentT0Id.Get()
}

// GetParentT0IdOk returns a tuple with the ParentT0Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *RouterInstance) GetParentT0IdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.ParentT0Id.Get(), o.ParentT0Id.IsSet()
}

// HasParentT0Id returns a boolean if a field has been set.
func (o *RouterInstance) HasParentT0Id() bool {
	if o != nil && o.ParentT0Id.IsSet() {
		return true
	}

	return false
}

// SetParentT0Id gets a reference to the given NullableString and assigns it to the ParentT0Id field.
func (o *RouterInstance) SetParentT0Id(v string) {
	o.ParentT0Id.Set(&v)
}

// SetParentT0IdNil sets the value for ParentT0Id to be an explicit nil
func (o *RouterInstance) SetParentT0IdNil() {
	o.ParentT0Id.Set(nil)
}

// UnsetParentT0Id ensures that no value is present for ParentT0Id, not even an explicit nil
func (o *RouterInstance) UnsetParentT0Id() {
	o.ParentT0Id.Unset()
}

// GetProjectId returns the ProjectId field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *RouterInstance) GetProjectId() string {
	if o == nil || IsNil(o.ProjectId.Get()) {
		var ret string
		return ret
	}
	return *o.ProjectId.Get()
}

// GetProjectIdOk returns a tuple with the ProjectId field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *RouterInstance) GetProjectIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.ProjectId.Get(), o.ProjectId.IsSet()
}

// HasProjectId returns a boolean if a field has been set.
func (o *RouterInstance) HasProjectId() bool {
	if o != nil && o.ProjectId.IsSet() {
		return true
	}

	return false
}

// SetProjectId gets a reference to the given NullableString and assigns it to the ProjectId field.
func (o *RouterInstance) SetProjectId(v string) {
	o.ProjectId.Set(&v)
}

// SetProjectIdNil sets the value for ProjectId to be an explicit nil
func (o *RouterInstance) SetProjectIdNil() {
	o.ProjectId.Set(nil)
}

// UnsetProjectId ensures that no value is present for ProjectId, not even an explicit nil
func (o *RouterInstance) UnsetProjectId() {
	o.ProjectId.Unset()
}

// GetFolderPath returns the FolderPath field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *RouterInstance) GetFolderPath() string {
	if o == nil || IsNil(o.FolderPath.Get()) {
		var ret string
		return ret
	}
	return *o.FolderPath.Get()
}

// GetFolderPathOk returns a tuple with the FolderPath field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *RouterInstance) GetFolderPathOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.FolderPath.Get(), o.FolderPath.IsSet()
}

// HasFolderPath returns a boolean if a field has been set.
func (o *RouterInstance) HasFolderPath() bool {
	if o != nil && o.FolderPath.IsSet() {
		return true
	}

	return false
}

// SetFolderPath gets a reference to the given NullableString and assigns it to the FolderPath field.
func (o *RouterInstance) SetFolderPath(v string) {
	o.FolderPath.Set(&v)
}

// SetFolderPathNil sets the value for FolderPath to be an explicit nil
func (o *RouterInstance) SetFolderPathNil() {
	o.FolderPath.Set(nil)
}

// UnsetFolderPath ensures that no value is present for FolderPath, not even an explicit nil
func (o *RouterInstance) UnsetFolderPath() {
	o.FolderPath.Unset()
}

// GetSnatEnabled returns the SnatEnabled field value if set, zero value otherwise.
func (o *RouterInstance) GetSnatEnabled() bool {
	if o == nil || IsNil(o.SnatEnabled) {
		var ret bool
		return ret
	}
	return *o.SnatEnabled
}

// GetSnatEnabledOk returns a tuple with the SnatEnabled field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RouterInstance) GetSnatEnabledOk() (*bool, bool) {
	if o == nil || IsNil(o.SnatEnabled) {
		return nil, false
	}
	return o.SnatEnabled, true
}

// HasSnatEnabled returns a boolean if a field has been set.
func (o *RouterInstance) HasSnatEnabled() bool {
	if o != nil && !IsNil(o.SnatEnabled) {
		return true
	}

	return false
}

// SetSnatEnabled gets a reference to the given bool and assigns it to the SnatEnabled field.
func (o *RouterInstance) SetSnatEnabled(v bool) {
	o.SnatEnabled = &v
}

// GetSnatIp returns the SnatIp field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *RouterInstance) GetSnatIp() string {
	if o == nil || IsNil(o.SnatIp.Get()) {
		var ret string
		return ret
	}
	return *o.SnatIp.Get()
}

// GetSnatIpOk returns a tuple with the SnatIp field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *RouterInstance) GetSnatIpOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.SnatIp.Get(), o.SnatIp.IsSet()
}

// HasSnatIp returns a boolean if a field has been set.
func (o *RouterInstance) HasSnatIp() bool {
	if o != nil && o.SnatIp.IsSet() {
		return true
	}

	return false
}

// SetSnatIp gets a reference to the given NullableString and assigns it to the SnatIp field.
func (o *RouterInstance) SetSnatIp(v string) {
	o.SnatIp.Set(&v)
}

// SetSnatIpNil sets the value for SnatIp to be an explicit nil
func (o *RouterInstance) SetSnatIpNil() {
	o.SnatIp.Set(nil)
}

// UnsetSnatIp ensures that no value is present for SnatIp, not even an explicit nil
func (o *RouterInstance) UnsetSnatIp() {
	o.SnatIp.Unset()
}

func (o RouterInstance) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if o.RouterId.IsSet() {
		toSerialize["routerId"] = o.RouterId.Get()
	}
	if o.ExternalId.IsSet() {
		toSerialize["externalId"] = o.ExternalId.Get()
	}
	if !IsNil(o.RouterType) {
		toSerialize["routerType"] = o.RouterType
	}
	if o.DisplayName.IsSet() {
		toSerialize["displayName"] = o.DisplayName.Get()
	}
	if o.DefaultRuleLogging.IsSet() {
		toSerialize["defaultRuleLogging"] = o.DefaultRuleLogging.Get()
	}
	if o.Description.IsSet() {
		toSerialize["description"] = o.Description.Get()
	}
	if o.DisableFirewall.IsSet() {
		toSerialize["disableFirewall"] = o.DisableFirewall.Get()
	}
	if !IsNil(o.FailoverMode) {
		toSerialize["failoverMode"] = o.FailoverMode
	}
	if o.ForceWithListing.IsSet() {
		toSerialize["forceWithListing"] = o.ForceWithListing.Get()
	}
	if !IsNil(o.HaMode) {
		toSerialize["haMode"] = o.HaMode
	}
	if o.Overridden.IsSet() {
		toSerialize["overridden"] = o.Overridden.Get()
	}
	if o.ParentPath.IsSet() {
		toSerialize["parentPath"] = o.ParentPath.Get()
	}
	if o.Path.IsSet() {
		toSerialize["path"] = o.Path.Get()
	}
	if o.RelativePath.IsSet() {
		toSerialize["relativePath"] = o.RelativePath.Get()
	}
	if !IsNil(o.Protection) {
		toSerialize["protection"] = o.Protection
	}
	if o.RdAdminField.IsSet() {
		toSerialize["rdAdminField"] = o.RdAdminField.Get()
	}
	if !IsNil(o.ResourceType) {
		toSerialize["resourceType"] = o.ResourceType
	}
	if o.Revision.IsSet() {
		toSerialize["revision"] = o.Revision.Get()
	}
	if o.DhcpConfigPathList != nil {
		toSerialize["dhcpConfigPathList"] = o.DhcpConfigPathList
	}
	if o.InternalTransitSubnetList != nil {
		toSerialize["internalTransitSubnetList"] = o.InternalTransitSubnetList
	}
	if o.Ip6ProfilePathList != nil {
		toSerialize["ip6ProfilePathList"] = o.Ip6ProfilePathList
	}
	if o.TransitSubnetList != nil {
		toSerialize["transitSubnetList"] = o.TransitSubnetList
	}
	if o.RouteAdvertisementType != nil {
		toSerialize["routeAdvertisementType"] = o.RouteAdvertisementType
	}
	if o.SchemaValue.IsSet() {
		toSerialize["schemaValue"] = o.SchemaValue.Get()
	}
	if o.CreatedBy.IsSet() {
		toSerialize["createdBy"] = o.CreatedBy.Get()
	}
	if o.CreationDate.IsSet() {
		toSerialize["creationDate"] = o.CreationDate.Get()
	}
	if o.ModifiedBy.IsSet() {
		toSerialize["modifiedBy"] = o.ModifiedBy.Get()
	}
	if o.ModificationDate.IsSet() {
		toSerialize["modificationDate"] = o.ModificationDate.Get()
	}
	if !IsNil(o.EdgeClusterInstance) {
		toSerialize["edgeClusterInstance"] = o.EdgeClusterInstance
	}
	if o.Tier0Path.IsSet() {
		toSerialize["tier0Path"] = o.Tier0Path.Get()
	}
	if o.ParentT0Id.IsSet() {
		toSerialize["parentT0Id"] = o.ParentT0Id.Get()
	}
	if o.ProjectId.IsSet() {
		toSerialize["projectId"] = o.ProjectId.Get()
	}
	if o.FolderPath.IsSet() {
		toSerialize["folderPath"] = o.FolderPath.Get()
	}
	if !IsNil(o.SnatEnabled) {
		toSerialize["snatEnabled"] = o.SnatEnabled
	}
	if o.SnatIp.IsSet() {
		toSerialize["snatIp"] = o.SnatIp.Get()
	}
	return toSerialize, nil
}

type NullableRouterInstance struct {
	value *RouterInstance
	isSet bool
}

func (v NullableRouterInstance) Get() *RouterInstance {
	return v.value
}

func (v *NullableRouterInstance) Set(val *RouterInstance) {
	v.value = val
	v.isSet = true
}

func (v NullableRouterInstance) IsSet() bool {
	return v.isSet
}

func (v *NullableRouterInstance) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableRouterInstance(val *RouterInstance) *NullableRouterInstance {
	return &NullableRouterInstance{value: val, isSet: true}
}

func (v NullableRouterInstance) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableRouterInstance) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
