/*
Platforma OChK - Proxy API

Platforma OChK - Proxy API

API version: v1
Contact: pomoc@ochk.pl
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"time"
)

// checks if the GetPublicIpAllocationResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetPublicIpAllocationResponse{}

// GetPublicIpAllocationResponse struct for GetPublicIpAllocationResponse
type GetPublicIpAllocationResponse struct {
	ErrorCode          NullableInt32       `json:"errorCode,omitempty"`
	Messages           NullableString      `json:"messages,omitempty"`
	Success            *bool               `json:"success,omitempty"`
	Timestamp          *time.Time          `json:"timestamp,omitempty"`
	PublicIpAllocation *PublicIpAllocation `json:"publicIpAllocation,omitempty"`
}

// NewGetPublicIpAllocationResponse instantiates a new GetPublicIpAllocationResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetPublicIpAllocationResponse() *GetPublicIpAllocationResponse {
	this := GetPublicIpAllocationResponse{}
	return &this
}

// NewGetPublicIpAllocationResponseWithDefaults instantiates a new GetPublicIpAllocationResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetPublicIpAllocationResponseWithDefaults() *GetPublicIpAllocationResponse {
	this := GetPublicIpAllocationResponse{}
	return &this
}

// GetErrorCode returns the ErrorCode field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *GetPublicIpAllocationResponse) GetErrorCode() int32 {
	if o == nil || IsNil(o.ErrorCode.Get()) {
		var ret int32
		return ret
	}
	return *o.ErrorCode.Get()
}

// GetErrorCodeOk returns a tuple with the ErrorCode field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *GetPublicIpAllocationResponse) GetErrorCodeOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return o.ErrorCode.Get(), o.ErrorCode.IsSet()
}

// HasErrorCode returns a boolean if a field has been set.
func (o *GetPublicIpAllocationResponse) HasErrorCode() bool {
	if o != nil && o.ErrorCode.IsSet() {
		return true
	}

	return false
}

// SetErrorCode gets a reference to the given NullableInt32 and assigns it to the ErrorCode field.
func (o *GetPublicIpAllocationResponse) SetErrorCode(v int32) {
	o.ErrorCode.Set(&v)
}

// SetErrorCodeNil sets the value for ErrorCode to be an explicit nil
func (o *GetPublicIpAllocationResponse) SetErrorCodeNil() {
	o.ErrorCode.Set(nil)
}

// UnsetErrorCode ensures that no value is present for ErrorCode, not even an explicit nil
func (o *GetPublicIpAllocationResponse) UnsetErrorCode() {
	o.ErrorCode.Unset()
}

// GetMessages returns the Messages field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *GetPublicIpAllocationResponse) GetMessages() string {
	if o == nil || IsNil(o.Messages.Get()) {
		var ret string
		return ret
	}
	return *o.Messages.Get()
}

// GetMessagesOk returns a tuple with the Messages field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *GetPublicIpAllocationResponse) GetMessagesOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Messages.Get(), o.Messages.IsSet()
}

// HasMessages returns a boolean if a field has been set.
func (o *GetPublicIpAllocationResponse) HasMessages() bool {
	if o != nil && o.Messages.IsSet() {
		return true
	}

	return false
}

// SetMessages gets a reference to the given NullableString and assigns it to the Messages field.
func (o *GetPublicIpAllocationResponse) SetMessages(v string) {
	o.Messages.Set(&v)
}

// SetMessagesNil sets the value for Messages to be an explicit nil
func (o *GetPublicIpAllocationResponse) SetMessagesNil() {
	o.Messages.Set(nil)
}

// UnsetMessages ensures that no value is present for Messages, not even an explicit nil
func (o *GetPublicIpAllocationResponse) UnsetMessages() {
	o.Messages.Unset()
}

// GetSuccess returns the Success field value if set, zero value otherwise.
func (o *GetPublicIpAllocationResponse) GetSuccess() bool {
	if o == nil || IsNil(o.Success) {
		var ret bool
		return ret
	}
	return *o.Success
}

// GetSuccessOk returns a tuple with the Success field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetPublicIpAllocationResponse) GetSuccessOk() (*bool, bool) {
	if o == nil || IsNil(o.Success) {
		return nil, false
	}
	return o.Success, true
}

// HasSuccess returns a boolean if a field has been set.
func (o *GetPublicIpAllocationResponse) HasSuccess() bool {
	if o != nil && !IsNil(o.Success) {
		return true
	}

	return false
}

// SetSuccess gets a reference to the given bool and assigns it to the Success field.
func (o *GetPublicIpAllocationResponse) SetSuccess(v bool) {
	o.Success = &v
}

// GetTimestamp returns the Timestamp field value if set, zero value otherwise.
func (o *GetPublicIpAllocationResponse) GetTimestamp() time.Time {
	if o == nil || IsNil(o.Timestamp) {
		var ret time.Time
		return ret
	}
	return *o.Timestamp
}

// GetTimestampOk returns a tuple with the Timestamp field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetPublicIpAllocationResponse) GetTimestampOk() (*time.Time, bool) {
	if o == nil || IsNil(o.Timestamp) {
		return nil, false
	}
	return o.Timestamp, true
}

// HasTimestamp returns a boolean if a field has been set.
func (o *GetPublicIpAllocationResponse) HasTimestamp() bool {
	if o != nil && !IsNil(o.Timestamp) {
		return true
	}

	return false
}

// SetTimestamp gets a reference to the given time.Time and assigns it to the Timestamp field.
func (o *GetPublicIpAllocationResponse) SetTimestamp(v time.Time) {
	o.Timestamp = &v
}

// GetPublicIpAllocation returns the PublicIpAllocation field value if set, zero value otherwise.
func (o *GetPublicIpAllocationResponse) GetPublicIpAllocation() PublicIpAllocation {
	if o == nil || IsNil(o.PublicIpAllocation) {
		var ret PublicIpAllocation
		return ret
	}
	return *o.PublicIpAllocation
}

// GetPublicIpAllocationOk returns a tuple with the PublicIpAllocation field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetPublicIpAllocationResponse) GetPublicIpAllocationOk() (*PublicIpAllocation, bool) {
	if o == nil || IsNil(o.PublicIpAllocation) {
		return nil, false
	}
	return o.PublicIpAllocation, true
}

// HasPublicIpAllocation returns a boolean if a field has been set.
func (o *GetPublicIpAllocationResponse) HasPublicIpAllocation() bool {
	if o != nil && !IsNil(o.PublicIpAllocation) {
		return true
	}

	return false
}

// SetPublicIpAllocation gets a reference to the given PublicIpAllocation and assigns it to the PublicIpAllocation field.
func (o *GetPublicIpAllocationResponse) SetPublicIpAllocation(v PublicIpAllocation) {
	o.PublicIpAllocation = &v
}

func (o GetPublicIpAllocationResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if o.ErrorCode.IsSet() {
		toSerialize["errorCode"] = o.ErrorCode.Get()
	}
	if o.Messages.IsSet() {
		toSerialize["messages"] = o.Messages.Get()
	}
	if !IsNil(o.Success) {
		toSerialize["success"] = o.Success
	}
	if !IsNil(o.Timestamp) {
		toSerialize["timestamp"] = o.Timestamp
	}
	if !IsNil(o.PublicIpAllocation) {
		toSerialize["publicIpAllocation"] = o.PublicIpAllocation
	}
	return toSerialize, nil
}

type NullableGetPublicIpAllocationResponse struct {
	value *GetPublicIpAllocationResponse
	isSet bool
}

func (v NullableGetPublicIpAllocationResponse) Get() *GetPublicIpAllocationResponse {
	return v.value
}

func (v *NullableGetPublicIpAllocationResponse) Set(val *GetPublicIpAllocationResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableGetPublicIpAllocationResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableGetPublicIpAllocationResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetPublicIpAllocationResponse(val *GetPublicIpAllocationResponse) *NullableGetPublicIpAllocationResponse {
	return &NullableGetPublicIpAllocationResponse{value: val, isSet: true}
}

func (v NullableGetPublicIpAllocationResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetPublicIpAllocationResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
