/*
Platforma OChK - Proxy API

Platforma OChK - Proxy API

API version: v1
Contact: pomoc@ochk.pl
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the L4PortSetEntry type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &L4PortSetEntry{}

// L4PortSetEntry struct for L4PortSetEntry
type L4PortSetEntry struct {
	L4PortSetEntryId NullableString `json:"l4PortSetEntryId,omitempty"`
	ExternalId       NullableString `json:"externalId,omitempty"`
	DisplayName      NullableString `json:"displayName,omitempty"`
	Description      NullableString `json:"description,omitempty"`
	Path             NullableString `json:"path,omitempty"`
	ParentPath       NullableString `json:"parentPath,omitempty"`
	RelativePath     NullableString `json:"relativePath,omitempty"`
	ResourceType     *ResourceType  `json:"resourceType,omitempty"`
	L4Protocol       *L4Protocol    `json:"l4Protocol,omitempty"`
	SourcePorts      []string       `json:"sourcePorts,omitempty"`
	DestinationPorts []string       `json:"destinationPorts,omitempty"`
}

// NewL4PortSetEntry instantiates a new L4PortSetEntry object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewL4PortSetEntry() *L4PortSetEntry {
	this := L4PortSetEntry{}
	return &this
}

// NewL4PortSetEntryWithDefaults instantiates a new L4PortSetEntry object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewL4PortSetEntryWithDefaults() *L4PortSetEntry {
	this := L4PortSetEntry{}
	return &this
}

// GetL4PortSetEntryId returns the L4PortSetEntryId field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *L4PortSetEntry) GetL4PortSetEntryId() string {
	if o == nil || IsNil(o.L4PortSetEntryId.Get()) {
		var ret string
		return ret
	}
	return *o.L4PortSetEntryId.Get()
}

// GetL4PortSetEntryIdOk returns a tuple with the L4PortSetEntryId field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *L4PortSetEntry) GetL4PortSetEntryIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.L4PortSetEntryId.Get(), o.L4PortSetEntryId.IsSet()
}

// HasL4PortSetEntryId returns a boolean if a field has been set.
func (o *L4PortSetEntry) HasL4PortSetEntryId() bool {
	if o != nil && o.L4PortSetEntryId.IsSet() {
		return true
	}

	return false
}

// SetL4PortSetEntryId gets a reference to the given NullableString and assigns it to the L4PortSetEntryId field.
func (o *L4PortSetEntry) SetL4PortSetEntryId(v string) {
	o.L4PortSetEntryId.Set(&v)
}

// SetL4PortSetEntryIdNil sets the value for L4PortSetEntryId to be an explicit nil
func (o *L4PortSetEntry) SetL4PortSetEntryIdNil() {
	o.L4PortSetEntryId.Set(nil)
}

// UnsetL4PortSetEntryId ensures that no value is present for L4PortSetEntryId, not even an explicit nil
func (o *L4PortSetEntry) UnsetL4PortSetEntryId() {
	o.L4PortSetEntryId.Unset()
}

// GetExternalId returns the ExternalId field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *L4PortSetEntry) GetExternalId() string {
	if o == nil || IsNil(o.ExternalId.Get()) {
		var ret string
		return ret
	}
	return *o.ExternalId.Get()
}

// GetExternalIdOk returns a tuple with the ExternalId field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *L4PortSetEntry) GetExternalIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.ExternalId.Get(), o.ExternalId.IsSet()
}

// HasExternalId returns a boolean if a field has been set.
func (o *L4PortSetEntry) HasExternalId() bool {
	if o != nil && o.ExternalId.IsSet() {
		return true
	}

	return false
}

// SetExternalId gets a reference to the given NullableString and assigns it to the ExternalId field.
func (o *L4PortSetEntry) SetExternalId(v string) {
	o.ExternalId.Set(&v)
}

// SetExternalIdNil sets the value for ExternalId to be an explicit nil
func (o *L4PortSetEntry) SetExternalIdNil() {
	o.ExternalId.Set(nil)
}

// UnsetExternalId ensures that no value is present for ExternalId, not even an explicit nil
func (o *L4PortSetEntry) UnsetExternalId() {
	o.ExternalId.Unset()
}

// GetDisplayName returns the DisplayName field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *L4PortSetEntry) GetDisplayName() string {
	if o == nil || IsNil(o.DisplayName.Get()) {
		var ret string
		return ret
	}
	return *o.DisplayName.Get()
}

// GetDisplayNameOk returns a tuple with the DisplayName field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *L4PortSetEntry) GetDisplayNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.DisplayName.Get(), o.DisplayName.IsSet()
}

// HasDisplayName returns a boolean if a field has been set.
func (o *L4PortSetEntry) HasDisplayName() bool {
	if o != nil && o.DisplayName.IsSet() {
		return true
	}

	return false
}

// SetDisplayName gets a reference to the given NullableString and assigns it to the DisplayName field.
func (o *L4PortSetEntry) SetDisplayName(v string) {
	o.DisplayName.Set(&v)
}

// SetDisplayNameNil sets the value for DisplayName to be an explicit nil
func (o *L4PortSetEntry) SetDisplayNameNil() {
	o.DisplayName.Set(nil)
}

// UnsetDisplayName ensures that no value is present for DisplayName, not even an explicit nil
func (o *L4PortSetEntry) UnsetDisplayName() {
	o.DisplayName.Unset()
}

// GetDescription returns the Description field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *L4PortSetEntry) GetDescription() string {
	if o == nil || IsNil(o.Description.Get()) {
		var ret string
		return ret
	}
	return *o.Description.Get()
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *L4PortSetEntry) GetDescriptionOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Description.Get(), o.Description.IsSet()
}

// HasDescription returns a boolean if a field has been set.
func (o *L4PortSetEntry) HasDescription() bool {
	if o != nil && o.Description.IsSet() {
		return true
	}

	return false
}

// SetDescription gets a reference to the given NullableString and assigns it to the Description field.
func (o *L4PortSetEntry) SetDescription(v string) {
	o.Description.Set(&v)
}

// SetDescriptionNil sets the value for Description to be an explicit nil
func (o *L4PortSetEntry) SetDescriptionNil() {
	o.Description.Set(nil)
}

// UnsetDescription ensures that no value is present for Description, not even an explicit nil
func (o *L4PortSetEntry) UnsetDescription() {
	o.Description.Unset()
}

// GetPath returns the Path field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *L4PortSetEntry) GetPath() string {
	if o == nil || IsNil(o.Path.Get()) {
		var ret string
		return ret
	}
	return *o.Path.Get()
}

// GetPathOk returns a tuple with the Path field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *L4PortSetEntry) GetPathOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Path.Get(), o.Path.IsSet()
}

// HasPath returns a boolean if a field has been set.
func (o *L4PortSetEntry) HasPath() bool {
	if o != nil && o.Path.IsSet() {
		return true
	}

	return false
}

// SetPath gets a reference to the given NullableString and assigns it to the Path field.
func (o *L4PortSetEntry) SetPath(v string) {
	o.Path.Set(&v)
}

// SetPathNil sets the value for Path to be an explicit nil
func (o *L4PortSetEntry) SetPathNil() {
	o.Path.Set(nil)
}

// UnsetPath ensures that no value is present for Path, not even an explicit nil
func (o *L4PortSetEntry) UnsetPath() {
	o.Path.Unset()
}

// GetParentPath returns the ParentPath field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *L4PortSetEntry) GetParentPath() string {
	if o == nil || IsNil(o.ParentPath.Get()) {
		var ret string
		return ret
	}
	return *o.ParentPath.Get()
}

// GetParentPathOk returns a tuple with the ParentPath field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *L4PortSetEntry) GetParentPathOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.ParentPath.Get(), o.ParentPath.IsSet()
}

// HasParentPath returns a boolean if a field has been set.
func (o *L4PortSetEntry) HasParentPath() bool {
	if o != nil && o.ParentPath.IsSet() {
		return true
	}

	return false
}

// SetParentPath gets a reference to the given NullableString and assigns it to the ParentPath field.
func (o *L4PortSetEntry) SetParentPath(v string) {
	o.ParentPath.Set(&v)
}

// SetParentPathNil sets the value for ParentPath to be an explicit nil
func (o *L4PortSetEntry) SetParentPathNil() {
	o.ParentPath.Set(nil)
}

// UnsetParentPath ensures that no value is present for ParentPath, not even an explicit nil
func (o *L4PortSetEntry) UnsetParentPath() {
	o.ParentPath.Unset()
}

// GetRelativePath returns the RelativePath field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *L4PortSetEntry) GetRelativePath() string {
	if o == nil || IsNil(o.RelativePath.Get()) {
		var ret string
		return ret
	}
	return *o.RelativePath.Get()
}

// GetRelativePathOk returns a tuple with the RelativePath field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *L4PortSetEntry) GetRelativePathOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.RelativePath.Get(), o.RelativePath.IsSet()
}

// HasRelativePath returns a boolean if a field has been set.
func (o *L4PortSetEntry) HasRelativePath() bool {
	if o != nil && o.RelativePath.IsSet() {
		return true
	}

	return false
}

// SetRelativePath gets a reference to the given NullableString and assigns it to the RelativePath field.
func (o *L4PortSetEntry) SetRelativePath(v string) {
	o.RelativePath.Set(&v)
}

// SetRelativePathNil sets the value for RelativePath to be an explicit nil
func (o *L4PortSetEntry) SetRelativePathNil() {
	o.RelativePath.Set(nil)
}

// UnsetRelativePath ensures that no value is present for RelativePath, not even an explicit nil
func (o *L4PortSetEntry) UnsetRelativePath() {
	o.RelativePath.Unset()
}

// GetResourceType returns the ResourceType field value if set, zero value otherwise.
func (o *L4PortSetEntry) GetResourceType() ResourceType {
	if o == nil || IsNil(o.ResourceType) {
		var ret ResourceType
		return ret
	}
	return *o.ResourceType
}

// GetResourceTypeOk returns a tuple with the ResourceType field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *L4PortSetEntry) GetResourceTypeOk() (*ResourceType, bool) {
	if o == nil || IsNil(o.ResourceType) {
		return nil, false
	}
	return o.ResourceType, true
}

// HasResourceType returns a boolean if a field has been set.
func (o *L4PortSetEntry) HasResourceType() bool {
	if o != nil && !IsNil(o.ResourceType) {
		return true
	}

	return false
}

// SetResourceType gets a reference to the given ResourceType and assigns it to the ResourceType field.
func (o *L4PortSetEntry) SetResourceType(v ResourceType) {
	o.ResourceType = &v
}

// GetL4Protocol returns the L4Protocol field value if set, zero value otherwise.
func (o *L4PortSetEntry) GetL4Protocol() L4Protocol {
	if o == nil || IsNil(o.L4Protocol) {
		var ret L4Protocol
		return ret
	}
	return *o.L4Protocol
}

// GetL4ProtocolOk returns a tuple with the L4Protocol field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *L4PortSetEntry) GetL4ProtocolOk() (*L4Protocol, bool) {
	if o == nil || IsNil(o.L4Protocol) {
		return nil, false
	}
	return o.L4Protocol, true
}

// HasL4Protocol returns a boolean if a field has been set.
func (o *L4PortSetEntry) HasL4Protocol() bool {
	if o != nil && !IsNil(o.L4Protocol) {
		return true
	}

	return false
}

// SetL4Protocol gets a reference to the given L4Protocol and assigns it to the L4Protocol field.
func (o *L4PortSetEntry) SetL4Protocol(v L4Protocol) {
	o.L4Protocol = &v
}

// GetSourcePorts returns the SourcePorts field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *L4PortSetEntry) GetSourcePorts() []string {
	if o == nil {
		var ret []string
		return ret
	}
	return o.SourcePorts
}

// GetSourcePortsOk returns a tuple with the SourcePorts field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *L4PortSetEntry) GetSourcePortsOk() ([]string, bool) {
	if o == nil || IsNil(o.SourcePorts) {
		return nil, false
	}
	return o.SourcePorts, true
}

// HasSourcePorts returns a boolean if a field has been set.
func (o *L4PortSetEntry) HasSourcePorts() bool {
	if o != nil && !IsNil(o.SourcePorts) {
		return true
	}

	return false
}

// SetSourcePorts gets a reference to the given []string and assigns it to the SourcePorts field.
func (o *L4PortSetEntry) SetSourcePorts(v []string) {
	o.SourcePorts = v
}

// GetDestinationPorts returns the DestinationPorts field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *L4PortSetEntry) GetDestinationPorts() []string {
	if o == nil {
		var ret []string
		return ret
	}
	return o.DestinationPorts
}

// GetDestinationPortsOk returns a tuple with the DestinationPorts field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *L4PortSetEntry) GetDestinationPortsOk() ([]string, bool) {
	if o == nil || IsNil(o.DestinationPorts) {
		return nil, false
	}
	return o.DestinationPorts, true
}

// HasDestinationPorts returns a boolean if a field has been set.
func (o *L4PortSetEntry) HasDestinationPorts() bool {
	if o != nil && !IsNil(o.DestinationPorts) {
		return true
	}

	return false
}

// SetDestinationPorts gets a reference to the given []string and assigns it to the DestinationPorts field.
func (o *L4PortSetEntry) SetDestinationPorts(v []string) {
	o.DestinationPorts = v
}

func (o L4PortSetEntry) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if o.L4PortSetEntryId.IsSet() {
		toSerialize["l4PortSetEntryId"] = o.L4PortSetEntryId.Get()
	}
	if o.ExternalId.IsSet() {
		toSerialize["externalId"] = o.ExternalId.Get()
	}
	if o.DisplayName.IsSet() {
		toSerialize["displayName"] = o.DisplayName.Get()
	}
	if o.Description.IsSet() {
		toSerialize["description"] = o.Description.Get()
	}
	if o.Path.IsSet() {
		toSerialize["path"] = o.Path.Get()
	}
	if o.ParentPath.IsSet() {
		toSerialize["parentPath"] = o.ParentPath.Get()
	}
	if o.RelativePath.IsSet() {
		toSerialize["relativePath"] = o.RelativePath.Get()
	}
	if !IsNil(o.ResourceType) {
		toSerialize["resourceType"] = o.ResourceType
	}
	if !IsNil(o.L4Protocol) {
		toSerialize["l4Protocol"] = o.L4Protocol
	}
	if o.SourcePorts != nil {
		toSerialize["sourcePorts"] = o.SourcePorts
	}
	if o.DestinationPorts != nil {
		toSerialize["destinationPorts"] = o.DestinationPorts
	}
	return toSerialize, nil
}

type NullableL4PortSetEntry struct {
	value *L4PortSetEntry
	isSet bool
}

func (v NullableL4PortSetEntry) Get() *L4PortSetEntry {
	return v.value
}

func (v *NullableL4PortSetEntry) Set(val *L4PortSetEntry) {
	v.value = val
	v.isSet = true
}

func (v NullableL4PortSetEntry) IsSet() bool {
	return v.isSet
}

func (v *NullableL4PortSetEntry) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableL4PortSetEntry(val *L4PortSetEntry) *NullableL4PortSetEntry {
	return &NullableL4PortSetEntry{value: val, isSet: true}
}

func (v NullableL4PortSetEntry) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableL4PortSetEntry) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
