/*
Platforma OChK - Proxy API

Platforma OChK - Proxy API

API version: v1
Contact: pomoc@ochk.pl
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the Hits type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &Hits{}

// Hits struct for Hits
type Hits struct {
	Total *Total `json:"total,omitempty"`
	Hits  []Hit  `json:"hits,omitempty"`
}

// NewHits instantiates a new Hits object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewHits() *Hits {
	this := Hits{}
	return &this
}

// NewHitsWithDefaults instantiates a new Hits object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewHitsWithDefaults() *Hits {
	this := Hits{}
	return &this
}

// GetTotal returns the Total field value if set, zero value otherwise.
func (o *Hits) GetTotal() Total {
	if o == nil || IsNil(o.Total) {
		var ret Total
		return ret
	}
	return *o.Total
}

// GetTotalOk returns a tuple with the Total field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Hits) GetTotalOk() (*Total, bool) {
	if o == nil || IsNil(o.Total) {
		return nil, false
	}
	return o.Total, true
}

// HasTotal returns a boolean if a field has been set.
func (o *Hits) HasTotal() bool {
	if o != nil && !IsNil(o.Total) {
		return true
	}

	return false
}

// SetTotal gets a reference to the given Total and assigns it to the Total field.
func (o *Hits) SetTotal(v Total) {
	o.Total = &v
}

// GetHits returns the Hits field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *Hits) GetHits() []Hit {
	if o == nil {
		var ret []Hit
		return ret
	}
	return o.Hits
}

// GetHitsOk returns a tuple with the Hits field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *Hits) GetHitsOk() ([]Hit, bool) {
	if o == nil || IsNil(o.Hits) {
		return nil, false
	}
	return o.Hits, true
}

// HasHits returns a boolean if a field has been set.
func (o *Hits) HasHits() bool {
	if o != nil && !IsNil(o.Hits) {
		return true
	}

	return false
}

// SetHits gets a reference to the given []Hit and assigns it to the Hits field.
func (o *Hits) SetHits(v []Hit) {
	o.Hits = v
}

func (o Hits) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Total) {
		toSerialize["total"] = o.Total
	}
	if o.Hits != nil {
		toSerialize["hits"] = o.Hits
	}
	return toSerialize, nil
}

type NullableHits struct {
	value *Hits
	isSet bool
}

func (v NullableHits) Get() *Hits {
	return v.value
}

func (v *NullableHits) Set(val *Hits) {
	v.value = val
	v.isSet = true
}

func (v NullableHits) IsSet() bool {
	return v.isSet
}

func (v *NullableHits) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableHits(val *Hits) *NullableHits {
	return &NullableHits{value: val, isSet: true}
}

func (v NullableHits) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableHits) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
