/*
Platforma OChK - Proxy API

Platforma OChK - Proxy API

API version: v1
Contact: pomoc@ochk.pl
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"time"
)

// checks if the FolderGetResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &FolderGetResponse{}

// FolderGetResponse struct for FolderGetResponse
type FolderGetResponse struct {
	ErrorCode      NullableInt32   `json:"errorCode,omitempty"`
	Messages       NullableString  `json:"messages,omitempty"`
	Success        *bool           `json:"success,omitempty"`
	Timestamp      *time.Time      `json:"timestamp,omitempty"`
	FolderInstance *FolderInstance `json:"folderInstance,omitempty"`
}

// NewFolderGetResponse instantiates a new FolderGetResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewFolderGetResponse() *FolderGetResponse {
	this := FolderGetResponse{}
	return &this
}

// NewFolderGetResponseWithDefaults instantiates a new FolderGetResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewFolderGetResponseWithDefaults() *FolderGetResponse {
	this := FolderGetResponse{}
	return &this
}

// GetErrorCode returns the ErrorCode field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *FolderGetResponse) GetErrorCode() int32 {
	if o == nil || IsNil(o.ErrorCode.Get()) {
		var ret int32
		return ret
	}
	return *o.ErrorCode.Get()
}

// GetErrorCodeOk returns a tuple with the ErrorCode field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *FolderGetResponse) GetErrorCodeOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return o.ErrorCode.Get(), o.ErrorCode.IsSet()
}

// HasErrorCode returns a boolean if a field has been set.
func (o *FolderGetResponse) HasErrorCode() bool {
	if o != nil && o.ErrorCode.IsSet() {
		return true
	}

	return false
}

// SetErrorCode gets a reference to the given NullableInt32 and assigns it to the ErrorCode field.
func (o *FolderGetResponse) SetErrorCode(v int32) {
	o.ErrorCode.Set(&v)
}

// SetErrorCodeNil sets the value for ErrorCode to be an explicit nil
func (o *FolderGetResponse) SetErrorCodeNil() {
	o.ErrorCode.Set(nil)
}

// UnsetErrorCode ensures that no value is present for ErrorCode, not even an explicit nil
func (o *FolderGetResponse) UnsetErrorCode() {
	o.ErrorCode.Unset()
}

// GetMessages returns the Messages field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *FolderGetResponse) GetMessages() string {
	if o == nil || IsNil(o.Messages.Get()) {
		var ret string
		return ret
	}
	return *o.Messages.Get()
}

// GetMessagesOk returns a tuple with the Messages field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *FolderGetResponse) GetMessagesOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Messages.Get(), o.Messages.IsSet()
}

// HasMessages returns a boolean if a field has been set.
func (o *FolderGetResponse) HasMessages() bool {
	if o != nil && o.Messages.IsSet() {
		return true
	}

	return false
}

// SetMessages gets a reference to the given NullableString and assigns it to the Messages field.
func (o *FolderGetResponse) SetMessages(v string) {
	o.Messages.Set(&v)
}

// SetMessagesNil sets the value for Messages to be an explicit nil
func (o *FolderGetResponse) SetMessagesNil() {
	o.Messages.Set(nil)
}

// UnsetMessages ensures that no value is present for Messages, not even an explicit nil
func (o *FolderGetResponse) UnsetMessages() {
	o.Messages.Unset()
}

// GetSuccess returns the Success field value if set, zero value otherwise.
func (o *FolderGetResponse) GetSuccess() bool {
	if o == nil || IsNil(o.Success) {
		var ret bool
		return ret
	}
	return *o.Success
}

// GetSuccessOk returns a tuple with the Success field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FolderGetResponse) GetSuccessOk() (*bool, bool) {
	if o == nil || IsNil(o.Success) {
		return nil, false
	}
	return o.Success, true
}

// HasSuccess returns a boolean if a field has been set.
func (o *FolderGetResponse) HasSuccess() bool {
	if o != nil && !IsNil(o.Success) {
		return true
	}

	return false
}

// SetSuccess gets a reference to the given bool and assigns it to the Success field.
func (o *FolderGetResponse) SetSuccess(v bool) {
	o.Success = &v
}

// GetTimestamp returns the Timestamp field value if set, zero value otherwise.
func (o *FolderGetResponse) GetTimestamp() time.Time {
	if o == nil || IsNil(o.Timestamp) {
		var ret time.Time
		return ret
	}
	return *o.Timestamp
}

// GetTimestampOk returns a tuple with the Timestamp field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FolderGetResponse) GetTimestampOk() (*time.Time, bool) {
	if o == nil || IsNil(o.Timestamp) {
		return nil, false
	}
	return o.Timestamp, true
}

// HasTimestamp returns a boolean if a field has been set.
func (o *FolderGetResponse) HasTimestamp() bool {
	if o != nil && !IsNil(o.Timestamp) {
		return true
	}

	return false
}

// SetTimestamp gets a reference to the given time.Time and assigns it to the Timestamp field.
func (o *FolderGetResponse) SetTimestamp(v time.Time) {
	o.Timestamp = &v
}

// GetFolderInstance returns the FolderInstance field value if set, zero value otherwise.
func (o *FolderGetResponse) GetFolderInstance() FolderInstance {
	if o == nil || IsNil(o.FolderInstance) {
		var ret FolderInstance
		return ret
	}
	return *o.FolderInstance
}

// GetFolderInstanceOk returns a tuple with the FolderInstance field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FolderGetResponse) GetFolderInstanceOk() (*FolderInstance, bool) {
	if o == nil || IsNil(o.FolderInstance) {
		return nil, false
	}
	return o.FolderInstance, true
}

// HasFolderInstance returns a boolean if a field has been set.
func (o *FolderGetResponse) HasFolderInstance() bool {
	if o != nil && !IsNil(o.FolderInstance) {
		return true
	}

	return false
}

// SetFolderInstance gets a reference to the given FolderInstance and assigns it to the FolderInstance field.
func (o *FolderGetResponse) SetFolderInstance(v FolderInstance) {
	o.FolderInstance = &v
}

func (o FolderGetResponse) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o FolderGetResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if o.ErrorCode.IsSet() {
		toSerialize["errorCode"] = o.ErrorCode.Get()
	}
	if o.Messages.IsSet() {
		toSerialize["messages"] = o.Messages.Get()
	}
	if !IsNil(o.Success) {
		toSerialize["success"] = o.Success
	}
	if !IsNil(o.Timestamp) {
		toSerialize["timestamp"] = o.Timestamp
	}
	if !IsNil(o.FolderInstance) {
		toSerialize["folderInstance"] = o.FolderInstance
	}
	return toSerialize, nil
}

type NullableFolderGetResponse struct {
	value *FolderGetResponse
	isSet bool
}

func (v NullableFolderGetResponse) Get() *FolderGetResponse {
	return v.value
}

func (v *NullableFolderGetResponse) Set(val *FolderGetResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableFolderGetResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableFolderGetResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableFolderGetResponse(val *FolderGetResponse) *NullableFolderGetResponse {
	return &NullableFolderGetResponse{value: val, isSet: true}
}

func (v NullableFolderGetResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableFolderGetResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
