/*
Platforma OChK - Proxy API

Platforma OChK - Proxy API

API version: v1
Contact: pomoc@ochk.pl
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the KeyExport type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &KeyExport{}

// KeyExport struct for KeyExport
type KeyExport struct {
	Format        *KeyExportFormat `json:"format,omitempty"`
	WrapPublicKey NullableString   `json:"wrapPublicKey,omitempty"`
}

// NewKeyExport instantiates a new KeyExport object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewKeyExport() *KeyExport {
	this := KeyExport{}
	return &this
}

// NewKeyExportWithDefaults instantiates a new KeyExport object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewKeyExportWithDefaults() *KeyExport {
	this := KeyExport{}
	return &this
}

// GetFormat returns the Format field value if set, zero value otherwise.
func (o *KeyExport) GetFormat() KeyExportFormat {
	if o == nil || IsNil(o.Format) {
		var ret KeyExportFormat
		return ret
	}
	return *o.Format
}

// GetFormatOk returns a tuple with the Format field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *KeyExport) GetFormatOk() (*KeyExportFormat, bool) {
	if o == nil || IsNil(o.Format) {
		return nil, false
	}
	return o.Format, true
}

// HasFormat returns a boolean if a field has been set.
func (o *KeyExport) HasFormat() bool {
	if o != nil && !IsNil(o.Format) {
		return true
	}

	return false
}

// SetFormat gets a reference to the given KeyExportFormat and assigns it to the Format field.
func (o *KeyExport) SetFormat(v KeyExportFormat) {
	o.Format = &v
}

// GetWrapPublicKey returns the WrapPublicKey field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *KeyExport) GetWrapPublicKey() string {
	if o == nil || IsNil(o.WrapPublicKey.Get()) {
		var ret string
		return ret
	}
	return *o.WrapPublicKey.Get()
}

// GetWrapPublicKeyOk returns a tuple with the WrapPublicKey field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *KeyExport) GetWrapPublicKeyOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.WrapPublicKey.Get(), o.WrapPublicKey.IsSet()
}

// HasWrapPublicKey returns a boolean if a field has been set.
func (o *KeyExport) HasWrapPublicKey() bool {
	if o != nil && o.WrapPublicKey.IsSet() {
		return true
	}

	return false
}

// SetWrapPublicKey gets a reference to the given NullableString and assigns it to the WrapPublicKey field.
func (o *KeyExport) SetWrapPublicKey(v string) {
	o.WrapPublicKey.Set(&v)
}

// SetWrapPublicKeyNil sets the value for WrapPublicKey to be an explicit nil
func (o *KeyExport) SetWrapPublicKeyNil() {
	o.WrapPublicKey.Set(nil)
}

// UnsetWrapPublicKey ensures that no value is present for WrapPublicKey, not even an explicit nil
func (o *KeyExport) UnsetWrapPublicKey() {
	o.WrapPublicKey.Unset()
}

func (o KeyExport) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Format) {
		toSerialize["format"] = o.Format
	}
	if o.WrapPublicKey.IsSet() {
		toSerialize["wrapPublicKey"] = o.WrapPublicKey.Get()
	}
	return toSerialize, nil
}

type NullableKeyExport struct {
	value *KeyExport
	isSet bool
}

func (v NullableKeyExport) Get() *KeyExport {
	return v.value
}

func (v *NullableKeyExport) Set(val *KeyExport) {
	v.value = val
	v.isSet = true
}

func (v NullableKeyExport) IsSet() bool {
	return v.isSet
}

func (v *NullableKeyExport) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableKeyExport(val *KeyExport) *NullableKeyExport {
	return &NullableKeyExport{value: val, isSet: true}
}

func (v NullableKeyExport) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableKeyExport) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
