/*
Platforma OChK - Proxy API

Platforma OChK - Proxy API

API version: v1
Contact: pomoc@ochk.pl
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"time"
)

// checks if the Subnet type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &Subnet{}

// Subnet struct for Subnet
type Subnet struct {
	PckId           NullableString   `json:"pckId,omitempty"`
	ExternalId      NullableString   `json:"externalId,omitempty"`
	ProjectId       NullableString   `json:"projectId,omitempty"`
	Name            NullableString   `json:"name,omitempty"`
	Description     NullableString   `json:"description,omitempty"`
	AdminStateUp    NullableBool     `json:"adminStateUp,omitempty"`
	Tags            []string         `json:"tags,omitempty"`
	CreatedAt       NullableTime     `json:"createdAt,omitempty"`
	UpdatedAt       NullableTime     `json:"updatedAt,omitempty"`
	Status          NullableString   `json:"status,omitempty"`
	NetworkId       NullableString   `json:"networkId,omitempty"`
	GatewayIp       NullableString   `json:"gatewayIp,omitempty"`
	NetworkCidr     NullableString   `json:"networkCidr,omitempty"`
	EnableDhcp      NullableBool     `json:"enableDhcp,omitempty"`
	AllocationPools []AllocationPool `json:"allocationPools,omitempty"`
	DnsServers      []string         `json:"dnsServers,omitempty"`
}

// NewSubnet instantiates a new Subnet object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSubnet() *Subnet {
	this := Subnet{}
	return &this
}

// NewSubnetWithDefaults instantiates a new Subnet object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSubnetWithDefaults() *Subnet {
	this := Subnet{}
	return &this
}

// GetPckId returns the PckId field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *Subnet) GetPckId() string {
	if o == nil || IsNil(o.PckId.Get()) {
		var ret string
		return ret
	}
	return *o.PckId.Get()
}

// GetPckIdOk returns a tuple with the PckId field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *Subnet) GetPckIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.PckId.Get(), o.PckId.IsSet()
}

// HasPckId returns a boolean if a field has been set.
func (o *Subnet) HasPckId() bool {
	if o != nil && o.PckId.IsSet() {
		return true
	}

	return false
}

// SetPckId gets a reference to the given NullableString and assigns it to the PckId field.
func (o *Subnet) SetPckId(v string) {
	o.PckId.Set(&v)
}

// SetPckIdNil sets the value for PckId to be an explicit nil
func (o *Subnet) SetPckIdNil() {
	o.PckId.Set(nil)
}

// UnsetPckId ensures that no value is present for PckId, not even an explicit nil
func (o *Subnet) UnsetPckId() {
	o.PckId.Unset()
}

// GetExternalId returns the ExternalId field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *Subnet) GetExternalId() string {
	if o == nil || IsNil(o.ExternalId.Get()) {
		var ret string
		return ret
	}
	return *o.ExternalId.Get()
}

// GetExternalIdOk returns a tuple with the ExternalId field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *Subnet) GetExternalIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.ExternalId.Get(), o.ExternalId.IsSet()
}

// HasExternalId returns a boolean if a field has been set.
func (o *Subnet) HasExternalId() bool {
	if o != nil && o.ExternalId.IsSet() {
		return true
	}

	return false
}

// SetExternalId gets a reference to the given NullableString and assigns it to the ExternalId field.
func (o *Subnet) SetExternalId(v string) {
	o.ExternalId.Set(&v)
}

// SetExternalIdNil sets the value for ExternalId to be an explicit nil
func (o *Subnet) SetExternalIdNil() {
	o.ExternalId.Set(nil)
}

// UnsetExternalId ensures that no value is present for ExternalId, not even an explicit nil
func (o *Subnet) UnsetExternalId() {
	o.ExternalId.Unset()
}

// GetProjectId returns the ProjectId field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *Subnet) GetProjectId() string {
	if o == nil || IsNil(o.ProjectId.Get()) {
		var ret string
		return ret
	}
	return *o.ProjectId.Get()
}

// GetProjectIdOk returns a tuple with the ProjectId field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *Subnet) GetProjectIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.ProjectId.Get(), o.ProjectId.IsSet()
}

// HasProjectId returns a boolean if a field has been set.
func (o *Subnet) HasProjectId() bool {
	if o != nil && o.ProjectId.IsSet() {
		return true
	}

	return false
}

// SetProjectId gets a reference to the given NullableString and assigns it to the ProjectId field.
func (o *Subnet) SetProjectId(v string) {
	o.ProjectId.Set(&v)
}

// SetProjectIdNil sets the value for ProjectId to be an explicit nil
func (o *Subnet) SetProjectIdNil() {
	o.ProjectId.Set(nil)
}

// UnsetProjectId ensures that no value is present for ProjectId, not even an explicit nil
func (o *Subnet) UnsetProjectId() {
	o.ProjectId.Unset()
}

// GetName returns the Name field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *Subnet) GetName() string {
	if o == nil || IsNil(o.Name.Get()) {
		var ret string
		return ret
	}
	return *o.Name.Get()
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *Subnet) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Name.Get(), o.Name.IsSet()
}

// HasName returns a boolean if a field has been set.
func (o *Subnet) HasName() bool {
	if o != nil && o.Name.IsSet() {
		return true
	}

	return false
}

// SetName gets a reference to the given NullableString and assigns it to the Name field.
func (o *Subnet) SetName(v string) {
	o.Name.Set(&v)
}

// SetNameNil sets the value for Name to be an explicit nil
func (o *Subnet) SetNameNil() {
	o.Name.Set(nil)
}

// UnsetName ensures that no value is present for Name, not even an explicit nil
func (o *Subnet) UnsetName() {
	o.Name.Unset()
}

// GetDescription returns the Description field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *Subnet) GetDescription() string {
	if o == nil || IsNil(o.Description.Get()) {
		var ret string
		return ret
	}
	return *o.Description.Get()
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *Subnet) GetDescriptionOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Description.Get(), o.Description.IsSet()
}

// HasDescription returns a boolean if a field has been set.
func (o *Subnet) HasDescription() bool {
	if o != nil && o.Description.IsSet() {
		return true
	}

	return false
}

// SetDescription gets a reference to the given NullableString and assigns it to the Description field.
func (o *Subnet) SetDescription(v string) {
	o.Description.Set(&v)
}

// SetDescriptionNil sets the value for Description to be an explicit nil
func (o *Subnet) SetDescriptionNil() {
	o.Description.Set(nil)
}

// UnsetDescription ensures that no value is present for Description, not even an explicit nil
func (o *Subnet) UnsetDescription() {
	o.Description.Unset()
}

// GetAdminStateUp returns the AdminStateUp field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *Subnet) GetAdminStateUp() bool {
	if o == nil || IsNil(o.AdminStateUp.Get()) {
		var ret bool
		return ret
	}
	return *o.AdminStateUp.Get()
}

// GetAdminStateUpOk returns a tuple with the AdminStateUp field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *Subnet) GetAdminStateUpOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return o.AdminStateUp.Get(), o.AdminStateUp.IsSet()
}

// HasAdminStateUp returns a boolean if a field has been set.
func (o *Subnet) HasAdminStateUp() bool {
	if o != nil && o.AdminStateUp.IsSet() {
		return true
	}

	return false
}

// SetAdminStateUp gets a reference to the given NullableBool and assigns it to the AdminStateUp field.
func (o *Subnet) SetAdminStateUp(v bool) {
	o.AdminStateUp.Set(&v)
}

// SetAdminStateUpNil sets the value for AdminStateUp to be an explicit nil
func (o *Subnet) SetAdminStateUpNil() {
	o.AdminStateUp.Set(nil)
}

// UnsetAdminStateUp ensures that no value is present for AdminStateUp, not even an explicit nil
func (o *Subnet) UnsetAdminStateUp() {
	o.AdminStateUp.Unset()
}

// GetTags returns the Tags field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *Subnet) GetTags() []string {
	if o == nil {
		var ret []string
		return ret
	}
	return o.Tags
}

// GetTagsOk returns a tuple with the Tags field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *Subnet) GetTagsOk() ([]string, bool) {
	if o == nil || IsNil(o.Tags) {
		return nil, false
	}
	return o.Tags, true
}

// HasTags returns a boolean if a field has been set.
func (o *Subnet) HasTags() bool {
	if o != nil && !IsNil(o.Tags) {
		return true
	}

	return false
}

// SetTags gets a reference to the given []string and assigns it to the Tags field.
func (o *Subnet) SetTags(v []string) {
	o.Tags = v
}

// GetCreatedAt returns the CreatedAt field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *Subnet) GetCreatedAt() time.Time {
	if o == nil || IsNil(o.CreatedAt.Get()) {
		var ret time.Time
		return ret
	}
	return *o.CreatedAt.Get()
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *Subnet) GetCreatedAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return o.CreatedAt.Get(), o.CreatedAt.IsSet()
}

// HasCreatedAt returns a boolean if a field has been set.
func (o *Subnet) HasCreatedAt() bool {
	if o != nil && o.CreatedAt.IsSet() {
		return true
	}

	return false
}

// SetCreatedAt gets a reference to the given NullableTime and assigns it to the CreatedAt field.
func (o *Subnet) SetCreatedAt(v time.Time) {
	o.CreatedAt.Set(&v)
}

// SetCreatedAtNil sets the value for CreatedAt to be an explicit nil
func (o *Subnet) SetCreatedAtNil() {
	o.CreatedAt.Set(nil)
}

// UnsetCreatedAt ensures that no value is present for CreatedAt, not even an explicit nil
func (o *Subnet) UnsetCreatedAt() {
	o.CreatedAt.Unset()
}

// GetUpdatedAt returns the UpdatedAt field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *Subnet) GetUpdatedAt() time.Time {
	if o == nil || IsNil(o.UpdatedAt.Get()) {
		var ret time.Time
		return ret
	}
	return *o.UpdatedAt.Get()
}

// GetUpdatedAtOk returns a tuple with the UpdatedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *Subnet) GetUpdatedAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return o.UpdatedAt.Get(), o.UpdatedAt.IsSet()
}

// HasUpdatedAt returns a boolean if a field has been set.
func (o *Subnet) HasUpdatedAt() bool {
	if o != nil && o.UpdatedAt.IsSet() {
		return true
	}

	return false
}

// SetUpdatedAt gets a reference to the given NullableTime and assigns it to the UpdatedAt field.
func (o *Subnet) SetUpdatedAt(v time.Time) {
	o.UpdatedAt.Set(&v)
}

// SetUpdatedAtNil sets the value for UpdatedAt to be an explicit nil
func (o *Subnet) SetUpdatedAtNil() {
	o.UpdatedAt.Set(nil)
}

// UnsetUpdatedAt ensures that no value is present for UpdatedAt, not even an explicit nil
func (o *Subnet) UnsetUpdatedAt() {
	o.UpdatedAt.Unset()
}

// GetStatus returns the Status field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *Subnet) GetStatus() string {
	if o == nil || IsNil(o.Status.Get()) {
		var ret string
		return ret
	}
	return *o.Status.Get()
}

// GetStatusOk returns a tuple with the Status field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *Subnet) GetStatusOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Status.Get(), o.Status.IsSet()
}

// HasStatus returns a boolean if a field has been set.
func (o *Subnet) HasStatus() bool {
	if o != nil && o.Status.IsSet() {
		return true
	}

	return false
}

// SetStatus gets a reference to the given NullableString and assigns it to the Status field.
func (o *Subnet) SetStatus(v string) {
	o.Status.Set(&v)
}

// SetStatusNil sets the value for Status to be an explicit nil
func (o *Subnet) SetStatusNil() {
	o.Status.Set(nil)
}

// UnsetStatus ensures that no value is present for Status, not even an explicit nil
func (o *Subnet) UnsetStatus() {
	o.Status.Unset()
}

// GetNetworkId returns the NetworkId field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *Subnet) GetNetworkId() string {
	if o == nil || IsNil(o.NetworkId.Get()) {
		var ret string
		return ret
	}
	return *o.NetworkId.Get()
}

// GetNetworkIdOk returns a tuple with the NetworkId field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *Subnet) GetNetworkIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.NetworkId.Get(), o.NetworkId.IsSet()
}

// HasNetworkId returns a boolean if a field has been set.
func (o *Subnet) HasNetworkId() bool {
	if o != nil && o.NetworkId.IsSet() {
		return true
	}

	return false
}

// SetNetworkId gets a reference to the given NullableString and assigns it to the NetworkId field.
func (o *Subnet) SetNetworkId(v string) {
	o.NetworkId.Set(&v)
}

// SetNetworkIdNil sets the value for NetworkId to be an explicit nil
func (o *Subnet) SetNetworkIdNil() {
	o.NetworkId.Set(nil)
}

// UnsetNetworkId ensures that no value is present for NetworkId, not even an explicit nil
func (o *Subnet) UnsetNetworkId() {
	o.NetworkId.Unset()
}

// GetGatewayIp returns the GatewayIp field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *Subnet) GetGatewayIp() string {
	if o == nil || IsNil(o.GatewayIp.Get()) {
		var ret string
		return ret
	}
	return *o.GatewayIp.Get()
}

// GetGatewayIpOk returns a tuple with the GatewayIp field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *Subnet) GetGatewayIpOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.GatewayIp.Get(), o.GatewayIp.IsSet()
}

// HasGatewayIp returns a boolean if a field has been set.
func (o *Subnet) HasGatewayIp() bool {
	if o != nil && o.GatewayIp.IsSet() {
		return true
	}

	return false
}

// SetGatewayIp gets a reference to the given NullableString and assigns it to the GatewayIp field.
func (o *Subnet) SetGatewayIp(v string) {
	o.GatewayIp.Set(&v)
}

// SetGatewayIpNil sets the value for GatewayIp to be an explicit nil
func (o *Subnet) SetGatewayIpNil() {
	o.GatewayIp.Set(nil)
}

// UnsetGatewayIp ensures that no value is present for GatewayIp, not even an explicit nil
func (o *Subnet) UnsetGatewayIp() {
	o.GatewayIp.Unset()
}

// GetNetworkCidr returns the NetworkCidr field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *Subnet) GetNetworkCidr() string {
	if o == nil || IsNil(o.NetworkCidr.Get()) {
		var ret string
		return ret
	}
	return *o.NetworkCidr.Get()
}

// GetNetworkCidrOk returns a tuple with the NetworkCidr field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *Subnet) GetNetworkCidrOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.NetworkCidr.Get(), o.NetworkCidr.IsSet()
}

// HasNetworkCidr returns a boolean if a field has been set.
func (o *Subnet) HasNetworkCidr() bool {
	if o != nil && o.NetworkCidr.IsSet() {
		return true
	}

	return false
}

// SetNetworkCidr gets a reference to the given NullableString and assigns it to the NetworkCidr field.
func (o *Subnet) SetNetworkCidr(v string) {
	o.NetworkCidr.Set(&v)
}

// SetNetworkCidrNil sets the value for NetworkCidr to be an explicit nil
func (o *Subnet) SetNetworkCidrNil() {
	o.NetworkCidr.Set(nil)
}

// UnsetNetworkCidr ensures that no value is present for NetworkCidr, not even an explicit nil
func (o *Subnet) UnsetNetworkCidr() {
	o.NetworkCidr.Unset()
}

// GetEnableDhcp returns the EnableDhcp field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *Subnet) GetEnableDhcp() bool {
	if o == nil || IsNil(o.EnableDhcp.Get()) {
		var ret bool
		return ret
	}
	return *o.EnableDhcp.Get()
}

// GetEnableDhcpOk returns a tuple with the EnableDhcp field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *Subnet) GetEnableDhcpOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return o.EnableDhcp.Get(), o.EnableDhcp.IsSet()
}

// HasEnableDhcp returns a boolean if a field has been set.
func (o *Subnet) HasEnableDhcp() bool {
	if o != nil && o.EnableDhcp.IsSet() {
		return true
	}

	return false
}

// SetEnableDhcp gets a reference to the given NullableBool and assigns it to the EnableDhcp field.
func (o *Subnet) SetEnableDhcp(v bool) {
	o.EnableDhcp.Set(&v)
}

// SetEnableDhcpNil sets the value for EnableDhcp to be an explicit nil
func (o *Subnet) SetEnableDhcpNil() {
	o.EnableDhcp.Set(nil)
}

// UnsetEnableDhcp ensures that no value is present for EnableDhcp, not even an explicit nil
func (o *Subnet) UnsetEnableDhcp() {
	o.EnableDhcp.Unset()
}

// GetAllocationPools returns the AllocationPools field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *Subnet) GetAllocationPools() []AllocationPool {
	if o == nil {
		var ret []AllocationPool
		return ret
	}
	return o.AllocationPools
}

// GetAllocationPoolsOk returns a tuple with the AllocationPools field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *Subnet) GetAllocationPoolsOk() ([]AllocationPool, bool) {
	if o == nil || IsNil(o.AllocationPools) {
		return nil, false
	}
	return o.AllocationPools, true
}

// HasAllocationPools returns a boolean if a field has been set.
func (o *Subnet) HasAllocationPools() bool {
	if o != nil && !IsNil(o.AllocationPools) {
		return true
	}

	return false
}

// SetAllocationPools gets a reference to the given []AllocationPool and assigns it to the AllocationPools field.
func (o *Subnet) SetAllocationPools(v []AllocationPool) {
	o.AllocationPools = v
}

// GetDnsServers returns the DnsServers field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *Subnet) GetDnsServers() []string {
	if o == nil {
		var ret []string
		return ret
	}
	return o.DnsServers
}

// GetDnsServersOk returns a tuple with the DnsServers field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *Subnet) GetDnsServersOk() ([]string, bool) {
	if o == nil || IsNil(o.DnsServers) {
		return nil, false
	}
	return o.DnsServers, true
}

// HasDnsServers returns a boolean if a field has been set.
func (o *Subnet) HasDnsServers() bool {
	if o != nil && !IsNil(o.DnsServers) {
		return true
	}

	return false
}

// SetDnsServers gets a reference to the given []string and assigns it to the DnsServers field.
func (o *Subnet) SetDnsServers(v []string) {
	o.DnsServers = v
}

func (o Subnet) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if o.PckId.IsSet() {
		toSerialize["pckId"] = o.PckId.Get()
	}
	if o.ExternalId.IsSet() {
		toSerialize["externalId"] = o.ExternalId.Get()
	}
	if o.ProjectId.IsSet() {
		toSerialize["projectId"] = o.ProjectId.Get()
	}
	if o.Name.IsSet() {
		toSerialize["name"] = o.Name.Get()
	}
	if o.Description.IsSet() {
		toSerialize["description"] = o.Description.Get()
	}
	if o.AdminStateUp.IsSet() {
		toSerialize["adminStateUp"] = o.AdminStateUp.Get()
	}
	if o.Tags != nil {
		toSerialize["tags"] = o.Tags
	}
	if o.CreatedAt.IsSet() {
		toSerialize["createdAt"] = o.CreatedAt.Get()
	}
	if o.UpdatedAt.IsSet() {
		toSerialize["updatedAt"] = o.UpdatedAt.Get()
	}
	if o.Status.IsSet() {
		toSerialize["status"] = o.Status.Get()
	}
	if o.NetworkId.IsSet() {
		toSerialize["networkId"] = o.NetworkId.Get()
	}
	if o.GatewayIp.IsSet() {
		toSerialize["gatewayIp"] = o.GatewayIp.Get()
	}
	if o.NetworkCidr.IsSet() {
		toSerialize["networkCidr"] = o.NetworkCidr.Get()
	}
	if o.EnableDhcp.IsSet() {
		toSerialize["enableDhcp"] = o.EnableDhcp.Get()
	}
	if o.AllocationPools != nil {
		toSerialize["allocationPools"] = o.AllocationPools
	}
	if o.DnsServers != nil {
		toSerialize["dnsServers"] = o.DnsServers
	}
	return toSerialize, nil
}

type NullableSubnet struct {
	value *Subnet
	isSet bool
}

func (v NullableSubnet) Get() *Subnet {
	return v.value
}

func (v *NullableSubnet) Set(val *Subnet) {
	v.value = val
	v.isSet = true
}

func (v NullableSubnet) IsSet() bool {
	return v.isSet
}

func (v *NullableSubnet) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSubnet(val *Subnet) *NullableSubnet {
	return &NullableSubnet{value: val, isSet: true}
}

func (v NullableSubnet) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSubnet) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
