/*
Platforma OChK - Proxy API

Platforma OChK - Proxy API

API version: v1
Contact: pomoc@ochk.pl
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"time"
)

// checks if the QueryFilter type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &QueryFilter{}

// QueryFilter struct for QueryFilter
type QueryFilter struct {
	LogSeverity   *LogSeverity   `json:"logSeverity,omitempty"`
	UserName      NullableString `json:"userName,omitempty"`
	ResourceName  NullableString `json:"resourceName,omitempty"`
	Id            NullableString `json:"id,omitempty"`
	QueryString   NullableString `json:"queryString,omitempty"`
	StartDateTime NullableTime   `json:"startDateTime,omitempty"`
	EndDateTime   NullableTime   `json:"endDateTime,omitempty"`
}

// NewQueryFilter instantiates a new QueryFilter object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewQueryFilter() *QueryFilter {
	this := QueryFilter{}
	return &this
}

// NewQueryFilterWithDefaults instantiates a new QueryFilter object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewQueryFilterWithDefaults() *QueryFilter {
	this := QueryFilter{}
	return &this
}

// GetLogSeverity returns the LogSeverity field value if set, zero value otherwise.
func (o *QueryFilter) GetLogSeverity() LogSeverity {
	if o == nil || IsNil(o.LogSeverity) {
		var ret LogSeverity
		return ret
	}
	return *o.LogSeverity
}

// GetLogSeverityOk returns a tuple with the LogSeverity field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *QueryFilter) GetLogSeverityOk() (*LogSeverity, bool) {
	if o == nil || IsNil(o.LogSeverity) {
		return nil, false
	}
	return o.LogSeverity, true
}

// HasLogSeverity returns a boolean if a field has been set.
func (o *QueryFilter) HasLogSeverity() bool {
	if o != nil && !IsNil(o.LogSeverity) {
		return true
	}

	return false
}

// SetLogSeverity gets a reference to the given LogSeverity and assigns it to the LogSeverity field.
func (o *QueryFilter) SetLogSeverity(v LogSeverity) {
	o.LogSeverity = &v
}

// GetUserName returns the UserName field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *QueryFilter) GetUserName() string {
	if o == nil || IsNil(o.UserName.Get()) {
		var ret string
		return ret
	}
	return *o.UserName.Get()
}

// GetUserNameOk returns a tuple with the UserName field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *QueryFilter) GetUserNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.UserName.Get(), o.UserName.IsSet()
}

// HasUserName returns a boolean if a field has been set.
func (o *QueryFilter) HasUserName() bool {
	if o != nil && o.UserName.IsSet() {
		return true
	}

	return false
}

// SetUserName gets a reference to the given NullableString and assigns it to the UserName field.
func (o *QueryFilter) SetUserName(v string) {
	o.UserName.Set(&v)
}

// SetUserNameNil sets the value for UserName to be an explicit nil
func (o *QueryFilter) SetUserNameNil() {
	o.UserName.Set(nil)
}

// UnsetUserName ensures that no value is present for UserName, not even an explicit nil
func (o *QueryFilter) UnsetUserName() {
	o.UserName.Unset()
}

// GetResourceName returns the ResourceName field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *QueryFilter) GetResourceName() string {
	if o == nil || IsNil(o.ResourceName.Get()) {
		var ret string
		return ret
	}
	return *o.ResourceName.Get()
}

// GetResourceNameOk returns a tuple with the ResourceName field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *QueryFilter) GetResourceNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.ResourceName.Get(), o.ResourceName.IsSet()
}

// HasResourceName returns a boolean if a field has been set.
func (o *QueryFilter) HasResourceName() bool {
	if o != nil && o.ResourceName.IsSet() {
		return true
	}

	return false
}

// SetResourceName gets a reference to the given NullableString and assigns it to the ResourceName field.
func (o *QueryFilter) SetResourceName(v string) {
	o.ResourceName.Set(&v)
}

// SetResourceNameNil sets the value for ResourceName to be an explicit nil
func (o *QueryFilter) SetResourceNameNil() {
	o.ResourceName.Set(nil)
}

// UnsetResourceName ensures that no value is present for ResourceName, not even an explicit nil
func (o *QueryFilter) UnsetResourceName() {
	o.ResourceName.Unset()
}

// GetId returns the Id field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *QueryFilter) GetId() string {
	if o == nil || IsNil(o.Id.Get()) {
		var ret string
		return ret
	}
	return *o.Id.Get()
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *QueryFilter) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Id.Get(), o.Id.IsSet()
}

// HasId returns a boolean if a field has been set.
func (o *QueryFilter) HasId() bool {
	if o != nil && o.Id.IsSet() {
		return true
	}

	return false
}

// SetId gets a reference to the given NullableString and assigns it to the Id field.
func (o *QueryFilter) SetId(v string) {
	o.Id.Set(&v)
}

// SetIdNil sets the value for Id to be an explicit nil
func (o *QueryFilter) SetIdNil() {
	o.Id.Set(nil)
}

// UnsetId ensures that no value is present for Id, not even an explicit nil
func (o *QueryFilter) UnsetId() {
	o.Id.Unset()
}

// GetQueryString returns the QueryString field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *QueryFilter) GetQueryString() string {
	if o == nil || IsNil(o.QueryString.Get()) {
		var ret string
		return ret
	}
	return *o.QueryString.Get()
}

// GetQueryStringOk returns a tuple with the QueryString field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *QueryFilter) GetQueryStringOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.QueryString.Get(), o.QueryString.IsSet()
}

// HasQueryString returns a boolean if a field has been set.
func (o *QueryFilter) HasQueryString() bool {
	if o != nil && o.QueryString.IsSet() {
		return true
	}

	return false
}

// SetQueryString gets a reference to the given NullableString and assigns it to the QueryString field.
func (o *QueryFilter) SetQueryString(v string) {
	o.QueryString.Set(&v)
}

// SetQueryStringNil sets the value for QueryString to be an explicit nil
func (o *QueryFilter) SetQueryStringNil() {
	o.QueryString.Set(nil)
}

// UnsetQueryString ensures that no value is present for QueryString, not even an explicit nil
func (o *QueryFilter) UnsetQueryString() {
	o.QueryString.Unset()
}

// GetStartDateTime returns the StartDateTime field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *QueryFilter) GetStartDateTime() time.Time {
	if o == nil || IsNil(o.StartDateTime.Get()) {
		var ret time.Time
		return ret
	}
	return *o.StartDateTime.Get()
}

// GetStartDateTimeOk returns a tuple with the StartDateTime field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *QueryFilter) GetStartDateTimeOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return o.StartDateTime.Get(), o.StartDateTime.IsSet()
}

// HasStartDateTime returns a boolean if a field has been set.
func (o *QueryFilter) HasStartDateTime() bool {
	if o != nil && o.StartDateTime.IsSet() {
		return true
	}

	return false
}

// SetStartDateTime gets a reference to the given NullableTime and assigns it to the StartDateTime field.
func (o *QueryFilter) SetStartDateTime(v time.Time) {
	o.StartDateTime.Set(&v)
}

// SetStartDateTimeNil sets the value for StartDateTime to be an explicit nil
func (o *QueryFilter) SetStartDateTimeNil() {
	o.StartDateTime.Set(nil)
}

// UnsetStartDateTime ensures that no value is present for StartDateTime, not even an explicit nil
func (o *QueryFilter) UnsetStartDateTime() {
	o.StartDateTime.Unset()
}

// GetEndDateTime returns the EndDateTime field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *QueryFilter) GetEndDateTime() time.Time {
	if o == nil || IsNil(o.EndDateTime.Get()) {
		var ret time.Time
		return ret
	}
	return *o.EndDateTime.Get()
}

// GetEndDateTimeOk returns a tuple with the EndDateTime field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *QueryFilter) GetEndDateTimeOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return o.EndDateTime.Get(), o.EndDateTime.IsSet()
}

// HasEndDateTime returns a boolean if a field has been set.
func (o *QueryFilter) HasEndDateTime() bool {
	if o != nil && o.EndDateTime.IsSet() {
		return true
	}

	return false
}

// SetEndDateTime gets a reference to the given NullableTime and assigns it to the EndDateTime field.
func (o *QueryFilter) SetEndDateTime(v time.Time) {
	o.EndDateTime.Set(&v)
}

// SetEndDateTimeNil sets the value for EndDateTime to be an explicit nil
func (o *QueryFilter) SetEndDateTimeNil() {
	o.EndDateTime.Set(nil)
}

// UnsetEndDateTime ensures that no value is present for EndDateTime, not even an explicit nil
func (o *QueryFilter) UnsetEndDateTime() {
	o.EndDateTime.Unset()
}

func (o QueryFilter) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.LogSeverity) {
		toSerialize["logSeverity"] = o.LogSeverity
	}
	if o.UserName.IsSet() {
		toSerialize["userName"] = o.UserName.Get()
	}
	if o.ResourceName.IsSet() {
		toSerialize["resourceName"] = o.ResourceName.Get()
	}
	if o.Id.IsSet() {
		toSerialize["id"] = o.Id.Get()
	}
	if o.QueryString.IsSet() {
		toSerialize["queryString"] = o.QueryString.Get()
	}
	if o.StartDateTime.IsSet() {
		toSerialize["startDateTime"] = o.StartDateTime.Get()
	}
	if o.EndDateTime.IsSet() {
		toSerialize["endDateTime"] = o.EndDateTime.Get()
	}
	return toSerialize, nil
}

type NullableQueryFilter struct {
	value *QueryFilter
	isSet bool
}

func (v NullableQueryFilter) Get() *QueryFilter {
	return v.value
}

func (v *NullableQueryFilter) Set(val *QueryFilter) {
	v.value = val
	v.isSet = true
}

func (v NullableQueryFilter) IsSet() bool {
	return v.isSet
}

func (v *NullableQueryFilter) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableQueryFilter(val *QueryFilter) *NullableQueryFilter {
	return &NullableQueryFilter{value: val, isSet: true}
}

func (v NullableQueryFilter) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableQueryFilter) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
