/*
Platforma OChK - Proxy API

Platforma OChK - Proxy API

API version: v1
Contact: pomoc@ochk.pl
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"fmt"
)

// NATType the model 'NATType'
type NATType string

// List of NATType
const (
	NATTYPE_MANUAL NATType = "MANUAL"
	NATTYPE_AUTO   NATType = "AUTO"
)

// All allowed values of NATType enum
var AllowedNATTypeEnumValues = []NATType{
	"MANUAL",
	"AUTO",
}

func (v *NATType) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := NATType(value)
	for _, existing := range AllowedNATTypeEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid NATType", value)
}

// NewNATTypeFromValue returns a pointer to a valid NATType
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewNATTypeFromValue(v string) (*NATType, error) {
	ev := NATType(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for NATType: valid values are %v", v, AllowedNATTypeEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v NATType) IsValid() bool {
	for _, existing := range AllowedNATTypeEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to NATType value
func (v NATType) Ptr() *NATType {
	return &v
}

type NullableNATType struct {
	value *NATType
	isSet bool
}

func (v NullableNATType) Get() *NATType {
	return v.value
}

func (v *NullableNATType) Set(val *NATType) {
	v.value = val
	v.isSet = true
}

func (v NullableNATType) IsSet() bool {
	return v.isSet
}

func (v *NullableNATType) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableNATType(val *NATType) *NullableNATType {
	return &NullableNATType{value: val, isSet: true}
}

func (v NullableNATType) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableNATType) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
