/*
Platforma OChK - Proxy API

Platforma OChK - Proxy API

API version: v1
Contact: pomoc@ochk.pl
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the FailoverMode type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &FailoverMode{}

// FailoverMode struct for FailoverMode
type FailoverMode struct {
	FailoverModeId *int32         `json:"failoverModeId,omitempty"`
	FailoverMode   NullableString `json:"failoverMode,omitempty"`
}

// NewFailoverMode instantiates a new FailoverMode object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewFailoverMode() *FailoverMode {
	this := FailoverMode{}
	return &this
}

// NewFailoverModeWithDefaults instantiates a new FailoverMode object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewFailoverModeWithDefaults() *FailoverMode {
	this := FailoverMode{}
	return &this
}

// GetFailoverModeId returns the FailoverModeId field value if set, zero value otherwise.
func (o *FailoverMode) GetFailoverModeId() int32 {
	if o == nil || IsNil(o.FailoverModeId) {
		var ret int32
		return ret
	}
	return *o.FailoverModeId
}

// GetFailoverModeIdOk returns a tuple with the FailoverModeId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FailoverMode) GetFailoverModeIdOk() (*int32, bool) {
	if o == nil || IsNil(o.FailoverModeId) {
		return nil, false
	}
	return o.FailoverModeId, true
}

// HasFailoverModeId returns a boolean if a field has been set.
func (o *FailoverMode) HasFailoverModeId() bool {
	if o != nil && !IsNil(o.FailoverModeId) {
		return true
	}

	return false
}

// SetFailoverModeId gets a reference to the given int32 and assigns it to the FailoverModeId field.
func (o *FailoverMode) SetFailoverModeId(v int32) {
	o.FailoverModeId = &v
}

// GetFailoverMode returns the FailoverMode field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *FailoverMode) GetFailoverMode() string {
	if o == nil || IsNil(o.FailoverMode.Get()) {
		var ret string
		return ret
	}
	return *o.FailoverMode.Get()
}

// GetFailoverModeOk returns a tuple with the FailoverMode field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *FailoverMode) GetFailoverModeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.FailoverMode.Get(), o.FailoverMode.IsSet()
}

// HasFailoverMode returns a boolean if a field has been set.
func (o *FailoverMode) HasFailoverMode() bool {
	if o != nil && o.FailoverMode.IsSet() {
		return true
	}

	return false
}

// SetFailoverMode gets a reference to the given NullableString and assigns it to the FailoverMode field.
func (o *FailoverMode) SetFailoverMode(v string) {
	o.FailoverMode.Set(&v)
}

// SetFailoverModeNil sets the value for FailoverMode to be an explicit nil
func (o *FailoverMode) SetFailoverModeNil() {
	o.FailoverMode.Set(nil)
}

// UnsetFailoverMode ensures that no value is present for FailoverMode, not even an explicit nil
func (o *FailoverMode) UnsetFailoverMode() {
	o.FailoverMode.Unset()
}

func (o FailoverMode) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.FailoverModeId) {
		toSerialize["failoverModeId"] = o.FailoverModeId
	}
	if o.FailoverMode.IsSet() {
		toSerialize["failoverMode"] = o.FailoverMode.Get()
	}
	return toSerialize, nil
}

type NullableFailoverMode struct {
	value *FailoverMode
	isSet bool
}

func (v NullableFailoverMode) Get() *FailoverMode {
	return v.value
}

func (v *NullableFailoverMode) Set(val *FailoverMode) {
	v.value = val
	v.isSet = true
}

func (v NullableFailoverMode) IsSet() bool {
	return v.isSet
}

func (v *NullableFailoverMode) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableFailoverMode(val *FailoverMode) *NullableFailoverMode {
	return &NullableFailoverMode{value: val, isSet: true}
}

func (v NullableFailoverMode) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableFailoverMode) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
