variable "test-data-prefix" {}
variable "vrf_router" {}
variable "host" {}
variable "platform" {}
variable "api_key" {}
variable "debug_log_file" {}
variable "initial_password_for_vm" {}
variable "backup_list" {}
variable "backup_plan" {}
variable "ovf_image" {}
variable "iso_image" {}
