name: Terraform Provider Checks

on:
  push:
    branches:
      - master
  pull_request:
    paths:
      - .github/workflows/terraform_provider.yml
      - .golangci.yml
      - ochk/**
      - tools/**
      - go.sum
      - main.go

env:
  GO_VERSION: "1.16"
  GO111MODULE: on
  TERRAFORM_VERSION: "0.13.5"

jobs:
  go_build_test_lint:
    name: go build, test, lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: build
        run: go build ./...
      - name: run tests
        run: go test ./... -timeout=120s
      - name: run linter
        run: ./tools/lint.sh

  swagger-gen:
    name: swagger-gen
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: setup go
        uses: actions/setup-go@v2.1.3
        with:
          go-version: ${{ env.GO_VERSION }}
      - name: Run swagger_gen.sh
        run: ./tools/swagger_gen.sh
      - name: Check for Git Differences
        run: |
          git diff --compact-summary --exit-code || \
            (echo; echo "Unexpected difference in directories after swagger generation. Run './tools/swagger_gen.sh' command and commit."; exit 1)
